/**
 * lib/trilingual-leak.ts — deterministic detector for English leakage inside
 * trilingual BM/中文 sub-note segments (P3-01).
 *
 * Used by BOTH:
 *   • `scripts/validate-trilingual-direct-answer.ts` — prebuild gate over the
 *     notes generated by `lib/direct-answer-trilingual.ts` for all 29 services.
 *   • `scripts/part3-aeo-audit.ts` — post-build corpus rollup over the
 *     rendered `trilingual-sub` paragraphs.
 *
 * Why structural rules instead of "any ASCII word" counting: Malay is written
 * in the Latin script and its trade copy legitimately carries loanwords
 * ("grout", "top-hung", "ACP"), so a raw ASCII counter reports Malay itself as
 * a "leak". The rules below flag the *mechanism* of the defect — an English
 * source string interpolated into a BM/中文 sentence, an English unit token,
 * or enough English function words to constitute an untranslated clause:
 *
 *   L1  containment — a full English source field (title/tagline/warranty,
 *       ≥12 chars, matched case-insensitively) appears in the note;
 *   L2  unit tokens — `sq ft` / `sqft` / `psf` / `per square foot|feet`;
 *   L3  English function-word density — two or more of the closed-class words
 *       (the, and, for, with, from, your, our, this, that, per, including,
 *       depending) inside the note. Clean Malay/中文 copy contains zero of
 *       these standalone; any untranslated English sentence carries several.
 */

export const TRILINGUAL_UNIT_LEAK_RE = /\bsq\.?\s?ft\b|\bsqft\b|\bpsf\b|\bper square (?:foot|feet)\b/i;

const FUNCTION_WORDS = [
  "the", "and", "for", "with", "from", "your", "our", "this", "that", "per",
  "including", "depending"
];

export type TrilingualLeak = { rule: "L1" | "L2" | "L3"; detail: string };

/** Count standalone English function words in the note. */
function functionWordCount(note: string): { count: number; words: string[] } {
  const found: string[] = [];
  for (const w of FUNCTION_WORDS) {
    const n = (note.match(new RegExp(`(?:^|[^A-Za-z0-9_])${w}(?:[^A-Za-z0-9_]|$)`, "gi")) || []).length;
    if (n > 0) {
      found.push(`${w}×${n}`);
      for (let i = 1; i < n; i++) found.push(w); // weight repeats so 2×"and" = two hits
    }
  }
  return { count: found.length, words: found };
}

export function trilingualLeakSignatures(
  note: string,
  enFields: Partial<Record<"title" | "tagline" | "warranty", string>> = {}
): TrilingualLeak[] {
  const leaks: TrilingualLeak[] = [];
  const lower = note.toLowerCase();

  for (const [name, value] of Object.entries(enFields)) {
    const v = (value || "").trim().toLowerCase().replace(/[.。]+$/, "");
    // Only structural-English containment counts when the localized override
    // is actually different from the English source (a service may
    // legitimately reuse a proper noun). Guard length to avoid trivial hits.
    if (v.length >= 12 && lower.includes(v)) {
      leaks.push({ rule: "L1", detail: `EN ${name} interpolated verbatim into note` });
    }
  }

  const unit = note.match(new RegExp(TRILINGUAL_UNIT_LEAK_RE, "gi"));
  if (unit) leaks.push({ rule: "L2", detail: `English area unit token: ${[...new Set(unit.map((u) => u.trim()))].join(", ")}` });

  const fn = functionWordCount(note);
  if (fn.count >= 2) {
    leaks.push({ rule: "L3", detail: `English function-word density (${fn.words.join(", ")})` });
  }

  return leaks;
}
