// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe area navigation: slug, state and trilingual name. Import this
// from client components instead of `config/area-data.ts` / `lib/location-i18n`.

export type AreaNavItem = { slug: string; name: string; state: string; i18n: Record<"ms" | "zh", { name: string }> };

export const areaNavList: AreaNavItem[] = [
  {
    "slug": "kuala-lumpur",
    "name": "Kuala Lumpur",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Kuala Lumpur"
      },
      "zh": {
        "name": "吉隆坡"
      }
    }
  },
  {
    "slug": "petaling-jaya",
    "name": "Petaling Jaya",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Petaling Jaya"
      },
      "zh": {
        "name": "八打灵再也"
      }
    }
  },
  {
    "slug": "subang-jaya",
    "name": "Subang Jaya",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Subang Jaya"
      },
      "zh": {
        "name": "梳邦再也"
      }
    }
  },
  {
    "slug": "puchong",
    "name": "Puchong",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Puchong"
      },
      "zh": {
        "name": "蒲种"
      }
    }
  },
  {
    "slug": "shah-alam",
    "name": "Shah Alam",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Shah Alam"
      },
      "zh": {
        "name": "莎阿南"
      }
    }
  },
  {
    "slug": "klang",
    "name": "Klang",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Klang"
      },
      "zh": {
        "name": "巴生"
      }
    }
  },
  {
    "slug": "cheras",
    "name": "Cheras",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Cheras"
      },
      "zh": {
        "name": "蕉赖"
      }
    }
  },
  {
    "slug": "ampang",
    "name": "Ampang",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Ampang"
      },
      "zh": {
        "name": "安邦"
      }
    }
  },
  {
    "slug": "kajang",
    "name": "Kajang",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Kajang"
      },
      "zh": {
        "name": "加影"
      }
    }
  },
  {
    "slug": "mont-kiara",
    "name": "Mont Kiara",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Mont Kiara"
      },
      "zh": {
        "name": "满家乐"
      }
    }
  },
  {
    "slug": "bangsar",
    "name": "Bangsar",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Bangsar"
      },
      "zh": {
        "name": "孟沙"
      }
    }
  },
  {
    "slug": "damansara",
    "name": "Damansara",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Damansara"
      },
      "zh": {
        "name": "白沙罗"
      }
    }
  },
  {
    "slug": "kepong",
    "name": "Kepong",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Kepong"
      },
      "zh": {
        "name": "甲洞"
      }
    }
  },
  {
    "slug": "setapak",
    "name": "Setapak",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Setapak"
      },
      "zh": {
        "name": "文良港"
      }
    }
  },
  {
    "slug": "sri-petaling",
    "name": "Sri Petaling",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Sri Petaling"
      },
      "zh": {
        "name": "Sri Petaling"
      }
    }
  },
  {
    "slug": "kota-damansara",
    "name": "Kota Damansara",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Kota Damansara"
      },
      "zh": {
        "name": "哥打白沙罗"
      }
    }
  },
  {
    "slug": "ara-damansara",
    "name": "Ara Damansara",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Ara Damansara"
      },
      "zh": {
        "name": "阿拉白沙罗"
      }
    }
  },
  {
    "slug": "sunway",
    "name": "Sunway",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Sunway"
      },
      "zh": {
        "name": "双威"
      }
    }
  },
  {
    "slug": "usj",
    "name": "USJ",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "USJ"
      },
      "zh": {
        "name": "USJ"
      }
    }
  },
  {
    "slug": "putrajaya",
    "name": "Putrajaya",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Putrajaya"
      },
      "zh": {
        "name": "布城"
      }
    }
  },
  {
    "slug": "cyberjaya",
    "name": "Cyberjaya",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Cyberjaya"
      },
      "zh": {
        "name": "赛城"
      }
    }
  },
  {
    "slug": "wangsa-maju",
    "name": "Wangsa Maju",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Wangsa Maju"
      },
      "zh": {
        "name": "旺沙玛珠"
      }
    }
  },
  {
    "slug": "bukit-jalil",
    "name": "Bukit Jalil",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Bukit Jalil"
      },
      "zh": {
        "name": "武吉加里尔"
      }
    }
  },
  {
    "slug": "desa-parkcity",
    "name": "Desa ParkCity",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Desa ParkCity"
      },
      "zh": {
        "name": "Desa ParkCity"
      }
    }
  },
  {
    "slug": "taman-melawati",
    "name": "Taman Melawati",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Taman Melawati"
      },
      "zh": {
        "name": "Taman Melawati"
      }
    }
  },
  {
    "slug": "bandar-utama",
    "name": "Bandar Utama",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Bandar Utama"
      },
      "zh": {
        "name": "万达镇"
      }
    }
  },
  {
    "slug": "ss2",
    "name": "SS2",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "SS2"
      },
      "zh": {
        "name": "SS2"
      }
    }
  },
  {
    "slug": "setia-alam",
    "name": "Setia Alam",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Setia Alam"
      },
      "zh": {
        "name": "Setia Alam"
      }
    }
  },
  {
    "slug": "kota-kemuning",
    "name": "Kota Kemuning",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Kota Kemuning"
      },
      "zh": {
        "name": "Kota Kemuning"
      }
    }
  },
  {
    "slug": "batu-caves",
    "name": "Batu Caves",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Batu Caves"
      },
      "zh": {
        "name": "黑风洞"
      }
    }
  },
  {
    "slug": "selayang",
    "name": "Selayang",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Selayang"
      },
      "zh": {
        "name": "士拉央"
      }
    }
  },
  {
    "slug": "rawang",
    "name": "Rawang",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Rawang"
      },
      "zh": {
        "name": "万挠"
      }
    }
  },
  {
    "slug": "sungai-buloh",
    "name": "Sungai Buloh",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Sungai Buloh"
      },
      "zh": {
        "name": "双溪毛糯"
      }
    }
  },
  {
    "slug": "semenyih",
    "name": "Semenyih",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Semenyih"
      },
      "zh": {
        "name": "士毛月"
      }
    }
  },
  {
    "slug": "seri-kembangan",
    "name": "Seri Kembangan",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Seri Kembangan"
      },
      "zh": {
        "name": "Seri Kembangan"
      }
    }
  },
  {
    "slug": "pandan-indah",
    "name": "Pandan Indah",
    "state": "Selangor",
    "i18n": {
      "ms": {
        "name": "Pandan Indah"
      },
      "zh": {
        "name": "Pandan Indah"
      }
    }
  },
  {
    "slug": "sentul",
    "name": "Sentul",
    "state": "Kuala Lumpur",
    "i18n": {
      "ms": {
        "name": "Sentul"
      },
      "zh": {
        "name": "沈都"
      }
    }
  }
];

export const areaNavBySlug: Record<string, AreaNavItem> = Object.fromEntries(
  areaNavList.map((area) => [area.slug, area])
);

export function getLocalizedAreaName(area: AreaNavItem, locale: "en" | "ms" | "zh"): string {
  return locale === "en" ? area.name : area.i18n[locale].name || area.name;
}
