// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe sibling index for the generic content pages. Import this from
// client components instead of `config/content-data.ts`.

export type ContentNavItem = {
  slug: string;
  title: string;
  category: string;
  /** First 120 characters of the page intro — the only part rendered on cards. */
  intro: string;
  relatedServiceSlug?: string;
};

export const contentNavList: ContentNavItem[] = [
  {
    "slug": "interior-painting-kl",
    "title": "Interior Painting in KL",
    "category": "Service Cluster",
    "intro": "A complete hub for interior wall painting, preparation, primer, washable paint, colour selection, and room-by-room sched",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "exterior-painting-kl",
    "title": "Exterior Painting in KL",
    "category": "Service Cluster",
    "intro": "A practical guide to exterior coating systems that survive Klang Valley UV exposure, rain, algae, and hairline masonry c",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "commercial-painting-kl",
    "title": "Commercial Painting in KL",
    "category": "Service Cluster",
    "intro": "Guidance for office, shoplot, and retail painting with after-hours scheduling, odor control, and handover deadlines.",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "leak-repair-kl",
    "title": "Leak Repair in KL",
    "category": "Service Cluster",
    "intro": "A local guide to visible and hidden pipe leaks, leak detection, pipe replacement, and pressure testing before handover.",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "installation-kl",
    "title": "Plumbing Installation in KL",
    "category": "Service Cluster",
    "intro": "A homeowner guide for taps, sinks, toilet bowls, water heaters, pumps, and fixture replacement in Malaysian homes.",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "emergency-plumbing-kl",
    "title": "Emergency Plumbing in KL",
    "category": "Service Cluster",
    "intro": "A fast-response guide for burst pipes, major leaks, blocked toilets, and urgent water shut-off actions.",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "ceiling-installation-kl",
    "title": "Ceiling Installation in KL",
    "category": "Service Cluster",
    "intro": "A practical ceiling installation hub covering gypsum boards, GI frames, L-boxes, downlight openings, and skim finishing.",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "repair-kl",
    "title": "Ceiling Repair in KL",
    "category": "Service Cluster",
    "intro": "A guide to cracked, stained, sagging, or water-damaged ceilings and when to replace boards instead of patching only.",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "partition-kl",
    "title": "Gypsum Partition Services KL & Selangor",
    "category": "Service Cluster",
    "intro": "Gypsum partitions for homes and offices across KL & Selangor, with metal framing, soundproofing, board options and smoot",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "bathroom-kl",
    "title": "Bathroom Waterproofing in KL",
    "category": "Service Cluster",
    "intro": "A focused hub for bathroom leaks, no-hack sealing, PU grouting, full membrane replacement, and water ponding tests.",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "roof-kl",
    "title": "Roof Waterproofing in KL",
    "category": "Service Cluster",
    "intro": "A roof and concrete slab guide covering membranes, crack routing, ponding, UV exposure, and rainy-season leak prevention",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "pu-grouting-kl",
    "title": "PU Grouting in KL",
    "category": "Service Cluster",
    "intro": "An in-depth hub on polyurethane injection for active concrete cracks and inter-floor leaks without unnecessary tile hack",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "tv-mounting-kl",
    "title": "TV Mounting in KL",
    "category": "Service Cluster",
    "intro": "A safety-first guide to mounting TVs on brick, concrete, and gypsum walls with the correct anchor system.",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "door-lock-kl",
    "title": "Door and Lock Repair in KL",
    "category": "Service Cluster",
    "intro": "A practical guide for sagging doors, hinges, latch alignment, lockset replacement, and digital lock preparation.",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "furniture-assembly-kl",
    "title": "Furniture Assembly in KL",
    "category": "Service Cluster",
    "intro": "A flat-pack assembly hub covering wardrobes, beds, desks, shelving, safety anchoring, and adjustment.",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "1hp-aircon-installation-kl",
    "title": "1 HP Aircon Installation in KL",
    "category": "Service Cluster",
    "intro": "A focused hub for installing a 1 HP wall-mounted aircon across KL & Selangor, with pricing, what's included and what the",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "1-5hp-aircon-installation-kl",
    "title": "1.5 HP Aircon Installation in KL",
    "category": "Service Cluster",
    "intro": "A practical guide to installing a 1.5 HP wall-mounted aircon — the most common size for Malaysian bedrooms and small liv",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "2hp-aircon-installation-kl",
    "title": "2 HP Aircon Installation in KL",
    "category": "Service Cluster",
    "intro": "Guidance for installing a 2 HP wall-mounted aircon for larger rooms, including pricing and copper pipe allowances.",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "ceiling-cassette-installation-kl",
    "title": "Ceiling Cassette Installation in KL",
    "category": "Service Cluster",
    "intro": "A hub for commercial and high-ceiling ceiling cassette installation, covering 1.0–1.5 HP and larger cassette pricing.",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "commercial-aircon-installation-kl",
    "title": "Commercial Aircon Installation in KL",
    "category": "Service Cluster",
    "intro": "A guide to commercial aircon installation for offices, shops and restaurants, including ceiling cassettes and multi-unit",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "how-to-choose-house-painter-kl",
    "title": "How to Choose a House Painter in KL",
    "category": "Painting",
    "intro": "How to Choose a House Painter in KL explains practical decision criteria, pricing signals, material quality checks, warr"
  },
  {
    "slug": "how-to-choose-plumber-kl",
    "title": "How to Choose a Plumber in KL",
    "category": "Plumbing",
    "intro": "How to Choose a Plumber in KL explains practical decision criteria, pricing signals, material quality checks, warranty q"
  },
  {
    "slug": "how-to-choose-waterproofing-contractor-kl",
    "title": "How to Choose a Waterproofing Contractor in KL",
    "category": "Waterproofing",
    "intro": "How to Choose a Waterproofing Contractor in KL explains practical decision criteria, pricing signals, material quality c"
  },
  {
    "slug": "how-to-choose-ceiling-contractor-kl",
    "title": "How to Choose a Ceiling Contractor in KL",
    "category": "Ceiling",
    "intro": "How to Choose a Ceiling Contractor in KL explains practical decision criteria, pricing signals, material quality checks,"
  },
  {
    "slug": "how-to-choose-handyman-kl",
    "title": "How to Choose a Handyman in KL",
    "category": "Handyman",
    "intro": "How to Choose a Handyman in KL explains practical decision criteria, pricing signals, material quality checks, warranty "
  },
  {
    "slug": "paint-brand-comparison-nippon-vs-dulux-vs-jotun",
    "title": "Paint Brand Comparison: Nippon vs Dulux vs Jotun",
    "category": "Painting",
    "intro": "Paint Brand Comparison: Nippon vs Dulux vs Jotun explains practical decision criteria, pricing signals, material quality"
  },
  {
    "slug": "waterproofing-method-comparison-pu-vs-membrane",
    "title": "Waterproofing Method Comparison: PU vs Membrane",
    "category": "Waterproofing",
    "intro": "Waterproofing Method Comparison: PU vs Membrane explains practical decision criteria, pricing signals, material quality "
  },
  {
    "slug": "ceiling-material-comparison-plaster-vs-gypsum",
    "title": "Ceiling Material Comparison: Plaster vs Gypsum",
    "category": "Ceiling",
    "intro": "Ceiling Material Comparison: Plaster vs Gypsum explains practical decision criteria, pricing signals, material quality c"
  },
  {
    "slug": "plumbing-pipe-comparison-pvc-vs-copper-vs-ppr",
    "title": "Plumbing Pipe Comparison: PVC vs Copper vs PPR",
    "category": "Plumbing",
    "intro": "Plumbing Pipe Comparison: PVC vs Copper vs PPR explains practical decision criteria, pricing signals, material quality c"
  },
  {
    "slug": "tv-mount-types-comparison-fixed-vs-tilt-vs-full-motion",
    "title": "TV Mount Types: Fixed vs Tilt vs Full-Motion",
    "category": "Handyman",
    "intro": "TV Mount Types: Fixed vs Tilt vs Full-Motion explains practical decision criteria, pricing signals, material quality che"
  },
  {
    "slug": "pu-grouting-vs-tile-hacking",
    "title": "PU Grouting vs Tile Hacking",
    "category": "Comparison",
    "intro": "PU Grouting vs Tile Hacking compares use cases, cost ranges, durability, disruption level, and suitability for KL and Se"
  },
  {
    "slug": "plaster-ceiling-vs-gypsum-ceiling",
    "title": "Plaster Ceiling vs Gypsum Ceiling",
    "category": "Comparison",
    "intro": "Plaster Ceiling vs Gypsum Ceiling compares use cases, cost ranges, durability, disruption level, and suitability for KL "
  },
  {
    "slug": "nippon-paint-vs-dulux-paint",
    "title": "Nippon Paint vs Dulux Paint",
    "category": "Comparison",
    "intro": "Nippon Paint vs Dulux Paint compares use cases, cost ranges, durability, disruption level, and suitability for KL and Se"
  },
  {
    "slug": "acrylic-vs-cementitious-waterproofing",
    "title": "Acrylic vs Cementitious Waterproofing",
    "category": "Comparison",
    "intro": "Acrylic vs Cementitious Waterproofing compares use cases, cost ranges, durability, disruption level, and suitability for"
  },
  {
    "slug": "pvc-pipes-vs-copper-pipes",
    "title": "PVC Pipes vs Copper Pipes",
    "category": "Comparison",
    "intro": "PVC Pipes vs Copper Pipes compares use cases, cost ranges, durability, disruption level, and suitability for KL and Sela"
  },
  {
    "slug": "pvc-vs-molly-bolt-anchors",
    "title": "PVC Plugs vs Molly Bolt Anchors",
    "category": "Comparison",
    "intro": "PVC Plugs vs Molly Bolt Anchors compares use cases, cost ranges, durability, disruption level, and suitability for KL an"
  },
  {
    "slug": "interior-paint-finishes-matte-vs-satin-vs-gloss",
    "title": "Interior Paint Finishes: Matte vs Satin vs Gloss",
    "category": "Comparison",
    "intro": "Interior Paint Finishes: Matte vs Satin vs Gloss compares use cases, cost ranges, durability, disruption level, and suit"
  },
  {
    "slug": "wall-putty-vs-plaster-smoothening",
    "title": "Wall Putty vs Plaster Smoothening",
    "category": "Comparison",
    "intro": "Wall Putty vs Plaster Smoothening compares use cases, cost ranges, durability, disruption level, and suitability for KL "
  },
  {
    "slug": "partition-materials-gypsum-vs-bricks-vs-glass",
    "title": "Partition Materials: Gypsum vs Bricks vs Glass",
    "category": "Comparison",
    "intro": "Partition Materials: Gypsum vs Bricks vs Glass compares use cases, cost ranges, durability, disruption level, and suitab"
  },
  {
    "slug": "diy-painting-vs-professional-painting",
    "title": "DIY Painting vs Professional Painting",
    "category": "Comparison",
    "intro": "DIY Painting vs Professional Painting compares use cases, cost ranges, durability, disruption level, and suitability for"
  },
  {
    "slug": "cheap-handyman-vs-insured-contractor",
    "title": "Cheap Handyman vs Insured Contractor",
    "category": "Comparison",
    "intro": "Cheap Handyman vs Insured Contractor compares use cases, cost ranges, durability, disruption level, and suitability for "
  },
  {
    "slug": "pu-injection-vs-surface-waterproofing",
    "title": "PU Injection vs Surface Waterproofing",
    "category": "Comparison",
    "intro": "PU Injection vs Surface Waterproofing compares use cases, cost ranges, durability, disruption level, and suitability for"
  },
  {
    "slug": "fixed-quote-vs-hourly-handyman",
    "title": "Fixed Quote vs Hourly Handyman",
    "category": "Comparison",
    "intro": "Fixed Quote vs Hourly Handyman compares use cases, cost ranges, durability, disruption level, and suitability for KL and"
  },
  {
    "slug": "drywall-partition-vs-glass-partition",
    "title": "Drywall Partition vs Glass Partition",
    "category": "Comparison",
    "intro": "Drywall Partition vs Glass Partition compares use cases, cost ranges, durability, disruption level, and suitability for "
  },
  {
    "slug": "roof-coating-vs-torch-on-membrane",
    "title": "Roof Coating vs Torch-On Membrane",
    "category": "Comparison",
    "intro": "Roof Coating vs Torch-On Membrane compares use cases, cost ranges, durability, disruption level, and suitability for KL "
  },
  {
    "slug": "chemical-wash-vs-chemical-overhaul",
    "title": "Chemical Wash vs Chemical Overhaul",
    "category": "Comparison",
    "intro": "Chemical Wash vs Chemical Overhaul compares use cases, cost ranges, durability, disruption level, and suitability for KL"
  },
  {
    "slug": "inverter-vs-non-inverter-aircon",
    "title": "Inverter vs Non-Inverter Aircon",
    "category": "Comparison",
    "intro": "Inverter vs Non-Inverter Aircon compares use cases, cost ranges, durability, disruption level, and suitability for KL an"
  },
  {
    "slug": "wall-mounted-vs-ceiling-cassette-aircon",
    "title": "Wall-Mounted vs Ceiling Cassette Aircon",
    "category": "Comparison",
    "intro": "Wall-Mounted vs Ceiling Cassette Aircon compares use cases, cost ranges, durability, disruption level, and suitability f"
  },
  {
    "slug": "painting-maintenance-schedule",
    "title": "Painting Maintenance Schedule",
    "category": "Maintenance Guide",
    "intro": "Painting Maintenance Schedule provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequen"
  },
  {
    "slug": "plumbing-annual-checklist",
    "title": "Plumbing Annual Checklist",
    "category": "Maintenance Guide",
    "intro": "Plumbing Annual Checklist provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequency, "
  },
  {
    "slug": "ceiling-maintenance-tips",
    "title": "Ceiling Maintenance Tips",
    "category": "Maintenance Guide",
    "intro": "Ceiling Maintenance Tips provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequency, r"
  },
  {
    "slug": "waterproofing-recheck-schedule",
    "title": "Waterproofing Recheck Schedule",
    "category": "Maintenance Guide",
    "intro": "Waterproofing Recheck Schedule provides a practical checklist for Malaysian homes, with tasks grouped by urgency, freque"
  },
  {
    "slug": "home-handyman-monthly-checklist",
    "title": "Home Handyman Monthly Checklist",
    "category": "Maintenance Guide",
    "intro": "Home Handyman Monthly Checklist provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequ"
  },
  {
    "slug": "rainy-season-home-prep",
    "title": "Rainy Season Home Prep",
    "category": "Maintenance Guide",
    "intro": "Rainy Season Home Prep provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequency, rai"
  },
  {
    "slug": "post-renovation-cleanup-checklist",
    "title": "Post Renovation Cleanup Checklist",
    "category": "Maintenance Guide",
    "intro": "Post Renovation Cleanup Checklist provides a practical checklist for Malaysian homes, with tasks grouped by urgency, fre"
  },
  {
    "slug": "condo-maintenance-checklist",
    "title": "Condo Maintenance Checklist",
    "category": "Maintenance Guide",
    "intro": "Condo Maintenance Checklist provides a practical checklist for Malaysian homes, with tasks grouped by urgency, frequency"
  },
  {
    "slug": "landed-house-maintenance-calendar",
    "title": "Landed House Maintenance Calendar",
    "category": "Maintenance Guide",
    "intro": "Landed House Maintenance Calendar provides a practical checklist for Malaysian homes, with tasks grouped by urgency, fre"
  },
  {
    "slug": "rental-property-turnover-checklist",
    "title": "Rental Property Turnover Checklist",
    "category": "Maintenance Guide",
    "intro": "Rental Property Turnover Checklist provides a practical checklist for Malaysian homes, with tasks grouped by urgency, fr"
  },
  {
    "slug": "home-prep-rainy-season-kl",
    "title": "Home Prep Rainy Season Kl",
    "category": "Seasonal",
    "intro": "Home Prep Rainy Season Kl offers season-aware planning for KL and Selangor homes, with practical timing around Malaysian"
  },
  {
    "slug": "painting-dry-season-tips",
    "title": "Painting Dry Season Tips",
    "category": "Seasonal",
    "intro": "Painting Dry Season Tips offers season-aware planning for KL and Selangor homes, with practical timing around Malaysian "
  },
  {
    "slug": "waterproofing-pre-monsoon-checklist",
    "title": "Waterproofing Pre Monsoon Checklist",
    "category": "Seasonal",
    "intro": "Waterproofing Pre Monsoon Checklist offers season-aware planning for KL and Selangor homes, with practical timing around"
  },
  {
    "slug": "chinese-new-year-home-repaint-guide",
    "title": "Chinese New Year Home Repaint Guide",
    "category": "Seasonal",
    "intro": "Chinese New Year Home Repaint Guide offers season-aware planning for KL and Selangor homes, with practical timing around"
  },
  {
    "slug": "raya-home-makeover-checklist",
    "title": "Raya Home Makeover Checklist",
    "category": "Seasonal",
    "intro": "Raya Home Makeover Checklist offers season-aware planning for KL and Selangor homes, with practical timing around Malays"
  },
  {
    "slug": "year-end-renovation-planning",
    "title": "Year End Renovation Planning",
    "category": "Seasonal",
    "intro": "Year End Renovation Planning offers season-aware planning for KL and Selangor homes, with practical timing around Malays"
  },
  {
    "slug": "hari-raya-painting-promo",
    "title": "Hari Raya Painting Promo",
    "category": "Seasonal",
    "intro": "Hari Raya Painting Promo offers season-aware planning for KL and Selangor homes, with practical timing around Malaysian "
  },
  {
    "slug": "monsoon-leak-emergency-guide",
    "title": "Monsoon Leak Emergency Guide",
    "category": "Seasonal",
    "intro": "Monsoon Leak Emergency Guide offers season-aware planning for KL and Selangor homes, with practical timing around Malays"
  },
  {
    "slug": "painting-services-kl",
    "title": "Commercial House Painting Services in KL",
    "category": "Commercial",
    "intro": "Offices, shoplots and showrooms repainted after hours with low-odour systems, brand-colour matching and clean handover b",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "plumbing-services-kl",
    "title": "Commercial Plumbing & Leak Repair Services in KL",
    "category": "Commercial",
    "intro": "Commercial plumbing for F&B units, offices and strata plant rooms: leak isolation, riser and washroom repairs, pump work",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "ceiling-services-kl",
    "title": "Commercial Ceiling & Partition Services in KL",
    "category": "Commercial",
    "intro": "Gypsum ceilings and partitions for offices and retail — laser-level framing, MEP access panels, tidy board schedules and",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "waterproofing-services-kl",
    "title": "Commercial Waterproofing & Leak Repair Services in KL",
    "category": "Commercial",
    "intro": "Warehouse roofs, podium decks and planter boxes: torch-on membranes, PU injection and ponding tests, documented for land",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "handyman-services-kl",
    "title": "Commercial Handyman Services in KL",
    "category": "Commercial",
    "intro": "One work order, one tidy visit: signage and screen mounting, door and furniture fixes, anchor checks and wall repairs fo",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "house-renovation-services-kl",
    "title": "Commercial Complete House Renovation in KL",
    "category": "Commercial",
    "intro": "Office and F&B fit-out refurbishment for Klang Valley tenancies: knock-down, rebuild and finishing sequenced around land",
    "relatedServiceSlug": "house-renovation"
  },
  {
    "slug": "electrical-services-kl",
    "title": "Commercial Licensed Electrical Services in KL",
    "category": "Commercial",
    "intro": "Commercial electrical for units and offices: dedicated appliance circuits, DB upgrades, ST-licensed wiremen and test rec",
    "relatedServiceSlug": "electrical"
  },
  {
    "slug": "water-heater-services-kl",
    "title": "Commercial Water Heater Installation & Repair in KL",
    "category": "Commercial",
    "intro": "Pantry and staff-quarter hot water for offices, salons and F&B back-of-house: heater supply, dedicated points and descal",
    "relatedServiceSlug": "water-heater"
  },
  {
    "slug": "ceiling-fan-services-kl",
    "title": "Commercial Ceiling Fan Installation & Replacement in KL",
    "category": "Commercial",
    "intro": "Showroom, classroom and workshop fans: high-mount installs, balancing and regulator checks — with double-height spaces s",
    "relatedServiceSlug": "ceiling-fan"
  },
  {
    "slug": "lighting-services-kl",
    "title": "Commercial Lighting Design & Installation in KL",
    "category": "Commercial",
    "intro": "Downlight grids, track heads and LED retrofits for retail and offices: energy-first relamping, driver swaps and high-lev",
    "relatedServiceSlug": "lighting"
  },
  {
    "slug": "tiling-services-kl",
    "title": "Commercial Professional Tiling & Tile Repair in KL",
    "category": "Commercial",
    "intro": "Lobbies, corridors and wet commercial areas: large-format and anti-slip tile schedules, setting-out drawings and phased ",
    "relatedServiceSlug": "tiling"
  },
  {
    "slug": "plaster-ceiling-services-kl",
    "title": "Commercial Plaster Ceiling Design & Build in KL",
    "category": "Commercial",
    "intro": "Feature plaster, cove strips and bulkheads for lobbies and showrooms — decorative systems backed by a 10-year sag-free w",
    "relatedServiceSlug": "plaster-ceiling"
  },
  {
    "slug": "skim-coat-services-kl",
    "title": "Commercial Wall & Ceiling Skim Coat in KL",
    "category": "Commercial",
    "intro": "Photo-ready wall finishes for showrooms and handovers: full surface prep and glass-smooth skim before final paint and th",
    "relatedServiceSlug": "skim-coat"
  },
  {
    "slug": "flooring-services-kl",
    "title": "Commercial Vinyl, SPC & Laminate Flooring in KL",
    "category": "Commercial",
    "intro": "SPC and vinyl for offices, studios and shoplots: caster-rated build-ups, transition details to common floors and phased ",
    "relatedServiceSlug": "flooring"
  },
  {
    "slug": "epoxy-flooring-services-kl",
    "title": "Commercial Epoxy & Polyurethane Flooring in KL",
    "category": "Commercial",
    "intro": "Warehouse bays, workshop floors and car-park decks: self-levelled epoxy and anti-slip topcoats with coved skirtings, lai",
    "relatedServiceSlug": "epoxy-flooring"
  },
  {
    "slug": "roof-repair-services-kl",
    "title": "Commercial Roof Repair & Waterproofing in KL",
    "category": "Commercial",
    "intro": "Shed, factory and shoplot roof fixes: sheet replacement, flashing and ridge seals, skylight re-bedding and membrane syst",
    "relatedServiceSlug": "roof-repair"
  },
  {
    "slug": "kitchen-cabinet-services-kl",
    "title": "Commercial Kitchen Cabinet & Countertop in KL",
    "category": "Commercial",
    "intro": "Café counters, staff pantries and prep lines: cabinet structures sized to the workflow, laminate fronts matched to brand",
    "relatedServiceSlug": "kitchen-cabinet"
  },
  {
    "slug": "carpentry-services-kl",
    "title": "Commercial Custom Carpentry & Joinery in KL",
    "category": "Commercial",
    "intro": "Reception joinery, display walls and back-of-house fit-outs: brand-matched veneers and laminates, fabricated ahead and i",
    "relatedServiceSlug": "carpentry"
  },
  {
    "slug": "door-services-kl",
    "title": "Commercial Door Repair & Installation in KL",
    "category": "Commercial",
    "intro": "High-traffic commercial doors: closers and hinges on heavy cycles, patch and clamp fittings for glass entrances, alignme",
    "relatedServiceSlug": "door"
  },
  {
    "slug": "window-repair-services-kl",
    "title": "Commercial Window Repair & Glass Replacement in KL",
    "category": "Commercial",
    "intro": "Shopfront and office windows: seal and gasket renewal, stiff sliding tracks, rollers and handles — including high-level ",
    "relatedServiceSlug": "window-repair"
  },
  {
    "slug": "locksmith-services-kl",
    "title": "Commercial Locksmith & Smart Lock Services in KL",
    "category": "Commercial",
    "intro": "Offices, stockrooms and warehouses: master-key planning, cylinder changes on tenant turnover, panic-exit hardware servic",
    "relatedServiceSlug": "locksmith"
  },
  {
    "slug": "glass-aluminium-services-kl",
    "title": "Commercial Glass & Aluminium Fabrication in KL",
    "category": "Commercial",
    "intro": "Storefront glass, aluminium partitions and glass doors for retail and offices: framing, fittings and seals installed to ",
    "relatedServiceSlug": "glass-aluminium"
  },
  {
    "slug": "cctv-services-kl",
    "title": "Commercial CCTV & Security Camera Installation in KL",
    "category": "Commercial",
    "intro": "Retail and warehouse coverage: camera planning against your floor plan, recorder retention settings and remote view — co",
    "relatedServiceSlug": "cctv"
  },
  {
    "slug": "autogate-services-kl",
    "title": "Commercial Auto Gate & Motorised Gate in KL",
    "category": "Commercial",
    "intro": "Shared lots and factory yards: sliding and swing gate automation, safety beams and intercom tie-ins, plus service plans ",
    "relatedServiceSlug": "autogate"
  },
  {
    "slug": "welding-services-kl",
    "title": "Commercial Welding & Metal Fabrication in KL",
    "category": "Commercial",
    "intro": "Fabrication and repair for workshops and yards: gates, grilles, canopies and stainless back-of-house work — site-welded,",
    "relatedServiceSlug": "welding"
  },
  {
    "slug": "aircon-services-kl",
    "title": "Commercial Aircon Service, Repair & Installation in KL",
    "category": "Commercial",
    "intro": "Office and restaurant aircon: cassette and multi-split servicing after trade hours, chemical wash cycles, gas checks and",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "kitchen-renovation-services-kl",
    "title": "Commercial Kitchen Renovation in KL",
    "category": "Commercial",
    "intro": "Café, canteen and F&B kitchen refurbs: tiling, counters, water and drainage rework sequenced for the shortest close, quo",
    "relatedServiceSlug": "kitchen-renovation"
  },
  {
    "slug": "bathroom-renovation-services-kl",
    "title": "Commercial Bathroom Renovation in KL",
    "category": "Commercial",
    "intro": "Office and mall washroom refurbishment: one cubicle at a time keeps facilities open, with anti-slip floors, fixture swap",
    "relatedServiceSlug": "bathroom-renovation"
  },
  {
    "slug": "awning-installation-services-kl",
    "title": "Commercial Awning Installation Services in KL",
    "category": "Commercial",
    "intro": "Shoplot and alfresco awnings: five-footway-cleared designs, council-aware fabrication, after-hours installs where needed",
    "relatedServiceSlug": "awning-installation"
  },
  {
    "slug": "painting-services-kl",
    "title": "Residential House Painting Services in KL",
    "category": "Residential",
    "intro": "Interior and exterior repainting for occupied homes: wrapped furniture, low-odour washable systems and room-by-room hand",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "plumbing-services-kl",
    "title": "Residential Plumbing & Leak Repair Services in KL",
    "category": "Residential",
    "intro": "Home plumbing for condos and landed houses: leak tracing, fixture and heater work, pumps and pressures — isolation expla",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "ceiling-services-kl",
    "title": "Residential Ceiling & Partition Services in KL",
    "category": "Residential",
    "intro": "Gypsum ceilings and partitions for homes: laser-level framing, moisture-resistant boards where it counts and downlight-r",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "waterproofing-services-kl",
    "title": "Residential Waterproofing & Leak Repair Services in KL",
    "category": "Residential",
    "intro": "Bathroom, balcony and roof leaks for homes: no-hack PU options where possible, membrane systems where needed, and pondin",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "handyman-services-kl",
    "title": "Residential Handyman Services in KL",
    "category": "Residential",
    "intro": "The mounted, fixed, hung and assembled jobs for homes: TVs anchored to the right wall, furniture assembled, doors and sh",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "house-renovation-services-kl",
    "title": "Residential Complete House Renovation in KL",
    "category": "Residential",
    "intro": "Whole-home renovation for condos, terraces and bungalows: phased so you can keep living in parts of the home, with itemi",
    "relatedServiceSlug": "house-renovation"
  },
  {
    "slug": "electrical-services-kl",
    "title": "Residential Licensed Electrical Services in KL",
    "category": "Residential",
    "intro": "Home wiring and points by ST-registered wiremen: dedicated circuits for aircons and kitchen gear, DB upgrades, labelled ",
    "relatedServiceSlug": "electrical"
  },
  {
    "slug": "water-heater-services-kl",
    "title": "Residential Water Heater Installation & Repair in KL",
    "category": "Residential",
    "intro": "Instant and storage heaters for Malaysian bathrooms: supply, installation on a dedicated tested point, and descaling whe",
    "relatedServiceSlug": "water-heater"
  },
  {
    "slug": "ceiling-fan-services-kl",
    "title": "Residential Ceiling Fan Installation & Replacement in KL",
    "category": "Residential",
    "intro": "Bedroom and living-room fans done safely: rated brackets and downrods for your slab or joists, wobble-free balancing, li",
    "relatedServiceSlug": "ceiling-fan"
  },
  {
    "slug": "lighting-services-kl",
    "title": "Residential Lighting Design & Installation in KL",
    "category": "Residential",
    "intro": "Downlights, pendants and cove strips for homes: cleanly cut ceilings, serviceable driver placement and matched colour te",
    "relatedServiceSlug": "lighting"
  },
  {
    "slug": "tiling-services-kl",
    "title": "Residential Professional Tiling & Tile Repair in KL",
    "category": "Residential",
    "intro": "Floor and wall tiling for renovations and repairs: homogeneous, porcelain, ceramic, mosaic and large-format slabs — set ",
    "relatedServiceSlug": "tiling"
  },
  {
    "slug": "plaster-ceiling-services-kl",
    "title": "Residential Plaster Ceiling Design & Build in KL",
    "category": "Residential",
    "intro": "Modern plaster ceilings for landed and high-rise homes: hidden cove light channels, stepped profiles, L-boxes and pelmet",
    "relatedServiceSlug": "plaster-ceiling"
  },
  {
    "slug": "skim-coat-services-kl",
    "title": "Residential Wall & Ceiling Skim Coat in KL",
    "category": "Residential",
    "intro": "Glass-smooth skim before the paint: full-surface prep, crack treatment and trowel-flat walls under raking light — the fi",
    "relatedServiceSlug": "skim-coat"
  },
  {
    "slug": "flooring-services-kl",
    "title": "Residential Vinyl, SPC & Laminate Flooring in KL",
    "category": "Residential",
    "intro": "Click-lock SPC, laminate and vinyl for homes: level subfloors, moisture barriers where they belong, quiet underfoot — us",
    "relatedServiceSlug": "flooring"
  },
  {
    "slug": "epoxy-flooring-services-kl",
    "title": "Residential Epoxy & Polyurethane Flooring in KL",
    "category": "Residential",
    "intro": "Garage and utility floors in epoxy: ground-prepped, self-levelled and sealed with wipe-clean, anti-slip options and cove",
    "relatedServiceSlug": "epoxy-flooring"
  },
  {
    "slug": "roof-repair-services-kl",
    "title": "Residential Roof Repair & Waterproofing in KL",
    "category": "Residential",
    "intro": "Terrace and bungalow roof leaks fixed at the source: sheet and tile replacement, ridge and flashing seals, valley cleara",
    "relatedServiceSlug": "roof-repair"
  },
  {
    "slug": "kitchen-cabinet-services-kl",
    "title": "Residential Kitchen Cabinet & Countertop in KL",
    "category": "Residential",
    "intro": "Kitchen cabinets built for real Malaysian cooking: anti-termite boards, soft-close fittings, wipe-clean laminates or PU ",
    "relatedServiceSlug": "kitchen-cabinet"
  },
  {
    "slug": "carpentry-services-kl",
    "title": "Residential Custom Carpentry & Joinery in KL",
    "category": "Residential",
    "intro": "Joinery and carpentry at home: fitted wardrobes, feature walls, doors and trims patched to match — existing pieces reviv",
    "relatedServiceSlug": "carpentry"
  },
  {
    "slug": "door-services-kl",
    "title": "Residential Door Repair & Installation in KL",
    "category": "Residential",
    "intro": "Doors that bind, sag, rattle or won't lock: planed, rehinged, latched and sealed — front doors, bathroom doors and gates",
    "relatedServiceSlug": "door"
  },
  {
    "slug": "window-repair-services-kl",
    "title": "Residential Window Repair & Glass Replacement in KL",
    "category": "Residential",
    "intro": "Casement, sliding and top-hung windows made smooth again: glass replacement, roller and track service, new seals, handle",
    "relatedServiceSlug": "window-repair"
  },
  {
    "slug": "locksmith-services-kl",
    "title": "Residential Locksmith & Smart Lock Services in KL",
    "category": "Residential",
    "intro": "Home locks, hinges and entry security: cylinder upgrades when keys outlive their owners, strike reinforcement, smart-loc",
    "relatedServiceSlug": "locksmith"
  },
  {
    "slug": "glass-aluminium-services-kl",
    "title": "Residential Glass & Aluminium Fabrication in KL",
    "category": "Residential",
    "intro": "Glass and aluminium at home: mirror walls for gyms and studies, splashbacks, wardrobe glass, partitions and shower enclo",
    "relatedServiceSlug": "glass-aluminium"
  },
  {
    "slug": "cctv-services-kl",
    "title": "Residential CCTV & Security Camera Installation in KL",
    "category": "Residential",
    "intro": "Home CCTV the honest way: coverage from porch to drive, discreet cabling, recorder placement agreed with you and phone v",
    "relatedServiceSlug": "cctv"
  },
  {
    "slug": "autogate-services-kl",
    "title": "Residential Auto Gate & Motorised Gate in KL",
    "category": "Residential",
    "intro": "Auto-gates for homes and cluster schemes: motor repair or replacement, rollers and tracks, safety beams, remotes and key",
    "relatedServiceSlug": "autogate"
  },
  {
    "slug": "welding-services-kl",
    "title": "Residential Welding & Metal Fabrication in KL",
    "category": "Residential",
    "intro": "Welding around the house: gates and grilles repaired, extenders and canopies built, stainless handrails and yard repairs",
    "relatedServiceSlug": "welding"
  },
  {
    "slug": "aircon-services-kl",
    "title": "Residential Aircon Service, Repair & Installation in KL",
    "category": "Residential",
    "intro": "Home aircon that actually cools: installs, chemical washes, gas top-ups and repairs — with drain tests, clean-sheet habi",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "kitchen-renovation-services-kl",
    "title": "Residential Kitchen Renovation in KL",
    "category": "Residential",
    "intro": "Kitchen refurbs in a workable sequence: cabinets, tiles, water and extraction changed over in order — kitchen out of act",
    "relatedServiceSlug": "kitchen-renovation"
  },
  {
    "slug": "bathroom-renovation-services-kl",
    "title": "Residential Bathroom Renovation in KL",
    "category": "Residential",
    "intro": "Bathroom renovation without the dread: leak-safe waterproofing, new tiles, fresh fixtures — planned so the house keeps o",
    "relatedServiceSlug": "bathroom-renovation"
  },
  {
    "slug": "awning-installation-services-kl",
    "title": "Residential Awning Installation Services in KL",
    "category": "Residential",
    "intro": "Awnings and roofing for car porches, patios and yards: polycarbonate, metal deck or ACP chosen against your actual sun a",
    "relatedServiceSlug": "awning-installation"
  },
  {
    "slug": "nippon-paint-application-malaysia",
    "title": "Nippon Paint Application Malaysia",
    "category": "Brand Guide",
    "intro": "Nippon Paint Application Malaysia explains when this brand or material category is suitable, how it should be applied, a",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "dulux-paint-application-malaysia",
    "title": "Dulux Paint Application Malaysia",
    "category": "Brand Guide",
    "intro": "Dulux Paint Application Malaysia explains when this brand or material category is suitable, how it should be applied, an",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "jotun-paint-application-malaysia",
    "title": "Jotun Paint Application Malaysia",
    "category": "Brand Guide",
    "intro": "Jotun Paint Application Malaysia explains when this brand or material category is suitable, how it should be applied, an",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "sirim-certified-pipes-malaysia",
    "title": "SIRIM-Certified Pipes Malaysia",
    "category": "Brand Guide",
    "intro": "SIRIM-Certified Pipes Malaysia explains when this brand or material category is suitable, how it should be applied, and ",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "grundfos-water-pump-installation",
    "title": "Grundfos Water Pump Installation",
    "category": "Brand Guide",
    "intro": "Grundfos Water Pump Installation explains when this brand or material category is suitable, how it should be applied, an",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "joven-water-heater-installation",
    "title": "Joven Water Heater Installation",
    "category": "Brand Guide",
    "intro": "Joven Water Heater Installation explains when this brand or material category is suitable, how it should be applied, and",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "rinnai-water-heater-installation",
    "title": "Rinnai Water Heater Installation",
    "category": "Brand Guide",
    "intro": "Rinnai Water Heater Installation explains when this brand or material category is suitable, how it should be applied, an",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "knauf-gypsum-board-installation",
    "title": "Knauf Gypsum Board Installation",
    "category": "Brand Guide",
    "intro": "Knauf Gypsum Board Installation explains when this brand or material category is suitable, how it should be applied, and",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "boral-gypsum-board-installation",
    "title": "Boral Gypsum Board Installation",
    "category": "Brand Guide",
    "intro": "Boral Gypsum Board Installation explains when this brand or material category is suitable, how it should be applied, and",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "sika-waterproofing-application",
    "title": "Sika Waterproofing Application",
    "category": "Brand Guide",
    "intro": "Sika Waterproofing Application explains when this brand or material category is suitable, how it should be applied, and ",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "bostik-waterproofing-application",
    "title": "Bostik Waterproofing Application",
    "category": "Brand Guide",
    "intro": "Bostik Waterproofing Application explains when this brand or material category is suitable, how it should be applied, an",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "mapei-waterproofing-application",
    "title": "Mapei Waterproofing Application",
    "category": "Brand Guide",
    "intro": "Mapei Waterproofing Application explains when this brand or material category is suitable, how it should be applied, and",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "daikin-aircon-service-malaysia",
    "title": "Daikin Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Daikin Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installa",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "panasonic-aircon-service-malaysia",
    "title": "Panasonic Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Panasonic Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and insta",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "mitsubishi-electric-aircon-service-malaysia",
    "title": "Mitsubishi Electric Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Mitsubishi Electric Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "york-aircon-service-malaysia",
    "title": "York Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "York Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installati",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "acson-aircon-service-malaysia",
    "title": "Acson Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Acson Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installat",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "carrier-aircon-service-malaysia",
    "title": "Carrier Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Carrier Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "midea-aircon-service-malaysia",
    "title": "Midea Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Midea Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installat",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "haier-aircon-service-malaysia",
    "title": "Haier Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Haier Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installat",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "toshiba-aircon-service-malaysia",
    "title": "Toshiba Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Toshiba Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "hitachi-aircon-service-malaysia",
    "title": "Hitachi Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Hitachi Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "samsung-aircon-service-malaysia",
    "title": "Samsung Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Samsung Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "lg-aircon-service-malaysia",
    "title": "LG Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "LG Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installation",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "sharp-aircon-service-malaysia",
    "title": "Sharp Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Sharp Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installat",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "fujitsu-aircon-service-malaysia",
    "title": "Fujitsu Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Fujitsu Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "gree-aircon-service-malaysia",
    "title": "Gree Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Gree Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installati",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "national-aircon-service-malaysia",
    "title": "National Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "National Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and instal",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "hisense-aircon-service-malaysia",
    "title": "Hisense Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Hisense Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and install",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "aux-aircon-service-malaysia",
    "title": "Aux Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Aux Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installatio",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "tcl-aircon-service-malaysia",
    "title": "TCL Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "TCL Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installatio",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "isonic-aircon-service-malaysia",
    "title": "Isonic Aircon Service Malaysia",
    "category": "Brand Guide",
    "intro": "Isonic Aircon Service Malaysia covers basic servicing, chemical wash, chemical overhaul, gas top-up, repair and installa",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "best-house-painters-kl-2026",
    "title": "How to Compare House Painters in KL (2026)",
    "category": "Top Considerations",
    "intro": "How to Compare House Painters in KL (2026) explains practical criteria for comparing providers, methods, materials, work"
  },
  {
    "slug": "best-plumbers-kl",
    "title": "How to Compare Plumbers in KL",
    "category": "Top Considerations",
    "intro": "How to Compare Plumbers in KL explains practical criteria for comparing providers, methods, materials, workmanship terms"
  },
  {
    "slug": "best-ceiling-contractors-kl",
    "title": "How to Compare Ceiling Contractors in KL",
    "category": "Top Considerations",
    "intro": "How to Compare Ceiling Contractors in KL explains practical criteria for comparing providers, methods, materials, workma"
  },
  {
    "slug": "best-waterproofing-contractors-kl",
    "title": "How to Compare Waterproofing Contractors in KL",
    "category": "Top Considerations",
    "intro": "How to Compare Waterproofing Contractors in KL explains practical criteria for comparing providers, methods, materials, "
  },
  {
    "slug": "best-handyman-kl",
    "title": "How to Compare Handyman Services in KL",
    "category": "Top Considerations",
    "intro": "How to Compare Handyman Services in KL explains practical criteria for comparing providers, methods, materials, workmans"
  },
  {
    "slug": "best-paint-brands-malaysia-2026",
    "title": "Paint Brands in Malaysia: 2026 Guide",
    "category": "Top Considerations",
    "intro": "Paint Brands in Malaysia: 2026 Guide explains practical criteria for comparing providers, methods, materials, workmanshi"
  },
  {
    "slug": "best-waterproofing-methods-malaysia",
    "title": "Waterproofing Methods in Malaysia",
    "category": "Top Considerations",
    "intro": "Waterproofing Methods in Malaysia explains practical criteria for comparing providers, methods, materials, workmanship t"
  },
  {
    "slug": "bathroom-waterproofing-options",
    "title": "Bathroom Waterproofing Options",
    "category": "Top Considerations",
    "intro": "Bathroom Waterproofing Options explains practical criteria for comparing providers, methods, materials, workmanship term"
  },
  {
    "slug": "ceiling-materials-malaysia",
    "title": "Ceiling Materials in Malaysia",
    "category": "Top Considerations",
    "intro": "Ceiling Materials in Malaysia explains practical criteria for comparing providers, methods, materials, workmanship terms"
  },
  {
    "slug": "handyman-services-every-homeowner-needs",
    "title": "Useful Handyman Services for Homeowners",
    "category": "Top Considerations",
    "intro": "Useful Handyman Services for Homeowners explains practical criteria for comparing providers, methods, materials, workman"
  },
  {
    "slug": "painting-ultimate-guide",
    "title": "House Painting Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "House Painting Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured and ",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "plumbing-ultimate-guide",
    "title": "Plumbing & Leak Repair Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Plumbing & Leak Repair Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insu",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "ceiling-ultimate-guide",
    "title": "Ceiling & Partition Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Ceiling & Partition Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "waterproofing-ultimate-guide",
    "title": "Waterproofing & Leak Repair Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Waterproofing & Leak Repair Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "handyman-ultimate-guide",
    "title": "Handyman Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Handyman Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured and backgr",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "house-renovation-ultimate-guide",
    "title": "Complete House Renovation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Complete House Renovation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured an",
    "relatedServiceSlug": "house-renovation"
  },
  {
    "slug": "electrical-ultimate-guide",
    "title": "Licensed Electrical Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Licensed Electrical Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured",
    "relatedServiceSlug": "electrical"
  },
  {
    "slug": "water-heater-ultimate-guide",
    "title": "Water Heater Installation & Repair Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Water Heater Installation & Repair in KL and Selangor should be priced fairly and openly, scoped clearly, performed by i",
    "relatedServiceSlug": "water-heater"
  },
  {
    "slug": "ceiling-fan-ultimate-guide",
    "title": "Ceiling Fan Installation & Replacement Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Ceiling Fan Installation & Replacement in KL and Selangor should be priced fairly and openly, scoped clearly, performed ",
    "relatedServiceSlug": "ceiling-fan"
  },
  {
    "slug": "lighting-ultimate-guide",
    "title": "Lighting Design & Installation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Lighting Design & Installation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insur",
    "relatedServiceSlug": "lighting"
  },
  {
    "slug": "tiling-ultimate-guide",
    "title": "Professional Tiling & Tile Repair Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Professional Tiling & Tile Repair in KL and Selangor should be priced fairly and openly, scoped clearly, performed by in",
    "relatedServiceSlug": "tiling"
  },
  {
    "slug": "plaster-ceiling-ultimate-guide",
    "title": "Plaster Ceiling Design & Build Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Plaster Ceiling Design & Build in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insur",
    "relatedServiceSlug": "plaster-ceiling"
  },
  {
    "slug": "skim-coat-ultimate-guide",
    "title": "Wall & Ceiling Skim Coat Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Wall & Ceiling Skim Coat in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured and",
    "relatedServiceSlug": "skim-coat"
  },
  {
    "slug": "flooring-ultimate-guide",
    "title": "Vinyl, SPC & Laminate Flooring Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Vinyl, SPC & Laminate Flooring in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insur",
    "relatedServiceSlug": "flooring"
  },
  {
    "slug": "epoxy-flooring-ultimate-guide",
    "title": "Epoxy & Polyurethane Flooring Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Epoxy & Polyurethane Flooring in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insure",
    "relatedServiceSlug": "epoxy-flooring"
  },
  {
    "slug": "roof-repair-ultimate-guide",
    "title": "Roof Repair & Waterproofing Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Roof Repair & Waterproofing in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured ",
    "relatedServiceSlug": "roof-repair"
  },
  {
    "slug": "kitchen-cabinet-ultimate-guide",
    "title": "Kitchen Cabinet & Countertop Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Kitchen Cabinet & Countertop in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured",
    "relatedServiceSlug": "kitchen-cabinet"
  },
  {
    "slug": "carpentry-ultimate-guide",
    "title": "Custom Carpentry & Joinery Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Custom Carpentry & Joinery in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured a",
    "relatedServiceSlug": "carpentry"
  },
  {
    "slug": "door-ultimate-guide",
    "title": "Door Repair & Installation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Door Repair & Installation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured a",
    "relatedServiceSlug": "door"
  },
  {
    "slug": "window-repair-ultimate-guide",
    "title": "Window Repair & Glass Replacement Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Window Repair & Glass Replacement in KL and Selangor should be priced fairly and openly, scoped clearly, performed by in",
    "relatedServiceSlug": "window-repair"
  },
  {
    "slug": "locksmith-ultimate-guide",
    "title": "Locksmith & Smart Lock Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Locksmith & Smart Lock Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insu",
    "relatedServiceSlug": "locksmith"
  },
  {
    "slug": "glass-aluminium-ultimate-guide",
    "title": "Glass & Aluminium Fabrication Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Glass & Aluminium Fabrication in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insure",
    "relatedServiceSlug": "glass-aluminium"
  },
  {
    "slug": "cctv-ultimate-guide",
    "title": "CCTV & Security Camera Installation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "CCTV & Security Camera Installation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by ",
    "relatedServiceSlug": "cctv"
  },
  {
    "slug": "autogate-ultimate-guide",
    "title": "Auto Gate & Motorised Gate Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Auto Gate & Motorised Gate in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured a",
    "relatedServiceSlug": "autogate"
  },
  {
    "slug": "welding-ultimate-guide",
    "title": "Welding & Metal Fabrication Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Welding & Metal Fabrication in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured ",
    "relatedServiceSlug": "welding"
  },
  {
    "slug": "aircon-ultimate-guide",
    "title": "Aircon Service, Repair & Installation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Aircon Service, Repair & Installation in KL and Selangor should be priced fairly and openly, scoped clearly, performed b",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "kitchen-renovation-ultimate-guide",
    "title": "Kitchen Renovation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Kitchen Renovation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured and backg",
    "relatedServiceSlug": "kitchen-renovation"
  },
  {
    "slug": "bathroom-renovation-ultimate-guide",
    "title": "Bathroom Renovation Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Bathroom Renovation in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured and back",
    "relatedServiceSlug": "bathroom-renovation"
  },
  {
    "slug": "awning-installation-ultimate-guide",
    "title": "Awning Installation Services Ultimate Guide for KL & Selangor",
    "category": "AI Answer Guide",
    "intro": "Awning Installation Services in KL and Selangor should be priced fairly and openly, scoped clearly, performed by insured",
    "relatedServiceSlug": "awning-installation"
  },
  {
    "slug": "painting-process-kl",
    "title": "House Painting Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for house painting services, including preparation, execution, quality checks, and warranty ",
    "relatedServiceSlug": "painting"
  },
  {
    "slug": "plumbing-process-kl",
    "title": "Plumbing & Leak Repair Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for plumbing & leak repair services, including preparation, execution, quality checks, and w",
    "relatedServiceSlug": "plumbing"
  },
  {
    "slug": "ceiling-process-kl",
    "title": "Ceiling & Partition Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for ceiling & partition services, including preparation, execution, quality checks, and warr",
    "relatedServiceSlug": "ceiling"
  },
  {
    "slug": "pu-grouting-process-kl",
    "title": "Waterproofing & Leak Repair Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for waterproofing & leak repair services, including preparation, execution, quality checks, ",
    "relatedServiceSlug": "waterproofing"
  },
  {
    "slug": "handyman-process-kl",
    "title": "Handyman Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for handyman services, including preparation, execution, quality checks, and warranty handov",
    "relatedServiceSlug": "handyman"
  },
  {
    "slug": "house-renovation-process-kl",
    "title": "Complete House Renovation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for complete house renovation, including preparation, execution, quality checks, and warrant",
    "relatedServiceSlug": "house-renovation"
  },
  {
    "slug": "electrical-process-kl",
    "title": "Licensed Electrical Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for licensed electrical services, including preparation, execution, quality checks, and warr",
    "relatedServiceSlug": "electrical"
  },
  {
    "slug": "water-heater-process-kl",
    "title": "Water Heater Installation & Repair Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for water heater installation & repair, including preparation, execution, quality checks, an",
    "relatedServiceSlug": "water-heater"
  },
  {
    "slug": "ceiling-fan-process-kl",
    "title": "Ceiling Fan Installation & Replacement Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for ceiling fan installation & replacement, including preparation, execution, quality checks",
    "relatedServiceSlug": "ceiling-fan"
  },
  {
    "slug": "lighting-process-kl",
    "title": "Lighting Design & Installation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for lighting design & installation, including preparation, execution, quality checks, and wa",
    "relatedServiceSlug": "lighting"
  },
  {
    "slug": "tiling-process-kl",
    "title": "Professional Tiling & Tile Repair Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for professional tiling & tile repair, including preparation, execution, quality checks, and",
    "relatedServiceSlug": "tiling"
  },
  {
    "slug": "plaster-ceiling-process-kl",
    "title": "Plaster Ceiling Design & Build Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for plaster ceiling design & build, including preparation, execution, quality checks, and wa",
    "relatedServiceSlug": "plaster-ceiling"
  },
  {
    "slug": "skim-coat-process-kl",
    "title": "Wall & Ceiling Skim Coat Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for wall & ceiling skim coat, including preparation, execution, quality checks, and warranty",
    "relatedServiceSlug": "skim-coat"
  },
  {
    "slug": "flooring-process-kl",
    "title": "Vinyl, SPC & Laminate Flooring Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for vinyl, spc & laminate flooring, including preparation, execution, quality checks, and wa",
    "relatedServiceSlug": "flooring"
  },
  {
    "slug": "epoxy-flooring-process-kl",
    "title": "Epoxy & Polyurethane Flooring Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for epoxy & polyurethane flooring, including preparation, execution, quality checks, and war",
    "relatedServiceSlug": "epoxy-flooring"
  },
  {
    "slug": "roof-repair-process-kl",
    "title": "Roof Repair & Waterproofing Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for roof repair & waterproofing, including preparation, execution, quality checks, and warra",
    "relatedServiceSlug": "roof-repair"
  },
  {
    "slug": "kitchen-cabinet-process-kl",
    "title": "Kitchen Cabinet & Countertop Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for kitchen cabinet & countertop, including preparation, execution, quality checks, and warr",
    "relatedServiceSlug": "kitchen-cabinet"
  },
  {
    "slug": "carpentry-process-kl",
    "title": "Custom Carpentry & Joinery Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for custom carpentry & joinery, including preparation, execution, quality checks, and warran",
    "relatedServiceSlug": "carpentry"
  },
  {
    "slug": "door-process-kl",
    "title": "Door Repair & Installation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for door repair & installation, including preparation, execution, quality checks, and warran",
    "relatedServiceSlug": "door"
  },
  {
    "slug": "window-repair-process-kl",
    "title": "Window Repair & Glass Replacement Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for window repair & glass replacement, including preparation, execution, quality checks, and",
    "relatedServiceSlug": "window-repair"
  },
  {
    "slug": "locksmith-process-kl",
    "title": "Locksmith & Smart Lock Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for locksmith & smart lock services, including preparation, execution, quality checks, and w",
    "relatedServiceSlug": "locksmith"
  },
  {
    "slug": "glass-aluminium-process-kl",
    "title": "Glass & Aluminium Fabrication Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for glass & aluminium fabrication, including preparation, execution, quality checks, and war",
    "relatedServiceSlug": "glass-aluminium"
  },
  {
    "slug": "cctv-process-kl",
    "title": "CCTV & Security Camera Installation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for cctv & security camera installation, including preparation, execution, quality checks, a",
    "relatedServiceSlug": "cctv"
  },
  {
    "slug": "autogate-process-kl",
    "title": "Auto Gate & Motorised Gate Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for auto gate & motorised gate, including preparation, execution, quality checks, and warran",
    "relatedServiceSlug": "autogate"
  },
  {
    "slug": "welding-process-kl",
    "title": "Welding & Metal Fabrication Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for welding & metal fabrication, including preparation, execution, quality checks, and warra",
    "relatedServiceSlug": "welding"
  },
  {
    "slug": "aircon-process-kl",
    "title": "Aircon Service, Repair & Installation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for aircon service, repair & installation, including preparation, execution, quality checks,",
    "relatedServiceSlug": "aircon"
  },
  {
    "slug": "kitchen-renovation-process-kl",
    "title": "Kitchen Renovation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for kitchen renovation, including preparation, execution, quality checks, and warranty hando",
    "relatedServiceSlug": "kitchen-renovation"
  },
  {
    "slug": "bathroom-renovation-process-kl",
    "title": "Bathroom Renovation Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for bathroom renovation, including preparation, execution, quality checks, and warranty hand",
    "relatedServiceSlug": "bathroom-renovation"
  },
  {
    "slug": "awning-installation-process-kl",
    "title": "Awning Installation Services Process in KL",
    "category": "Process",
    "intro": "A step-by-step process page for awning installation services, including preparation, execution, quality checks, and warr",
    "relatedServiceSlug": "awning-installation"
  }
];

export type ContentRelatedServiceLink = {
  slug: string;
  title: string;
  tagline: string;
  subServices: { name: string; desc: string }[];
};

export const contentRelatedServiceBySlug: Record<string, ContentRelatedServiceLink> = {
  "painting": {
    "slug": "painting",
    "title": "House Painting Services",
    "tagline": "Interior, exterior and wall repainting for homes, offices and shops across KL & Selangor, with surface preparation, floor and furniture protection, and clean handover. From RM 450.",
    "subServices": [
      {
        "name": "Interior House Painting",
        "desc": "Premium interior wall painting with low-odor, low-VOC washable paint."
      },
      {
        "name": "Exterior House Painting",
        "desc": "Weatherproof, anti-fungal, and UV-resistant exterior coatings for ultimate protection."
      }
    ]
  },
  "plumbing": {
    "slug": "plumbing",
    "title": "Plumbing & Leak Repair Services",
    "tagline": "Plumbing and leak repair for pipes, taps, toilets, drains, water heaters and pumps across KL & Selangor, with the scope confirmed before work. From RM 280.",
    "subServices": [
      {
        "name": "Water Leakage Diagnosis & Repair",
        "desc": "Detection of hidden pipe leaks behind walls or underground, followed by precise repair."
      },
      {
        "name": "Toilet, Tap & Sink Installation",
        "desc": "Fitting new toilet bowls, modern kitchen faucets, basins, and heavy-duty sink plumbing."
      }
    ]
  },
  "ceiling": {
    "slug": "ceiling",
    "title": "Ceiling & Partition Services",
    "tagline": "Plaster ceiling installation and repair, gypsum partitions, cornices, L-box features and skim finishing for homes and commercial spaces across KL & Selangor. From RM 220.",
    "subServices": [
      {
        "name": "Water-Damaged Ceiling Repair",
        "desc": "Removing moldy, rotting plasterboard, addressing the leak source, and fitting a clean moisture-resistant panel."
      },
      {
        "name": "Plaster Ceiling Installation",
        "desc": "Elegant flat, tiered, or L-box plaster ceiling setups with custom cutout channels for downlights."
      }
    ]
  },
  "waterproofing": {
    "slug": "waterproofing",
    "title": "Waterproofing & Leak Repair Services",
    "tagline": "Bathroom, roof, balcony and concrete waterproofing plus PU injection grouting for leaks across KL & Selangor, selected after assessing the cause. From RM 300.",
    "subServices": [
      {
        "name": "PU High-Pressure Injection Grouting",
        "desc": "Smart non-destructive polyurethane injection to seal inter-floor concrete slab leaks."
      },
      {
        "name": "Bathroom & Wet Area Waterproofing",
        "desc": "Chemical waterproofing membrane application for showers, toilets, and wet commercial washrooms."
      }
    ]
  },
  "handyman": {
    "slug": "handyman",
    "title": "Handyman Services",
    "tagline": "TV mounting, door and lock repair, furniture assembly, curtain and shelf installation, cabinet adjustments and general maintenance across KL & Selangor. From RM 280.",
    "subServices": [
      {
        "name": "Heavy TV Wall Mounting",
        "desc": "Safe, level wall-mounting of TVs up to 85\" on brick, concrete, or gypsum partition walls with hidden wire options."
      },
      {
        "name": "Door, Hinge & Lockset Repair",
        "desc": "Fixing sagging doors, replacing rusty hinges, and installing premium lever locks or smart digital locks."
      }
    ]
  },
  "house-renovation": {
    "slug": "house-renovation",
    "title": "Complete House Renovation",
    "tagline": "End-to-end residential and commercial renovation: design, demolition, structural work, electrical, plumbing, painting, and handover. From RM 22,000.",
    "subServices": [
      {
        "name": "Full House Renovation Package",
        "desc": "Hacking, structural, ceiling, tiling, electrical, plumbing, painting, and final cleaning."
      },
      {
        "name": "Partial House Renovation",
        "desc": "Targeted renovation for specific areas — kitchen, bathroom, living or bedrooms — with isolated work zones."
      }
    ]
  },
  "electrical": {
    "slug": "electrical",
    "title": "Licensed Electrical Services",
    "tagline": "Wiring, DB box upgrades, power point and switch installation, ceiling fan and lighting point setup by ST-licensed electricians. From RM 280.",
    "subServices": [
      {
        "name": "New Power Point & Switch Installation",
        "desc": "Adding new 13A sockets, USB outlets, double-pole switches, and dimmer controls on existing or new circuits."
      },
      {
        "name": "DB Box Upgrade & Rewiring",
        "desc": "Replacing old fuse boxes with modern MCB+RCCB distribution boards and full or partial house rewiring."
      }
    ]
  },
  "water-heater": {
    "slug": "water-heater",
    "title": "Water Heater Installation & Repair",
    "tagline": "Instant, storage, and heat-pump water heater supply, installation, repair, and descaling by ST-licensed technicians. From RM 180.",
    "subServices": [
      {
        "name": "Instant Water Heater Installation",
        "desc": "Single-point instant shower heater supply and install with proper isolator, water-proof cover, and pressure test."
      },
      {
        "name": "Storage Tank Heater Installation",
        "desc": "Multi-point 15L–50L storage heater installation including wall mounting, pressure relief valve, and pipework."
      }
    ]
  },
  "ceiling-fan": {
    "slug": "ceiling-fan",
    "title": "Ceiling Fan Installation & Replacement",
    "tagline": "Safe ceiling fan mounting on concrete, plaster ceiling, and condo false ceiling with proper fan hook, regulator, and concealed wiring. From RM 150.",
    "subServices": [
      {
        "name": "New Ceiling Fan Installation",
        "desc": "Mounting your supplied fan on a solid fan hook with regulator, wiring, and swing-test included."
      },
      {
        "name": "Ceiling Fan Replacement",
        "desc": "Removing the old fan, safe disposal, and installing your new fan on the existing hook with fresh wiring."
      }
    ]
  },
  "lighting": {
    "slug": "lighting",
    "title": "Lighting Design & Installation",
    "tagline": "Downlight, track light, pendant, cove, and outdoor lighting design, supply, and installation by ST-licensed electricians. From RM 120 / point.",
    "subServices": [
      {
        "name": "LED Downlight Installation",
        "desc": "Cutting and wiring new downlight points with COB LED fixtures, drivers, and proper heat dissipation."
      },
      {
        "name": "Pendant & Chandelier Install",
        "desc": "Mounting heavy pendants and chandeliers on reinforced ceiling hooks with safety cables."
      }
    ]
  },
  "tiling": {
    "slug": "tiling",
    "title": "Professional Tiling & Tile Repair",
    "tagline": "Floor and wall tiling for new builds, renovations, and repairs. Homogeneous, porcelain, ceramic, mosaic, and large-format slabs. From RM 14 / sq ft.",
    "subServices": [
      {
        "name": "Floor Tiling Installation",
        "desc": "Standard 300x300mm to 600x600mm floor tile installation with cement-sand screed and tile adhesive."
      },
      {
        "name": "Wall Tiling Installation",
        "desc": "Kitchen splashback, bathroom wall, and feature wall tiling with straight or brick-bond patterns."
      }
    ]
  },
  "plaster-ceiling": {
    "slug": "plaster-ceiling",
    "title": "Plaster Ceiling Design & Build",
    "tagline": "Modern plaster ceiling with concealed LED trough, tiered design, L-box, and cove lighting for landed and high-rise properties. From RM 10 / sq ft.",
    "subServices": [
      {
        "name": "Flat Plaster Ceiling",
        "desc": "Clean, single-level flat ceiling with skim coat finish — ideal for minimalist modern interiors."
      },
      {
        "name": "False Ceiling Installation",
        "desc": "General false ceiling for homes and offices with GI frame and moisture-resistant boards."
      }
    ]
  },
  "skim-coat": {
    "slug": "skim-coat",
    "title": "Wall & Ceiling Skim Coat",
    "tagline": "Glass-smooth skim coating for walls and ceilings, paint-ready finish, full surface preparation and crack repair. From RM 5 / sq ft.",
    "subServices": [
      {
        "name": "Wall Skim Coating",
        "desc": "Two-coat skim coating on plastered or previously painted walls for a glass-smooth paint-ready finish."
      },
      {
        "name": "Ceiling Skim Coating",
        "desc": "Re-skim of existing plaster ceilings to refresh aged surfaces before repainting."
      }
    ]
  },
  "flooring": {
    "slug": "flooring",
    "title": "Vinyl, SPC & Laminate Flooring",
    "tagline": "Modern click-lock flooring for homes and offices. Waterproof SPC, scratch-resistant laminate, and luxury vinyl planks. From RM 14 / sq ft.",
    "subServices": [
      {
        "name": "SPC Click-Lock Flooring Install",
        "desc": "Waterproof stone polymer composite planks with built-in underlay, ideal for whole-home installation."
      },
      {
        "name": "Laminate Flooring Install",
        "desc": "Budget-friendly HDF laminate with wood-look finish, AC4–AC5 wear rating for residential traffic."
      }
    ]
  },
  "epoxy-flooring": {
    "slug": "epoxy-flooring",
    "title": "Epoxy & Polyurethane Flooring",
    "tagline": "Heavy-duty epoxy floor coating for garages, warehouses, factories, showrooms, and commercial kitchens. From RM 22 / sq ft.",
    "subServices": [
      {
        "name": "Self-Levelling Epoxy Floor",
        "desc": "Mirror-smooth 2–3mm self-levelling epoxy for residential, showroom, and light commercial floors."
      },
      {
        "name": "Flake / Quartz Broadcast Epoxy",
        "desc": "Decorative vinyl flake or coloured quartz broadcast with slip-resistant finish for garages and kitchens."
      }
    ]
  },
  "roof-repair": {
    "slug": "roof-repair",
    "title": "Roof Repair & Waterproofing",
    "tagline": "Roof tile replacement, leak repair, gutter cleaning, flashing, and full torch-on waterproofing for landed properties. From RM 380.",
    "subServices": [
      {
        "name": "Roof Leak Diagnosis & Repair",
        "desc": "Thermal imaging to locate the leak source, followed by tile, flashing, or membrane repair on the affected area."
      },
      {
        "name": "Ridge Re-Bedding & Re-Pointing",
        "desc": "Removing loose ridge mortar and re-bedding with flexible polymer mortar for a permanent seal."
      }
    ]
  },
  "kitchen-cabinet": {
    "slug": "kitchen-cabinet",
    "title": "Kitchen Cabinet & Countertop",
    "tagline": "Custom-built and modular kitchen cabinets with stone, solid surface, or laminate countertops. Design, supply, install. From RM 7,500.",
    "subServices": [
      {
        "name": "Modular Kitchen Cabinet (10ft L-shape)",
        "desc": "Häfele or Blum hardware with 18mm melamine carcass, doors in laminate, acrylic, or spray-painted finish."
      },
      {
        "name": "Custom Plywood Kitchen",
        "desc": "Built-to-fit plywood cabinet with soft-close hardware, custom doors, and full-height pantry units."
      }
    ]
  },
  "carpentry": {
    "slug": "carpentry",
    "title": "Custom Carpentry & Joinery",
    "tagline": "Built-in wardrobes, TV consoles, study desks, feature walls, shoe racks, and custom furniture. From RM 300 / linier ft.",
    "subServices": [
      {
        "name": "Built-in Wardrobe",
        "desc": "Floor-to-ceiling wardrobe with internal drawers, shelves, hanging rails, and mirror or laminate doors."
      },
      {
        "name": "TV Console & Feature Wall",
        "desc": "Custom TV console with storage drawers, floating shelves, cable management, and matching feature wall panelling."
      }
    ]
  },
  "door": {
    "slug": "door",
    "title": "Door Repair & Installation",
    "tagline": "Solid timber, engineered, fire-rated, and laminate doors — supply, install, plane, hinge, and lock fitting. From RM 250.",
    "subServices": [
      {
        "name": "Solid Timber Door Installation",
        "desc": "Solid meranti or chengal door with meranti frame, 3 SS304 hinges, architrave, and basic mortice lockset."
      },
      {
        "name": "Laminate Door Installation",
        "desc": "HDF-skin engineered door with smooth laminate finish, ideal for budget-friendly modern interiors."
      }
    ]
  },
  "window-repair": {
    "slug": "window-repair",
    "title": "Window Repair & Glass Replacement",
    "tagline": "Casement, sliding, top-hung, awning windows — glass replacement, seal repair, handle replacement, and alignment. From RM 200.",
    "subServices": [
      {
        "name": "Glass Replacement",
        "desc": "Removing broken or cracked glass and installing new clear, tinted, frosted, or tempered glass to the same size and thickness."
      },
      {
        "name": "Window Seal Replacement",
        "desc": "Replacing worn or hardened EPDM rubber seals to stop water ingress and improve insulation."
      }
    ]
  },
  "locksmith": {
    "slug": "locksmith",
    "title": "Locksmith & Smart Lock Services",
    "tagline": "Digital smart locks, key cutting, lock replacement, door reinforcement, and emergency lockout service. From RM 180.",
    "subServices": [
      {
        "name": "Smart Lock Installation",
        "desc": "Supply and install digital keypad, Bluetooth, Wi-Fi, or biometric fingerprint lock with app pairing and user registration."
      },
      {
        "name": "Mortice / Deadbolt Lock Replacement",
        "desc": "Remove existing mortice or deadbolt lock and install a new Yale, Imperial, or Hafele lock with 3 keys."
      }
    ]
  },
  "glass-aluminium": {
    "slug": "glass-aluminium",
    "title": "Glass & Aluminium Fabrication",
    "tagline": "Shower screens, glass partitions, aluminium windows, sliding doors, and mirror installation across KL & Selangor. From RM 320.",
    "subServices": [
      {
        "name": "Frameless Shower Screen",
        "desc": "10–12mm tempered glass with concealed hinges and anti-leak seals. Custom cut to your bathroom layout."
      },
      {
        "name": "Aluminium Sliding Window",
        "desc": "Locally fabricated aluminium sliding window with 5mm clear or tinted glass, nylon rollers, and weatherstrip."
      }
    ]
  },
  "cctv": {
    "slug": "cctv",
    "title": "CCTV & Security Camera Installation",
    "tagline": "Hikvision, Dahua, Ezviz, TP-Link, Tuya CCTV supply, install, network setup, and remote viewing. From RM 420 / camera.",
    "subServices": [
      {
        "name": "Condo Wi-Fi CCTV Package (4 cameras)",
        "desc": "4x 4MP Wi-Fi cameras with cloud storage, mobile app setup, and remote viewing. Ideal for 1,000-1,500 sqft condos."
      },
      {
        "name": "Landed House PoE CCTV (8 cameras)",
        "desc": "8x 4MP PoE bullet cameras, 8-channel NVR with 2TB HDD, 1-week continuous recording, full cable routing."
      }
    ]
  },
  "autogate": {
    "slug": "autogate",
    "title": "Auto Gate & Motorised Gate",
    "tagline": "Swing, sliding, and folding autogate supply, install, and motor servicing across KL & Selangor. From RM 2,200.",
    "subServices": [
      {
        "name": "Single Swing Autogate",
        "desc": "Single-leaf swing gate motor with 2 remotes, safety sensor, and basic installation. Most popular for terrace houses."
      },
      {
        "name": "Double Swing Autogate",
        "desc": "Two-leaf swing gate with dual motors, synchronisation, 2 remotes, and 2 safety sensors."
      }
    ]
  },
  "welding": {
    "slug": "welding",
    "title": "Welding & Metal Fabrication",
    "tagline": "Custom grilles, gates, structural repair, staircase fabrication, and on-site welding across KL & Selangor. From RM 280.",
    "subServices": [
      {
        "name": "Custom Window Grille",
        "desc": "Powder-coated mild steel window grille in your chosen design (geometric, classic, or modern). Includes anti-rust primer."
      },
      {
        "name": "Main Gate Fabrication",
        "desc": "Custom main gate with mild steel frame, infill design of your choice, and hot-dip galvanised + powder-coat finish."
      }
    ]
  },
  "aircon": {
    "slug": "aircon",
    "title": "Aircon Service, Repair & Installation",
    "tagline": "Air-conditioner basic servicing, chemical wash, chemical overhaul, gas top-up, repair, new installation and dismantling for homes and offices across KL & Selangor. From RM 129.",
    "subServices": [
      {
        "name": "Basic Servicing",
        "desc": "Filter and coil cleaning, drainage check, gas pressure and cooling test for wall-mounted units from RM 129."
      },
      {
        "name": "Chemical Wash",
        "desc": "Pressure chemical wash of coils and blower without full dismantling, from RM 156."
      }
    ]
  },
  "kitchen-renovation": {
    "slug": "kitchen-renovation",
    "title": "Kitchen Renovation",
    "tagline": "Complete kitchen makeover: hacking, tiling, waterproofing, cabinetry, countertop, plumbing, electrical and lighting across KL & Selangor. From RM 8,000.",
    "subServices": [
      {
        "name": "Full Kitchen Renovation",
        "desc": "Complete kitchen rebuild: hacking, waterproofing, tiling, cabinets, countertop, plumbing, electrical and painting."
      },
      {
        "name": "Kitchen Cabinet Installation",
        "desc": "Custom base, wall and tall cabinets with soft-close hinges, drawer systems and pantry pull-outs."
      }
    ]
  },
  "bathroom-renovation": {
    "slug": "bathroom-renovation",
    "title": "Bathroom Renovation",
    "tagline": "Full bathroom and toilet makeover: hacking, waterproofing, tiling, plumbing, sanitary, electrical and ventilation in KL & Selangor. From RM 6,000.",
    "subServices": [
      {
        "name": "Full Bathroom Renovation",
        "desc": "Complete bathroom rebuild: hacking, waterproofing with ponding test, tiling, plumbing, sanitary and electrical."
      },
      {
        "name": "Toilet Renovation",
        "desc": "Small toilet/WC renovation: WC replacement, wall and floor tiling, plumbing and ventilation."
      }
    ]
  },
  "awning-installation": {
    "slug": "awning-installation",
    "title": "Awning Installation Services",
    "tagline": "Custom awnings and awning roofing for car porches, entrances, windows, balconies and yards across the Klang Valley (KL & Selangor) — polycarbonate, metal deck, aluminium composite (ACP), glass and fabric systems, plus retractable awnings and outdoor roller blinds, fabricated and installed to suit your site. Project-quoted with a 12-month workmanship warranty.",
    "subServices": [
      {
        "name": "Car Porch Awning Installation",
        "desc": "New car porch / carport awning to shade and protect vehicles from sun and rain, sized to your porch with suitable slope and drainage."
      },
      {
        "name": "Polycarbonate Awning",
        "desc": "Polycarbonate sheet awning roofing in clear or tinted profiles — translucent, lightweight cover for porch, yard, walkway or balcony that lets natural light through."
      }
    ]
  }
};
