// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe cards for the six hand-built calculators linked from service
// pages. Import this instead of `config/tools-data.ts` in client components.

export type DedicatedToolCard = { slug: string; name: string; stats: { label: string; value: string }[] };

export const dedicatedToolCardBySlug: Record<string, DedicatedToolCard> = {
  "painting-calculator": {
    "slug": "painting-calculator",
    "name": "Painting Cost Calculator",
    "stats": [
      {
        "label": "Interior rate",
        "value": "RM 2–RM 7 / sq ft"
      },
      {
        "label": "From, per room",
        "value": "RM 450"
      },
      {
        "label": "Time to finish",
        "value": "Under 2 minutes"
      }
    ]
  },
  "plumbing-diagnostic": {
    "slug": "plumbing-diagnostic",
    "name": "Plumbing Diagnostic",
    "stats": [
      {
        "label": "Minor repair from",
        "value": "RM 150"
      },
      {
        "label": "Drain clearing from",
        "value": "RM 180"
      },
      {
        "label": "Diagnosis time",
        "value": "Under 2 minutes"
      }
    ]
  },
  "ceiling-calculator": {
    "slug": "ceiling-calculator",
    "name": "Ceiling Repair Estimator",
    "stats": [
      {
        "label": "Flat ceiling from",
        "value": "RM 10 / sq ft"
      },
      {
        "label": "Repair from",
        "value": "RM 220"
      },
      {
        "label": "Time to finish",
        "value": "Under 2 minutes"
      }
    ]
  },
  "leak-triage": {
    "slug": "leak-triage",
    "name": "Water Leak Triage",
    "stats": [
      {
        "label": "PU grouting",
        "value": "RM 80–RM 300 / point"
      },
      {
        "label": "Ceiling repair from",
        "value": "RM 220"
      },
      {
        "label": "Diagnosis time",
        "value": "Under 2 minutes"
      }
    ]
  },
  "tv-mount-advisor": {
    "slug": "tv-mount-advisor",
    "name": "TV Mount Advisor",
    "stats": [
      {
        "label": "Mounting from",
        "value": "RM 150"
      },
      {
        "label": "Power point from",
        "value": "RM 150 / point"
      },
      {
        "label": "Advice time",
        "value": "Under 1 minute"
      }
    ]
  }
};
