// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe problem link cards (title + symptom, trilingual). Import this
// from client components instead of `config/problem-data.ts`, which carries
// every cause, solution and FAQ for all problems.

export type ProblemNavItem = {
  slug: string;
  serviceSlug: string;
  title: string;
  symptom: string;
  costRange: string;
  i18n?: Partial<Record<"ms" | "zh", { title: string; symptom: string; costRange: string }>>;
};

export const problemNavList: ProblemNavItem[] = [
  {
    "slug": "peeling-paint-malaysia",
    "serviceSlug": "painting",
    "title": "Peeling Paint in Malaysian Homes",
    "symptom": "Paint flakes, bubbles, or chalks because moisture, weak primer, or old coatings break the bond with the wall.",
    "costRange": "RM150–RM900+ depending on wall condition and area size",
    "i18n": {
      "ms": {
        "title": "Cat Terkopek di Rumah Malaysia",
        "symptom": "Cat mengelupas, melecuh, atau berkapur kerana lembapan, primer lemah, atau salutan lama yang gagal melekat pada dinding.",
        "costRange": "RM150–RM900+ bergantung kepada keadaan dinding dan saiz kawasan"
      },
      "zh": {
        "title": "马来西亚房屋油漆剥落",
        "symptom": "由于潮气、底漆薄弱或旧涂层与墙面粘结失效，油漆出现片状剥落、起泡或粉化。",
        "costRange": "RM150–RM900+，视墙面状况和面积而定"
      }
    }
  },
  {
    "slug": "faded-exterior-paint-malaysia",
    "serviceSlug": "painting",
    "title": "Faded Exterior Paint After Malaysian Sun and Rain",
    "symptom": "Exterior walls look chalky, patchy, or washed out after UV exposure and heavy rain cycles.",
    "costRange": "RM1,800–RM8,000+ depending on house size and access",
    "i18n": {
      "ms": {
        "title": "Cat Eksterior Pudar Selepas Matahari dan Hujan Malaysia",
        "symptom": "Dinding luar kelihatan berkapur, berbelang, atau pudar selepas pendedahan UV dan kitaran hujan lebat.",
        "costRange": "RM1,800–RM8,000+ bergantung kepada saiz rumah dan akses"
      },
      "zh": {
        "title": "马来西亚阳光雨水导致外墙油漆褪色",
        "symptom": "经过紫外线照射与热带暴雨循环后，外墙呈现粉化、斑驳或褪色状态。",
        "costRange": "RM1,800–RM8,000+，视房屋大小和施工难度而定"
      }
    }
  },
  {
    "slug": "damp-walls-paint-bubbling",
    "serviceSlug": "waterproofing",
    "title": "Damp Walls and Paint Bubbling",
    "symptom": "Paint bubbles, brown stains, or white salt marks appear because water is moving through the wall or slab.",
    "costRange": "RM300–RM2,500+ depending on leak source",
    "i18n": {
      "ms": {
        "title": "Dinding Lembap dan Cat Menggelembung",
        "symptom": "Cat menggelembung, kesan perang, atau kesan garam putih muncul kerana air bergerak melalui dinding atau slab.",
        "costRange": "RM300–RM2,500+ bergantung kepada punca kebocoran"
      },
      "zh": {
        "title": "潮湿墙面与油漆起泡",
        "symptom": "由于水分透过墙体或楼板移动，油漆出现起泡、棕色渍痕或白色盐渍。",
        "costRange": "RM300–RM2,500+，视漏水源而定"
      }
    }
  },
  {
    "slug": "ceiling-mold-stains",
    "serviceSlug": "ceiling",
    "title": "Ceiling Mold and Brown Water Stains",
    "symptom": "Ceiling boards show dark mold, yellow-brown rings, or soft sagging areas after water exposure.",
    "costRange": "RM180–RM1,200+ based on ceiling board damage",
    "i18n": {
      "ms": {
        "title": "Kulat Siling dan Kesan Air Perang",
        "symptom": "Papan siling menunjukkan kulat gelap, cincin kuning-perang, atau kawasan melendut lembut selepas pendedahan air.",
        "costRange": "RM180–RM1,200+ berdasarkan kerosakan papan siling"
      },
      "zh": {
        "title": "天花板霉菌与棕色水渍",
        "symptom": "天花板板材在遇水后出现深色霉菌、黄棕色环渍或局部软化下垂区域。",
        "costRange": "RM180–RM1,200+，视天花板损坏程度而定"
      }
    }
  },
  {
    "slug": "burst-pipe-emergency",
    "serviceSlug": "plumbing",
    "title": "Burst Pipe Emergency in KL & Selangor",
    "symptom": "Water is spraying, flooding, or rapidly pooling from a pipe, valve, or wall area.",
    "costRange": "RM180–RM800+ depending on pipe access and material",
    "i18n": {
      "ms": {
        "title": "Kecemasan Paip Pecah di KL & Selangor",
        "symptom": "Air menyembur, membanjiri, atau bertakung dengan cepat daripada paip, injap, atau kawasan dinding.",
        "costRange": "RM180–RM800+ bergantung kepada akses dan bahan paip"
      },
      "zh": {
        "title": "吉隆坡与雪兰莪爆管紧急事件",
        "symptom": "水从管道、阀门或墙体区域喷出、泛滥或迅速积聚。",
        "costRange": "RM180–RM800+，视管道可及性和材质而定"
      }
    }
  },
  {
    "slug": "low-water-pressure-kl",
    "serviceSlug": "plumbing",
    "title": "Low Water Pressure in KL Homes",
    "symptom": "Showers, taps, or toilets have weak flow even when the main water valve is open.",
    "costRange": "RM120–RM1,500+ depending on diagnosis and pump needs",
    "i18n": {
      "ms": {
        "title": "Tekanan Air Rendah di Rumah KL",
        "symptom": "Pancuran, paip air, atau tandas mempunyai aliran lemah walaupun injap air utama terbuka.",
        "costRange": "RM120–RM1,500+ bergantung kepada diagnosis dan keperluan pam"
      },
      "zh": {
        "title": "吉隆坡住宅水压偏低",
        "symptom": "即使主水阀已完全打开，淋浴、水龙头或马桶的水流仍然微弱。",
        "costRange": "RM120–RM1,500+，视诊断和是否需要水泵而定"
      }
    }
  },
  {
    "slug": "blocked-drain-toilet",
    "serviceSlug": "plumbing",
    "title": "Blocked Drain or Toilet Choke",
    "symptom": "Water drains slowly, backs up, smells bad, or toilet water rises after flushing.",
    "costRange": "RM150–RM500+ depending on blockage severity",
    "i18n": {
      "ms": {
        "title": "Saliran atau Tandas Tersumbat",
        "symptom": "Air mengalir perlahan, mengundur, berbau busuk, atau air tandas naik selepas disiram.",
        "costRange": "RM150–RM500+ bergantung kepada keterukan sumbatan"
      },
      "zh": {
        "title": "排水管或马桶堵塞",
        "symptom": "排水缓慢、倒流、发出臭味，或冲厕后马桶水位升高。",
        "costRange": "RM150–RM500+，视堵塞严重程度而定"
      }
    }
  },
  {
    "slug": "water-heater-not-working",
    "serviceSlug": "plumbing",
    "title": "Water Heater Not Working",
    "symptom": "No hot water, low flow, tripping power, or leaking around the water heater unit.",
    "costRange": "RM120–RM650+ depending on part replacement or installation",
    "i18n": {
      "ms": {
        "title": "Pemanas Air Tidak Berfungsi",
        "symptom": "Tiada air panas, aliran rendah, trip kuasa, atau kebocoran di sekitar unit pemanas air.",
        "costRange": "RM120–RM650+ bergantung kepada penggantian bahagian atau pemasangan"
      },
      "zh": {
        "title": "热水器无法运作",
        "symptom": "无热水、水流量低、跳闸，或热水器周围出现漏水。",
        "costRange": "RM120–RM650+，视更换零件或整机安装而定"
      }
    }
  },
  {
    "slug": "sagging-plaster-ceiling",
    "serviceSlug": "ceiling",
    "title": "Sagging Plaster Ceiling",
    "symptom": "Ceiling boards bow downward, joints open, or the ceiling feels unsafe after moisture or weak framing.",
    "costRange": "RM180–RM1,500+ depending on damaged area and frame work",
    "i18n": {
      "ms": {
        "title": "Siling Plaster Melendut",
        "symptom": "Papan siling melentur ke bawah, sendi terbuka, atau siling terasa tidak selamat selepas lembapan atau rangka lemah.",
        "costRange": "RM180–RM1,500+ bergantung kepada kawasan rosak dan kerja rangka"
      },
      "zh": {
        "title": "石膏天花板下垂",
        "symptom": "天花板板材向下弯曲，接缝开裂，或因潮气或骨架薄弱使天花板感觉不安全。",
        "costRange": "RM180–RM1,500+，视受损面积和骨架工程而定"
      }
    }
  },
  {
    "slug": "ceiling-leak-after-rain",
    "serviceSlug": "waterproofing",
    "title": "Ceiling Leak After Rain",
    "symptom": "Ceiling drips or stains only during or after rain, often below roof, balcony, or exterior wall areas.",
    "costRange": "RM250–RM3,500+ depending on source and method",
    "i18n": {
      "ms": {
        "title": "Kebocoran Siling Selepas Hujan",
        "symptom": "Siling menitis atau berkesan hanya semasa atau selepas hujan, sering di bawah bumbung, balkoni, atau kawasan dinding luar.",
        "costRange": "RM250–RM3,500+ bergantung kepada punca dan kaedah"
      },
      "zh": {
        "title": "雨后天花板漏水",
        "symptom": "天花板仅在下雨期间或雨后滴水或出现渍痕，通常位于屋顶、阳台或外墙下方。",
        "costRange": "RM250–RM3,500+，视漏水源和处理方法而定"
      }
    }
  },
  {
    "slug": "cracked-ceiling-joints",
    "serviceSlug": "ceiling",
    "title": "Cracked Ceiling Joints",
    "symptom": "Straight-line cracks appear along plasterboard joints, especially after building movement or poor joint tape work.",
    "costRange": "RM180–RM900+ based on crack length and repainting",
    "i18n": {
      "ms": {
        "title": "Sendi Siling Retak",
        "symptom": "Retakan garis lurus muncul di sepanjang sendi papan plaster, terutamanya selepas pergerakan bangunan atau kerja pita sendi yang lemah.",
        "costRange": "RM180–RM900+ berdasarkan panjang retak dan pengecatan semula"
      },
      "zh": {
        "title": "天花板接缝开裂",
        "symptom": "石膏板接缝处出现直线裂缝，通常发生在建筑物位移或接缝贴带工艺不佳之后。",
        "costRange": "RM180–RM900+，视裂缝长度和是否需要重新粉刷而定"
      }
    }
  },
  {
    "slug": "condensation-ceiling-mold",
    "serviceSlug": "ceiling",
    "title": "Condensation Ceiling Mold",
    "symptom": "Black mold or spotting appears in cool rooms, bathrooms, or air-conditioned spaces without obvious leaks.",
    "costRange": "RM180–RM1,000+ depending on cleaning, board repair, and repainting",
    "i18n": {
      "ms": {
        "title": "Kulat Siling Kondensasi",
        "symptom": "Kulat hitam atau bintik muncul di bilik sejuk, bilik air, atau ruang berhawa dingin tanpa kebocoran ketara.",
        "costRange": "RM180–RM1,000+ bergantung kepada pembersihan, pembaikan papan, dan pengecatan semula"
      },
      "zh": {
        "title": "冷凝导致的天花板霉菌",
        "symptom": "在没有明显漏水的情况下，凉爽房间、浴室或空调空间的天花板出现黑色霉菌或斑点。",
        "costRange": "RM180–RM1,000+，视清洁、板材修复和重新粉刷而定"
      }
    }
  },
  {
    "slug": "bathroom-leak-upper-floor",
    "serviceSlug": "waterproofing",
    "title": "Upper-Floor Bathroom Leak",
    "symptom": "A lower ceiling drips below an upstairs bathroom, especially after showering or floor washing.",
    "costRange": "RM250–RM9,000 depending on PU injection, no-hack coating, or full re-waterproofing",
    "i18n": {
      "ms": {
        "title": "Kebocoran Bilik Air Tingkat Atas",
        "symptom": "Siling bawah menitis di bawah bilik air atas, terutamanya selepas mandi atau mencuci lantai.",
        "costRange": "RM250–RM9,000 bergantung kepada suntikan PU, salutan tanpa hacking, atau kalis air semula penuh"
      },
      "zh": {
        "title": "楼上浴室漏水",
        "symptom": "楼下天花板在楼上浴室下方滴水，尤其是在淋浴或冲洗地板后。",
        "costRange": "RM250–RM9,000，视 PU 注射、非破坏性涂层或全面重新防水而定"
      }
    }
  },
  {
    "slug": "roof-leak-rainy-season",
    "serviceSlug": "waterproofing",
    "title": "Roof Leak During Rainy Season",
    "symptom": "Water enters during storms through roof tiles, gutters, flashing, or flat roof membranes.",
    "costRange": "RM250–RM5,000+ depending on roof access and waterproofing scope",
    "i18n": {
      "ms": {
        "title": "Kebocoran Bumbung Semasa Musim Hujan",
        "symptom": "Air masuk semasa ribut melalui jubin bumbung, saliran, kilasan, atau membran bumbung rata.",
        "costRange": "RM250–RM5,000+ bergantung kepada akses bumbung dan skop kalis air"
      },
      "zh": {
        "title": "雨季屋顶漏水",
        "symptom": "暴雨期间，水通过屋顶瓦片、排水沟、防水板或平屋顶防水层渗入室内。",
        "costRange": "RM250–RM5,000+，视屋顶可及性和防水范围而定"
      }
    }
  },
  {
    "slug": "wall-dampness-rising",
    "serviceSlug": "waterproofing",
    "title": "Rising Damp and Lower Wall Peeling",
    "symptom": "Paint flakes and white salts appear near the bottom of walls, often in older landed homes.",
    "costRange": "RM300–RM3,000+ depending on wall length and waterproofing approach",
    "i18n": {
      "ms": {
        "title": "Lembapan Naik dan Pengelupasan Dinding Bawah",
        "symptom": "Cat mengelupas dan garam putih muncul berhampiran bahagian bawah dinding, sering di rumah bertanah lama.",
        "costRange": "RM300–RM3,000+ bergantung kepada panjang dinding dan pendekatan kalis air"
      },
      "zh": {
        "title": "毛细返潮与下层墙面剥落",
        "symptom": "墙面下部出现油漆剥落和白色盐渍，常见于老旧有地房屋。",
        "costRange": "RM300–RM3,000+，视墙体长度和防水方式而定"
      }
    }
  },
  {
    "slug": "swimming-pool-leak-balcony",
    "serviceSlug": "waterproofing",
    "title": "Balcony or Pool Deck Leak",
    "symptom": "Water seeps from balcony, pool deck, or terrace areas into rooms or ceilings below.",
    "costRange": "RM850–RM12,000+ depending on surface area and hacking needs",
    "i18n": {
      "ms": {
        "title": "Kebocoran Balkoni atau Dek Kolam",
        "symptom": "Air merembes daripada balkoni, dek kolam, atau kawasan teres ke dalam bilik atau siling bawah.",
        "costRange": "RM850–RM12,000+ bergantung kepada saiz permukaan dan keperluan hacking"
      },
      "zh": {
        "title": "阳台或泳池平台漏水",
        "symptom": "水从阳台、泳池平台或露台区域渗入下方房间或天花板。",
        "costRange": "RM850–RM12,000+，视表面积和凿除需求而定"
      }
    }
  },
  {
    "slug": "loose-door-hinge",
    "serviceSlug": "handyman",
    "title": "Loose Door Hinge or Scraping Door",
    "symptom": "Door drops, scrapes the floor, fails to latch, or hinges pull loose from the frame.",
    "costRange": "RM90–RM350+ depending on hinge and frame condition",
    "i18n": {
      "ms": {
        "title": "Engsel Pintu Longgar atau Pintu Menggesel",
        "symptom": "Pintu jatuh, menggesel lantai, gagal mengancing, atau engsel tertanggal dari rangka.",
        "costRange": "RM90–RM350+ bergantung kepada keadaan engsel dan rangka"
      },
      "zh": {
        "title": "门铰链松动或门刮擦地面",
        "symptom": "门下垂、刮擦地毯，或门闩无法锁上。",
        "costRange": "RM90–RM350+，视铰链和门框状况而定"
      }
    }
  },
  {
    "slug": "tv-fell-off-wall",
    "serviceSlug": "handyman",
    "title": "Unsafe TV Wall Mount or Failed Anchors",
    "symptom": "TV bracket is loose, wall plugs are pulling out, or TV was mounted on the wrong wall anchor type.",
    "costRange": "RM120–RM450+ depending on TV size, bracket, and wall type",
    "i18n": {
      "ms": {
        "title": "Pemasangan Dinding TV Tidak Selamat atau Sauh Gagal",
        "symptom": "Braket TV longgar, plag dinding tertanggal, atau TV dipasang pada jenis sauh dinding yang salah.",
        "costRange": "RM120–RM450+ bergantung kepada saiz TV, braket, dan jenis dinding"
      },
      "zh": {
        "title": "电视挂墙不安全或锚固件失效",
        "symptom": "电视支架松动，墙塞脱落，或电视安装在错误类型的墙壁锚固件上。",
        "costRange": "RM120–RM450+，视电视尺寸、支架和墙壁类型而定"
      }
    }
  },
  {
    "slug": "stuck-window-lock",
    "serviceSlug": "handyman",
    "title": "Stuck Window Lock or Handle",
    "symptom": "Window handle jams, lock no longer catches, or sliding window does not close securely.",
    "costRange": "RM80–RM300+ depending on parts and window type",
    "i18n": {
      "ms": {
        "title": "Kunci atau Pemegang Tingkap Tersangkut",
        "symptom": "Pemegang tingkap tersekat, kunci tidak lagi mengancing, atau tingkap gelongsor tidak menutup dengan selamat.",
        "costRange": "RM80–RM300+ bergantung kepada bahagian dan jenis tingkap"
      },
      "zh": {
        "title": "窗锁或把手卡住",
        "symptom": "窗户把手卡住、锁扣无法闭合，或推拉窗无法安全关闭。",
        "costRange": "RM80–RM300+，视零件和窗户类型而定"
      }
    }
  },
  {
    "slug": "ikea-furniture-assembly-help",
    "serviceSlug": "handyman",
    "title": "IKEA or Flat-Pack Furniture Assembly Help",
    "symptom": "Wardrobes, beds, shelves, or desks are difficult to assemble, unstable, or need wall anchoring.",
    "costRange": "RM100–RM600+ depending on furniture size and complexity",
    "i18n": {
      "ms": {
        "title": "Bantuan Pemasangan Perabot IKEA atau Flat-Pack",
        "symptom": "Almari, katil, rak, atau meja sukar dipasang, tidak stabil, atau memerlukan sauh dinding.",
        "costRange": "RM100–RM600+ bergantung kepada saiz dan kerumitan perabot"
      },
      "zh": {
        "title": "IKEA 或平板包装家具组装协助",
        "symptom": "衣柜、床架、置物架或书桌难以组装、不稳固，或需要墙壁锚固。",
        "costRange": "RM100–RM600+，视家具尺寸和复杂程度而定"
      }
    }
  },
  {
    "slug": "rccb-tripping-kl",
    "serviceSlug": "electrical",
    "title": "RCCB / ELCB Keeps Tripping in KL Homes",
    "symptom": "Main RCCB trips repeatedly, especially when AC, water heater or multiple appliances are turned on.",
    "costRange": "RM180–RM850+ depending on diagnosis and DB upgrade",
    "i18n": {
      "ms": {
        "title": "RCCB / ELCB Kerap Trip di Rumah KL",
        "symptom": "RCCB utama kerap trip, terutamanya apabila AC, pemanas air atau beberapa perkakas dihidupkan.",
        "costRange": "RM180–RM850+ bergantung kepada diagnosis dan naik taraf DB"
      },
      "zh": {
        "title": "KL 住宅 RCCB / ELCB 频繁跳闸",
        "symptom": "主 RCCB 频繁跳闸，尤其在开启空调、热水器或多个电器时。",
        "costRange": "RM180–RM850+，视诊断和 DB 升级而定"
      }
    }
  },
  {
    "slug": "flickering-lights-kl",
    "serviceSlug": "electrical",
    "title": "Flickering Lights or Dimming When Appliances Turn On",
    "symptom": "Lights flicker or dim when AC, water heater, or microwave starts.",
    "costRange": "RM120–RM650+ depending on wiring and DB work",
    "i18n": {
      "ms": {
        "title": "Lampu Berkelip atau Malap Apabila Perkakas Dihidupkan",
        "symptom": "Lampu berkelip atau malap apabila AC, pemanas air atau microwave dihidupkan.",
        "costRange": "RM120–RM650+ bergantung kepada pendawaian dan kerja DB"
      },
      "zh": {
        "title": "电器开启时灯光闪烁或变暗",
        "symptom": "开启空调、热水器或微波炉时灯光闪烁或变暗。",
        "costRange": "RM120–RM650+，视布线和 DB 工作而定"
      }
    }
  },
  {
    "slug": "water-heater-not-heating",
    "serviceSlug": "water-heater",
    "title": "Instant Water Heater Not Heating or Weak Flow",
    "symptom": "No hot water or very slow heating even after 2–3 minutes.",
    "costRange": "RM150–RM680+ depending on element or unit replacement",
    "i18n": {
      "ms": {
        "title": "Pemanas Air Segera Tidak Panas atau Aliran Lemah",
        "symptom": "Tiada air panas atau pemanasan sangat perlahan walaupun selepas 2–3 minit.",
        "costRange": "RM150–RM680+ bergantung kepada elemen atau penggantian unit"
      },
      "zh": {
        "title": "即热式热水器不加热或水流弱",
        "symptom": "即使运行 2–3 分钟后仍无热水或加热非常缓慢。",
        "costRange": "RM150–RM680+，视加热元件或整机更换而定"
      }
    }
  },
  {
    "slug": "ceiling-fan-wobbling",
    "serviceSlug": "ceiling-fan",
    "title": "Ceiling Fan Wobbling or Vibrating Loudly",
    "symptom": "Fan wobbles, makes noise, or feels unstable when running at medium/high speed.",
    "costRange": "RM90–RM380+ depending on balancing or replacement",
    "i18n": {
      "ms": {
        "title": "Kipas Siling Bergetar atau Bising Kuat",
        "symptom": "Kipas bergetar, mengeluarkan bunyi atau terasa tidak stabil apabila berjalan pada kelajuan sederhana/tinggi.",
        "costRange": "RM90–RM380+ bergantung kepada pengimbangan atau penggantian"
      },
      "zh": {
        "title": "吊扇晃动或噪音大",
        "symptom": "吊扇在中高速时晃动、发出噪音或感觉不稳。",
        "costRange": "RM90–RM380+，视平衡校正或更换而定"
      }
    }
  },
  {
    "slug": "hollow-tiles-floor",
    "serviceSlug": "tiling",
    "title": "Hollow Sounding Tiles or Loose Floor Tiles",
    "symptom": "Tiles sound hollow when tapped and some are lifting or cracking.",
    "costRange": "RM180–RM1,200+ depending on area and substrate repair",
    "i18n": {
      "ms": {
        "title": "Jubin Berongga atau Longgar di Lantai",
        "symptom": "Jubin berongga apabila diketuk dan sebahagiannya terangkat atau retak.",
        "costRange": "RM180–RM1,200+ bergantung kepada kawasan dan pembaikan substrat"
      },
      "zh": {
        "title": "地板瓷砖空鼓或松动",
        "symptom": "敲击时瓷砖有空鼓声，部分瓷砖翘起或开裂。",
        "costRange": "RM180–RM1,200+，视面积和基层修复而定"
      }
    }
  },
  {
    "slug": "spc-flooring-peeling-edges",
    "serviceSlug": "flooring",
    "title": "SPC / Vinyl Flooring Peeling at Edges or Seams",
    "symptom": "Flooring edges are lifting, seams opening, or planks are buckling.",
    "costRange": "RM120–RM950+ depending on area and cause",
    "i18n": {
      "ms": {
        "title": "Lantai SPC / Vinyl Terkupas di Tepi atau Sendi",
        "symptom": "Tepi lantai terangkat, sendi terbuka, atau papan melengkung.",
        "costRange": "RM120–RM950+ bergantung kepada kawasan dan punca"
      },
      "zh": {
        "title": "SPC / 乙烯基地板边缘或接缝剥离",
        "symptom": "地板边缘翘起、接缝打开或板材起拱。",
        "costRange": "RM120–RM950+，视面积和原因而定"
      }
    }
  },
  {
    "slug": "clogged-gutter-leaking",
    "serviceSlug": "roof-repair",
    "title": "Clogged Gutter Causing Roof Leak or Overflow",
    "symptom": "Water overflows from gutter during rain, causing wall or ceiling leaks.",
    "costRange": "RM280–RM1,200+ depending on cleaning + repair scope",
    "i18n": {
      "ms": {
        "title": "Saliran Tersumbat Menyebabkan Kebocoran atau Limpahan Bumbung",
        "symptom": "Air melimpah dari saliran semasa hujan, menyebabkan kebocoran dinding atau siling.",
        "costRange": "RM280–RM1,200+ bergantung kepada skop pembersihan + pembaikan"
      },
      "zh": {
        "title": "排水沟堵塞导致屋顶漏水或溢流",
        "symptom": "下雨时排水沟溢流，导致墙面或天花板漏水。",
        "costRange": "RM280–RM1,200+，视清理与维修范围而定"
      }
    }
  },
  {
    "slug": "kitchen-cabinet-door-misaligned",
    "serviceSlug": "kitchen-cabinet",
    "title": "Kitchen Cabinet Doors Misaligned or Not Closing Properly",
    "symptom": "Cabinet doors are uneven, rubbing, or will not stay closed.",
    "costRange": "RM90–RM450+ depending on hinge replacement and adjustment",
    "i18n": {
      "ms": {
        "title": "Pintu Kabinet Dapur Tidak Sejajar atau Tidak Menutup dengan Betul",
        "symptom": "Pintu kabinet tidak sekata, bergesel, atau tidak kekal tertutup.",
        "costRange": "RM90–RM450+ bergantung kepada penggantian engsel dan pelarasan"
      },
      "zh": {
        "title": "厨房橱柜门错位或无法正常关闭",
        "symptom": "橱柜门不平整、摩擦或无法保持关闭。",
        "costRange": "RM90–RM450+，视铰链更换和调整而定"
      }
    }
  },
  {
    "slug": "flickering-downlights",
    "serviceSlug": "lighting",
    "title": "Downlights Flickering or Not Turning On",
    "symptom": "LED downlights flicker, buzz, or fail to turn on after a few months.",
    "costRange": "RM80–RM320+ per point depending on driver replacement",
    "i18n": {
      "ms": {
        "title": "Downlight Berkelip atau Tidak Menyala",
        "symptom": "Downlight LED berkelip, berdengung, atau gagal menyala selepas beberapa bulan.",
        "costRange": "RM80–RM320+ setiap titik bergantung kepada penggantian pemacu"
      },
      "zh": {
        "title": "筒灯闪烁或无法开启",
        "symptom": "LED 筒灯使用几个月后出现闪烁、嗡嗡声或无法开启。",
        "costRange": "RM80–RM320+/点，视驱动器更换而定"
      }
    }
  },
  {
    "slug": "plaster-ceiling-cracking-joints",
    "serviceSlug": "plaster-ceiling",
    "title": "Plaster Ceiling Joint Cracking After Installation",
    "symptom": "Straight cracks appear along plasterboard joints within months of installation.",
    "costRange": "RM150–RM850+ depending on area",
    "i18n": {
      "ms": {
        "title": "Retakan Sendi Siling Plaster Selepas Pemasangan",
        "symptom": "Retakan lurus muncul di sepanjang sendi papan plaster dalam beberapa bulan selepas pemasangan.",
        "costRange": "RM150–RM850+ bergantung kepada kawasan"
      },
      "zh": {
        "title": "石膏天花板安装后接缝开裂",
        "symptom": "安装后几个月内石膏板接缝处出现直线裂缝。",
        "costRange": "RM150–RM850+，视面积而定"
      }
    }
  },
  {
    "slug": "peeling-skim-coat",
    "serviceSlug": "skim-coat",
    "title": "Skim Coat Peeling or Powdering After Painting",
    "symptom": "New skim coat surface is powdery, peeling, or not holding paint well.",
    "costRange": "RM120–RM680+ depending on area",
    "i18n": {
      "ms": {
        "title": "Skim Coat Terkopek atau Berserbuk Selepas Pengecatan",
        "symptom": "Permukaan skim coat baru berserbuk, terkopek, atau tidak memegang cat dengan baik.",
        "costRange": "RM120–RM680+ bergantung kepada kawasan"
      },
      "zh": {
        "title": "批灰粉刷后剥落或粉化",
        "symptom": "新批灰表面出现粉化、剥落，或无法很好地附着油漆。",
        "costRange": "RM120–RM680+，视面积而定"
      }
    }
  },
  {
    "slug": "epoxy-floor-yellowing",
    "serviceSlug": "epoxy-flooring",
    "title": "Epoxy Floor Yellowing or Discoloring",
    "symptom": "New epoxy floor has turned yellow, especially in areas exposed to sunlight.",
    "costRange": "RM280–RM1,800+ depending on area",
    "i18n": {
      "ms": {
        "title": "Lantai Epoxy Menguning atau Berubah Warna",
        "symptom": "Lantai epoxy baru bertukar kuning, terutamanya di kawasan terdedah kepada cahaya matahari.",
        "costRange": "RM280–RM1,800+ bergantung kepada kawasan"
      },
      "zh": {
        "title": "环氧地板变黄或褪色",
        "symptom": "新环氧地板出现发黄，尤其是在阳光照射的区域。",
        "costRange": "RM280–RM1,800+，视面积而定"
      }
    }
  },
  {
    "slug": "wardrobe-door-not-closing",
    "serviceSlug": "carpentry",
    "title": "Built-in Wardrobe Door Not Closing or Misaligned",
    "symptom": "Wardrobe doors are uneven, rubbing against each other, or will not close flush.",
    "costRange": "RM120–RM580+ depending on adjustment or hinge work",
    "i18n": {
      "ms": {
        "title": "Pintu Almari Bina-Dalam Tidak Menutup atau Tidak Sejajar",
        "symptom": "Pintu almari tidak sekata, bergesel antara satu sama lain, atau tidak menutup rata.",
        "costRange": "RM120–RM580+ bergantung kepada pelarasan atau kerja engsel"
      },
      "zh": {
        "title": "定制衣柜门无法关闭或错位",
        "symptom": "衣柜门不平整、彼此摩擦，或无法平齐关闭。",
        "costRange": "RM120–RM580+，视调整或铰链工作而定"
      }
    }
  },
  {
    "slug": "door-scraping-floor",
    "serviceSlug": "door",
    "title": "Door Scraping Floor or Not Latching Properly",
    "symptom": "Door drags on floor, scrapes carpet, or latch does not catch.",
    "costRange": "RM80–RM350+ depending on work needed",
    "i18n": {
      "ms": {
        "title": "Pintu Menggesel Lantai atau Tidak Mengancing dengan Betul",
        "symptom": "Pintu menggesel lantai, bergesel dengan karpet, atau kancing tidak mengait.",
        "costRange": "RM80–RM350+ bergantung kepada kerja yang diperlukan"
      },
      "zh": {
        "title": "门刮擦地板或无法正常锁上",
        "symptom": "门拖擦地面、刮擦地毯，或门闩无法扣合。",
        "costRange": "RM80–RM350+，视所需工作而定"
      }
    }
  },
  {
    "slug": "sliding-window-stuck",
    "serviceSlug": "window-repair",
    "title": "Sliding Window Stuck or Hard to Open",
    "symptom": "Sliding window is difficult to move, jumps off track, or will not lock.",
    "costRange": "RM90–RM420+ depending on parts",
    "i18n": {
      "ms": {
        "title": "Tingkap Gelongsor Tersekat atau Sukar Dibuka",
        "symptom": "Tingkap gelongsor sukar digerakkan, terkeluar dari trek, atau tidak mengunci.",
        "costRange": "RM90–RM420+ bergantung kepada bahagian"
      },
      "zh": {
        "title": "推拉窗卡住或难以开启",
        "symptom": "推拉窗移动困难、脱离轨道，或无法上锁。",
        "costRange": "RM90–RM420+，视零件而定"
      }
    }
  },
  {
    "slug": "smart-lock-not-working",
    "serviceSlug": "locksmith",
    "title": "Smart Lock Not Responding or Battery Draining Fast",
    "symptom": "Digital/smart lock is unresponsive, app not connecting, or battery drains quickly.",
    "costRange": "RM150–RM680+ depending on model and issue",
    "i18n": {
      "ms": {
        "title": "Kunci Pintar Tidak Bertindak Balas atau Bateri Cepat Habis",
        "symptom": "Kunci digital/pintar tidak bertindak balas, apl tidak menyambung, atau bateri cepat habis.",
        "costRange": "RM150–RM680+ bergantung kepada model dan isu"
      },
      "zh": {
        "title": "智能锁无响应或耗电过快",
        "symptom": "数字/智能锁无响应、应用无法连接，或电池耗电过快。",
        "costRange": "RM150–RM680+，视型号和问题而定"
      }
    }
  },
  {
    "slug": "shower-screen-leaking",
    "serviceSlug": "glass-aluminium",
    "title": "Frameless Shower Screen Leaking at Bottom",
    "symptom": "Water leaks from the bottom of the shower screen onto the floor.",
    "costRange": "RM180–RM750+ depending on seal replacement",
    "i18n": {
      "ms": {
        "title": "Skrin Pancuran Tanpa Bingkai Bocor di Bahagian Bawah",
        "symptom": "Air bocor dari bahagian bawah skrin pancuran ke lantai.",
        "costRange": "RM180–RM750+ bergantung kepada penggantian pengedap"
      },
      "zh": {
        "title": "无框淋浴屏底部漏水",
        "symptom": "水从淋浴屏底部渗漏到地面。",
        "costRange": "RM180–RM750+，视密封条更换而定"
      }
    }
  },
  {
    "slug": "mold-in-bathroom-after-cleaning",
    "serviceSlug": "cleaning",
    "title": "Mold Returning Quickly After Professional Cleaning",
    "symptom": "Black mold appears again in bathroom within 1–2 weeks after cleaning.",
    "costRange": "RM120–RM450+ depending on treatment",
    "i18n": {
      "ms": {
        "title": "Kulat Kembali Pesat Selepas Pembersihan Profesional",
        "symptom": "Kulat hitam muncul semula di bilik air dalam 1–2 minggu selepas pembersihan.",
        "costRange": "RM120–RM450+ bergantung kepada rawatan"
      },
      "zh": {
        "title": "专业清洁后霉菌迅速再次出现",
        "symptom": "清洁后 1–2 周内浴室黑霉再次出现。",
        "costRange": "RM120–RM450+，视处理方式而定"
      }
    }
  },
  {
    "slug": "stubborn-grout-stains-after-deep-clean",
    "serviceSlug": "deep-cleaning",
    "title": "Grout Still Stained After Deep Cleaning Service",
    "symptom": "Bathroom or kitchen grout remains discolored even after professional deep clean.",
    "costRange": "RM180–RM680+ depending on area and method",
    "i18n": {
      "ms": {
        "title": "Grout Masih Berkesan Selepas Perkhidmatan Pembersihan Mendalam",
        "symptom": "Grout bilik air atau dapur kekal berubah warna walaupun selepas pembersihan mendalam profesional.",
        "costRange": "RM180–RM680+ bergantung kepada kawasan dan kaedah"
      },
      "zh": {
        "title": "深度清洁后瓷砖填缝仍有污渍",
        "symptom": "即使经过专业深度清洁，浴室或厨房的填缝仍然变色。",
        "costRange": "RM180–RM680+，视面积和方法而定"
      }
    }
  },
  {
    "slug": "construction-dust-returning",
    "serviceSlug": "post-renovation-cleaning",
    "title": "Fine Construction Dust Returning After Post-Reno Clean",
    "symptom": "Fine white or grey dust keeps appearing on surfaces days after post-renovation cleaning.",
    "costRange": "RM250–RM950+ depending on property size",
    "i18n": {
      "ms": {
        "title": "Habuk Pembinaan Halus Kembali Selepas Pembersihan Selepas Renovasi",
        "symptom": "Habuk putih atau kelabu halus terus muncul pada permukaan beberapa hari selepas pembersihan pasca renovasi.",
        "costRange": "RM250–RM950+ bergantung kepada saiz hartanah"
      },
      "zh": {
        "title": "装修后清洁后细粉尘再次出现",
        "symptom": "装修后清洁数天后，细白色或灰色粉尘仍持续出现在表面。",
        "costRange": "RM250–RM950+，视物业大小而定"
      }
    }
  },
  {
    "slug": "cctv-not-recording",
    "serviceSlug": "cctv",
    "title": "CCTV Camera Not Recording or Footage Missing",
    "symptom": "Cameras show live view but no recordings, or footage is corrupted/missing.",
    "costRange": "RM180–RM850+ depending on NVR/HDD issue",
    "i18n": {
      "ms": {
        "title": "Kamera CCTV Tidak Merakam atau Rakaman Hilang",
        "symptom": "Kamera menunjukkan paparan langsung tetapi tiada rakaman, atau rakaman rosak/hilang.",
        "costRange": "RM180–RM850+ bergantung kepada isu NVR/HDD"
      },
      "zh": {
        "title": "CCTV 摄像头无法录像或录像丢失",
        "symptom": "摄像头能显示实时画面但无录像，或录像损坏/丢失。",
        "costRange": "RM180–RM850+，视 NVR/硬盘问题而定"
      }
    }
  },
  {
    "slug": "autogate-not-closing",
    "serviceSlug": "autogate",
    "title": "Autogate Not Closing or Motor Running Continuously",
    "symptom": "Autogate opens but will not close, or motor keeps running without stopping.",
    "costRange": "RM250–RM1,200+ depending on motor or sensor replacement",
    "i18n": {
      "ms": {
        "title": "Autogate Tidak Menutup atau Motor Berjalan Berterusan",
        "symptom": "Autogate terbuka tetapi tidak akan menutup, atau motor terus berjalan tanpa berhenti.",
        "costRange": "RM250–RM1,200+ bergantung kepada penggantian motor atau sensor"
      },
      "zh": {
        "title": "自动门无法关闭或电机持续运转",
        "symptom": "自动门可以打开但无法关闭，或电机持续运转不停止。",
        "costRange": "RM250–RM1,200+，视电机或传感器更换而定"
      }
    }
  },
  {
    "slug": "rusting-window-grille",
    "serviceSlug": "welding",
    "title": "Window Grille or Gate Rusting Quickly",
    "symptom": "New or recently painted grille/gate shows rust spots within months.",
    "costRange": "RM150–RM680+ depending on area and treatment",
    "i18n": {
      "ms": {
        "title": "Grille Tingkap atau Pintu Pagar Berkarat Pesat",
        "symptom": "Grille/pagar baru atau baru dicat menunjukkan bintik karat dalam beberapa bulan.",
        "costRange": "RM150–RM680+ bergantung kepada kawasan dan rawatan"
      },
      "zh": {
        "title": "窗户护栏或大门快速生锈",
        "symptom": "新的或近期上漆的护栏/大门在几个月内出现锈斑。",
        "costRange": "RM150–RM680+，视面积和处理方式而定"
      }
    }
  },
  {
    "slug": "yellowing-white-walls",
    "serviceSlug": "painting",
    "title": "White Walls Turning Yellow / Cream",
    "symptom": "Once-white walls start looking cream, yellow, or dirty after 12–36 months even without touching them.",
    "costRange": "RM 400–RM 3,500+ depending on room count and cause",
    "i18n": {
      "ms": {
        "title": "Dinding Putih Bertukar Kuning / Krim",
        "symptom": "Once-white walls start looking cream, yellow, or dirty after 12–36 months even without touching them.",
        "costRange": "RM 400–RM 3,500+ bergantung kepada bilangan bilik dan punca"
      },
      "zh": {
        "title": "白墙发黄 / 变黄",
        "symptom": "Once-white walls start looking cream, yellow, or dirty after 12–36 months even without touching them.",
        "costRange": "RM 400–RM 3,500+，视房间数量和原因而定"
      }
    }
  },
  {
    "slug": "paint-cracking-hairline-walls",
    "serviceSlug": "painting",
    "title": "Hairline Cracks Appearing on Painted Walls",
    "symptom": "Fine spidery cracks appear on painted walls, often around window frames, door frames, or ceiling-wall junctions.",
    "costRange": "RM 300–RM 2,200+ depending on crack length and repaint scope",
    "i18n": {
      "ms": {
        "title": "Retak Rambut pada Dinding Bercat",
        "symptom": "Fine spidery cracks appear on painted walls, often around window frames, door frames, or ceiling-wall junctions.",
        "costRange": "RM 300–RM 2,200+ bergantung kepada panjang retakan dan skop pengecatan semula"
      },
      "zh": {
        "title": "涂漆墙面出现发丝裂纹",
        "symptom": "Fine spidery cracks appear on painted walls, often around window frames, door frames, or ceiling-wall junctions.",
        "costRange": "RM 300–RM 2,200+，视裂纹长度和重涂范围而定"
      }
    }
  },
  {
    "slug": "leaking-bathroom",
    "serviceSlug": "plumbing",
    "title": "Leaking Bathroom (Wet Floor Below, Damp Walls)",
    "symptom": "The floor below your upstairs bathroom is wet or damp, or the wall next to the bathroom shows brown stains and paint bubbling.",
    "costRange": "RM 350–RM 4,500+ depending on leak source",
    "i18n": {
      "ms": {
        "title": "Bilik Air Bocor (Lantai Basah, Dinding Lembap)",
        "symptom": "The floor below your upstairs bathroom is wet or damp, or the wall next to the bathroom shows brown stains and paint bubbling.",
        "costRange": "RM 350–RM 4,500+ bergantung kepada punca kebocoran"
      },
      "zh": {
        "title": "浴室漏水（楼下地面潮湿、墙壁渗水）",
        "symptom": "The floor below your upstairs bathroom is wet or damp, or the wall next to the bathroom shows brown stains and paint bubbling.",
        "costRange": "RM 350–RM 4,500+，视漏水原因而定"
      }
    }
  },
  {
    "slug": "low-water-pressure",
    "serviceSlug": "plumbing",
    "title": "Low Water Pressure at Home",
    "symptom": "Weak shower flow, taps trickling, or the water heater struggling to trigger because incoming pressure is too low.",
    "costRange": "RM 200–RM 3,500+ depending on cause and fixture count",
    "i18n": {
      "ms": {
        "title": "Tekanan Air Rendah di Rumah",
        "symptom": "Weak shower flow, taps trickling, or the water heater struggling to trigger because incoming pressure is too low.",
        "costRange": "RM 200–RM 3,500+ bergantung kepada punca dan bilangan paip"
      },
      "zh": {
        "title": "家中水压过低",
        "symptom": "Weak shower flow, taps trickling, or the water heater struggling to trigger because incoming pressure is too low.",
        "costRange": "RM 200–RM 3,500+，视原因和水龙头数量而定"
      }
    }
  },
  {
    "slug": "clogged-drain",
    "serviceSlug": "plumbing",
    "title": "Clogged Kitchen or Bathroom Drain",
    "symptom": "Water drains slowly, sits in the sink or shower tray, or backs up when you run multiple taps.",
    "costRange": "RM 150–RM 700+ depending on clog severity",
    "i18n": {
      "ms": {
        "title": "Saluran Dapur atau Bilik Air Tersumbat",
        "symptom": "Water drains slowly, sits in the sink or shower tray, or backs up when you run multiple taps.",
        "costRange": "RM 150–RM 700+ bergantung kepada tahap penyumbatan"
      },
      "zh": {
        "title": "厨房或浴室下水道堵塞",
        "symptom": "Water drains slowly, sits in the sink or shower tray, or backs up when you run multiple taps.",
        "costRange": "RM 150–RM 700+，视堵塞程度而定"
      }
    }
  },
  {
    "slug": "toilet-not-flushing",
    "serviceSlug": "plumbing",
    "title": "Toilet Not Flushing Properly",
    "symptom": "Toilet flushes weakly, does not clear the bowl in one press, or keeps running after flushing.",
    "costRange": "RM 150–RM 850+ depending on part replacement",
    "i18n": {
      "ms": {
        "title": "Tandas Tidak Berfungsi dengan Baik",
        "symptom": "Toilet flushes weakly, does not clear the bowl in one press, or keeps running after flushing.",
        "costRange": "RM 150–RM 850+ bergantung kepada penggantian bahagian"
      },
      "zh": {
        "title": "马桶冲水不畅",
        "symptom": "Toilet flushes weakly, does not clear the bowl in one press, or keeps running after flushing.",
        "costRange": "RM 150–RM 850+，视更换部件而定"
      }
    }
  },
  {
    "slug": "sagging-ceiling",
    "serviceSlug": "ceiling",
    "title": "Sagging or Bowing Plaster Ceiling",
    "symptom": "Sections of the ceiling visibly droop, feel soft when tapped, or show a curved dip in the board.",
    "costRange": "RM 380–RM 2,800+ depending on board area to replace",
    "i18n": {
      "ms": {
        "title": "Siling Plaster Melendut atau Melengkung",
        "symptom": "Sections of the ceiling visibly droop, feel soft when tapped, or show a curved dip in the board.",
        "costRange": "RM 380–RM 2,800+ bergantung kepada keluasan papan yang diganti"
      },
      "zh": {
        "title": "石膏天花板下垂或变形",
        "symptom": "Sections of the ceiling visibly droop, feel soft when tapped, or show a curved dip in the board.",
        "costRange": "RM 380–RM 2,800+，视需更换的天花板面积而定"
      }
    }
  },
  {
    "slug": "ceiling-cornice-crack",
    "serviceSlug": "ceiling",
    "title": "Cornice Cracks Between Wall and Ceiling",
    "symptom": "Visible cracks or gaps appear at the joint between the wall and the plaster cornice moulding.",
    "costRange": "RM 200–RM 900+ depending on room count",
    "i18n": {
      "ms": {
        "title": "Retak Kornis Antara Dinding dan Siling",
        "symptom": "Visible cracks or gaps appear at the joint between the wall and the plaster cornice moulding.",
        "costRange": "RM 200–RM 900+ bergantung kepada bilangan bilik"
      },
      "zh": {
        "title": "墙面与天花板之间石膏线开裂",
        "symptom": "Visible cracks or gaps appear at the joint between the wall and the plaster cornice moulding.",
        "costRange": "RM 200–RM 900+，视房间数量而定"
      }
    }
  },
  {
    "slug": "balcony-leak-condo",
    "serviceSlug": "waterproofing",
    "title": "Balcony Leaking Into the Unit Below (Condo)",
    "symptom": "Your downstairs neighbour reports water dripping from their ceiling on the same footprint as your balcony above.",
    "costRange": "RM 800–RM 6,500+ depending on membrane state",
    "i18n": {
      "ms": {
        "title": "Balkoni Bocor ke Unit Bawah (Kondominium)",
        "symptom": "Your downstairs neighbour reports water dripping from their ceiling on the same footprint as your balcony above.",
        "costRange": "RM 800–RM 6,500+ bergantung kepada keadaan membran"
      },
      "zh": {
        "title": "公寓阳台漏水渗到楼下单位",
        "symptom": "Your downstairs neighbour reports water dripping from their ceiling on the same footprint as your balcony above.",
        "costRange": "RM 800–RM 6,500+，视防水膜状况而定"
      }
    }
  },
  {
    "slug": "concrete-slab-crack-leak",
    "serviceSlug": "waterproofing",
    "title": "Concrete Slab Cracks Leaking During Heavy Rain",
    "symptom": "Water appears on the ceiling only during heavy monsoon rains, tracing a specific crack line in the slab above.",
    "costRange": "RM 650–RM 3,800+ depending on crack length",
    "i18n": {
      "ms": {
        "title": "Retak Papak Konkrit Bocor Semasa Hujan Lebat",
        "symptom": "Water appears on the ceiling only during heavy monsoon rains, tracing a specific crack line in the slab above.",
        "costRange": "RM 650–RM 3,800+ bergantung kepada panjang retakan"
      },
      "zh": {
        "title": "混凝土楼板裂缝在暴雨时渗水",
        "symptom": "Water appears on the ceiling only during heavy monsoon rains, tracing a specific crack line in the slab above.",
        "costRange": "RM 650–RM 3,800+，视裂缝长度而定"
      }
    }
  },
  {
    "slug": "curtain-track-falling",
    "serviceSlug": "handyman",
    "title": "Curtain Track Coming Loose from the Ceiling",
    "symptom": "The curtain track is drooping, has visible screw holes pulling out of the ceiling, or has partially fallen.",
    "costRange": "RM 120–RM 380+ per window",
    "i18n": {
      "ms": {
        "title": "Trek Langsir Tercabut daripada Siling",
        "symptom": "The curtain track is drooping, has visible screw holes pulling out of the ceiling, or has partially fallen.",
        "costRange": "RM 120–RM 380+ setiap tingkap"
      },
      "zh": {
        "title": "窗帘轨道从天花板松脱",
        "symptom": "The curtain track is drooping, has visible screw holes pulling out of the ceiling, or has partially fallen.",
        "costRange": "每个窗户 RM 120–RM 380+"
      }
    }
  },
  {
    "slug": "door-hinge-sagging",
    "serviceSlug": "handyman",
    "title": "Sagging or Squeaking Door",
    "symptom": "Door drags on the floor, doesn't close flush, squeaks when opened, or the hinges show visible movement.",
    "costRange": "RM 150–RM 550+ per door",
    "i18n": {
      "ms": {
        "title": "Pintu Kendor atau Berbunyi",
        "symptom": "Door drags on the floor, doesn't close flush, squeaks when opened, or the hinges show visible movement.",
        "costRange": "RM 150–RM 550+ setiap pintu"
      },
      "zh": {
        "title": "门扇下垂或吱吱作响",
        "symptom": "Door drags on the floor, doesn't close flush, squeaks when opened, or the hinges show visible movement.",
        "costRange": "每扇门 RM 150–RM 550+"
      }
    }
  },
  {
    "slug": "old-condo-full-refurbishment",
    "serviceSlug": "house-renovation",
    "title": "Old Condo That Needs Full Refurbishment",
    "symptom": "You've bought or inherited a 15+ year old condo with tired paint, dated tiles, worn kitchen and old bathrooms.",
    "costRange": "RM 22,000–RM 180,000+ depending on unit size and scope",
    "i18n": {
      "ms": {
        "title": "Kondominium Lama Yang Perlu Diubahsuai Sepenuhnya",
        "symptom": "You've bought or inherited a 15+ year old condo with tired paint, dated tiles, worn kitchen and old bathrooms.",
        "costRange": "RM 22,000–RM 180,000+ bergantung kepada saiz unit dan skop"
      },
      "zh": {
        "title": "需要全面翻新的老公寓",
        "symptom": "You've bought or inherited a 15+ year old condo with tired paint, dated tiles, worn kitchen and old bathrooms.",
        "costRange": "RM 22,000–RM 180,000+，视单位面积和工程范围而定"
      }
    }
  },
  {
    "slug": "power-tripping-frequently",
    "serviceSlug": "electrical",
    "title": "Power Tripping Frequently in the House",
    "symptom": "The main breaker or an RCD trips several times a day, often when a specific appliance is turned on.",
    "costRange": "RM 180–RM 1,800+ depending on cause",
    "i18n": {
      "ms": {
        "title": "Elektrik Kerap Trip di Rumah",
        "symptom": "The main breaker or an RCD trips several times a day, often when a specific appliance is turned on.",
        "costRange": "RM 180–RM 1,800+ bergantung kepada punca"
      },
      "zh": {
        "title": "家中频繁跳闸",
        "symptom": "The main breaker or an RCD trips several times a day, often when a specific appliance is turned on.",
        "costRange": "RM 180–RM 1,800+，视原因而定"
      }
    }
  },
  {
    "slug": "water-heater-cold",
    "serviceSlug": "water-heater",
    "title": "Water Heater Not Heating (Cold Water Only)",
    "symptom": "The shower runs cold even after turning on the water heater — no warm output at all.",
    "costRange": "RM 180–RM 850+ depending on fault",
    "i18n": {
      "ms": {
        "title": "Pemanas Air Tidak Panas (Air Sejuk Sahaja)",
        "symptom": "The shower runs cold even after turning on the water heater — no warm output at all.",
        "costRange": "RM 180–RM 850+ bergantung kepada kerosakan"
      },
      "zh": {
        "title": "热水器不加热（只有冷水）",
        "symptom": "The shower runs cold even after turning on the water heater — no warm output at all.",
        "costRange": "RM 180–RM 850+，视故障而定"
      }
    }
  },
  {
    "slug": "loose-hollow-tiles",
    "serviceSlug": "tiling",
    "title": "Loose or Hollow-Sounding Floor Tiles",
    "symptom": "Tiles crack, pop up, or sound hollow when tapped with a coin because the bond to the substrate has failed.",
    "costRange": "RM 350–RM 2,800+ depending on tile count and access",
    "i18n": {
      "ms": {
        "title": "Jubin Lantai Longgar atau Berbunyi Kosong",
        "symptom": "Tiles crack, pop up, or sound hollow when tapped with a coin because the bond to the substrate has failed.",
        "costRange": "RM 350–RM 2,800+ bergantung kepada bilangan jubin dan akses"
      },
      "zh": {
        "title": "地砖松动或敲击有空鼓声",
        "symptom": "Tiles crack, pop up, or sound hollow when tapped with a coin because the bond to the substrate has failed.",
        "costRange": "RM 350–RM 2,800+，视瓷砖数量和施工条件而定"
      }
    }
  },
  {
    "slug": "cracked-tile-grout",
    "serviceSlug": "tiling",
    "title": "Cracked or Discoloured Tile Grout",
    "symptom": "Grout lines between tiles are cracking, crumbling, or turning grey/black with mould.",
    "costRange": "RM 250–RM 1,800+ depending on room size",
    "i18n": {
      "ms": {
        "title": "Grout Jubin Retak atau Berubah Warna",
        "symptom": "Grout lines between tiles are cracking, crumbling, or turning grey/black with mould.",
        "costRange": "RM 250–RM 1,800+ bergantung kepada saiz bilik"
      },
      "zh": {
        "title": "瓷砖填缝剂开裂或变色",
        "symptom": "Grout lines between tiles are cracking, crumbling, or turning grey/black with mould.",
        "costRange": "RM 250–RM 1,800+，视房间大小而定"
      }
    }
  },
  {
    "slug": "plaster-ceiling-hairline-crack",
    "serviceSlug": "plaster-ceiling",
    "title": "Hairline Cracks in Plaster Ceiling",
    "symptom": "Fine spider-web cracks appear across the plaster ceiling surface, often near joints or corners.",
    "costRange": "RM 300–RM 1,800+ depending on ceiling area",
    "i18n": {
      "ms": {
        "title": "Retak Rambut pada Siling Plaster",
        "symptom": "Fine spider-web cracks appear across the plaster ceiling surface, often near joints or corners.",
        "costRange": "RM 300–RM 1,800+ bergantung kepada keluasan siling"
      },
      "zh": {
        "title": "石膏天花板出现发丝裂纹",
        "symptom": "Fine spider-web cracks appear across the plaster ceiling surface, often near joints or corners.",
        "costRange": "RM 300–RM 1,800+，视天花板面积而定"
      }
    }
  },
  {
    "slug": "uneven-wall-surface-skim",
    "serviceSlug": "skim-coat",
    "title": "Uneven or Bumpy Wall Surface",
    "symptom": "Walls have visible bumps, dips, plaster ridges, or old paint texture that shows through the new topcoat.",
    "costRange": "RM 5–RM 12 per sq ft (skim-coat)",
    "i18n": {
      "ms": {
        "title": "Permukaan Dinding Tidak Rata atau Beralun",
        "symptom": "Walls have visible bumps, dips, plaster ridges, or old paint texture that shows through the new topcoat.",
        "costRange": "RM 5–RM 12 setiap kaki persegi (skim coat)"
      },
      "zh": {
        "title": "墙面不平整或凹凸不平",
        "symptom": "Walls have visible bumps, dips, plaster ridges, or old paint texture that shows through the new topcoat.",
        "costRange": "每平方英尺 RM 5–RM 12（批灰）"
      }
    }
  },
  {
    "slug": "vinyl-flooring-lifting-edges",
    "serviceSlug": "flooring",
    "title": "Vinyl or SPC Flooring Lifting at the Edges",
    "symptom": "Vinyl or SPC planks curl, lift, or gap at the edges — usually near doors, windows, or wet areas.",
    "costRange": "RM 250–RM 1,800+ depending on plank count",
    "i18n": {
      "ms": {
        "title": "Lantai Vinyl atau SPC Terangkat di Tepi",
        "symptom": "Vinyl or SPC planks curl, lift, or gap at the edges — usually near doors, windows, or wet areas.",
        "costRange": "RM 250–RM 1,800+ bergantung kepada bilangan plank"
      },
      "zh": {
        "title": "乙烯基或 SPC 地板边缘翘起",
        "symptom": "Vinyl or SPC planks curl, lift, or gap at the edges — usually near doors, windows, or wet areas.",
        "costRange": "RM 250–RM 1,800+，视地板板块数量而定"
      }
    }
  },
  {
    "slug": "cracked-roof-tiles",
    "serviceSlug": "roof-repair",
    "title": "Cracked or Displaced Roof Tiles",
    "symptom": "Roof tiles visibly cracked, slipped, or displaced — often first noticed after a heavy storm.",
    "costRange": "RM 380–RM 1,800+ depending on tile count and access",
    "i18n": {
      "ms": {
        "title": "Jubin Bumbung Retak atau Teralih",
        "symptom": "Roof tiles visibly cracked, slipped, or displaced — often first noticed after a heavy storm.",
        "costRange": "RM 380–RM 1,800+ bergantung kepada bilangan jubin dan akses"
      },
      "zh": {
        "title": "屋顶瓦片开裂或移位",
        "symptom": "Roof tiles visibly cracked, slipped, or displaced — often first noticed after a heavy storm.",
        "costRange": "RM 380–RM 1,800+，视瓦片数量和施工条件而定"
      }
    }
  },
  {
    "slug": "cabinet-door-sagging",
    "serviceSlug": "kitchen-cabinet",
    "title": "Kitchen Cabinet Doors Sagging or Misaligned",
    "symptom": "Cabinet doors don't close flush, sag on one side, or rub against neighbouring doors.",
    "costRange": "RM 150–RM 850+ depending on door count",
    "i18n": {
      "ms": {
        "title": "Pintu Kabinet Dapur Kendor atau Senget",
        "symptom": "Cabinet doors don't close flush, sag on one side, or rub against neighbouring doors.",
        "costRange": "RM 150–RM 850+ bergantung kepada bilangan pintu"
      },
      "zh": {
        "title": "厨房柜门下垂或错位",
        "symptom": "Cabinet doors don't close flush, sag on one side, or rub against neighbouring doors.",
        "costRange": "RM 150–RM 850+，视门板数量而定"
      }
    }
  },
  {
    "slug": "wardrobe-door-jamming",
    "serviceSlug": "carpentry",
    "title": "Wardrobe Door Jamming or Not Closing",
    "symptom": "Sliding wardrobe doors stick on the track, or hinged doors won't shut without pushing hard.",
    "costRange": "RM 180–RM 650+ depending on door type",
    "i18n": {
      "ms": {
        "title": "Pintu Almari Tersangkut atau Tidak Tertutup",
        "symptom": "Sliding wardrobe doors stick on the track, or hinged doors won't shut without pushing hard.",
        "costRange": "RM 180–RM 650+ bergantung kepada jenis pintu"
      },
      "zh": {
        "title": "衣柜门卡住或关不上",
        "symptom": "Sliding wardrobe doors stick on the track, or hinged doors won't shut without pushing hard.",
        "costRange": "RM 180–RM 650+，视门型而定"
      }
    }
  },
  {
    "slug": "digital-smart-lock-installation",
    "serviceSlug": "door",
    "title": "Digital / Smart Lock Installation on Existing Door",
    "symptom": "You bought a Samsung, Yale, Kaadas or similar smart lock and need it installed on your current door properly.",
    "costRange": "RM 250–RM 550+ per door",
    "i18n": {
      "ms": {
        "title": "Pemasangan Kunci Digital / Pintar pada Pintu Sedia Ada",
        "symptom": "You bought a Samsung, Yale, Kaadas or similar smart lock and need it installed on your current door properly.",
        "costRange": "RM 250–RM 550+ setiap pintu"
      },
      "zh": {
        "title": "在现有门上安装电子 / 智能门锁",
        "symptom": "You bought a Samsung, Yale, Kaadas or similar smart lock and need it installed on your current door properly.",
        "costRange": "每扇门 RM 250–RM 550+"
      }
    }
  },
  {
    "slug": "locked-out-of-house",
    "serviceSlug": "locksmith",
    "title": "Locked Out of Your House",
    "symptom": "You've locked your keys inside or lost them, and you can't get into your house.",
    "costRange": "RM 180–RM 550+ depending on lock type and time",
    "i18n": {
      "ms": {
        "title": "Terkunci di Luar Rumah",
        "symptom": "You've locked your keys inside or lost them, and you can't get into your house.",
        "costRange": "RM 180–RM 550+ bergantung kepada jenis kunci dan masa"
      },
      "zh": {
        "title": "被反锁在家门外",
        "symptom": "You've locked your keys inside or lost them, and you can't get into your house.",
        "costRange": "RM 180–RM 550+，视锁型和时段而定"
      }
    }
  },
  {
    "slug": "downlight-flickering",
    "serviceSlug": "lighting",
    "title": "LED Downlight Flickering or Dying Early",
    "symptom": "LED downlights flicker on/off, dim intermittently, or die months after installation.",
    "costRange": "RM 80–RM 320 per light",
    "i18n": {
      "ms": {
        "title": "Downlight LED Berkelip atau Cepat Rosak",
        "symptom": "LED downlights flicker on/off, dim intermittently, or die months after installation.",
        "costRange": "RM 80–RM 320 setiap lampu"
      },
      "zh": {
        "title": "LED 筒灯闪烁或过早损坏",
        "symptom": "LED downlights flicker on/off, dim intermittently, or die months after installation.",
        "costRange": "每个灯 RM 80–RM 320"
      }
    }
  },
  {
    "slug": "shower-screen-water-leak",
    "serviceSlug": "glass-aluminium",
    "title": "Shower Screen Leaking Water onto the Floor",
    "symptom": "Water pools outside the shower screen after every use — from either the corner joint, bottom seal, or hinge line.",
    "costRange": "RM 180–RM 850+ depending on screen size",
    "i18n": {
      "ms": {
        "title": "Skrin Mandian Bocor ke Lantai",
        "symptom": "Water pools outside the shower screen after every use — from either the corner joint, bottom seal, or hinge line.",
        "costRange": "RM 180–RM 850+ bergantung kepada saiz skrin"
      },
      "zh": {
        "title": "淋浴隔断漏水到地板",
        "symptom": "Water pools outside the shower screen after every use — from either the corner joint, bottom seal, or hinge line.",
        "costRange": "RM 180–RM 850+，视隔断尺寸而定"
      }
    }
  },
  {
    "slug": "stubborn-bathroom-limescale",
    "serviceSlug": "cleaning",
    "title": "Stubborn Bathroom Limescale and Water Stains",
    "symptom": "White chalky deposits and hard-water stains build up on shower glass, taps and tiles that regular cleaning won't remove.",
    "costRange": "RM 180–RM 550+ per bathroom",
    "i18n": {
      "ms": {
        "title": "Karat Kapur dan Kesan Air Degil di Bilik Air",
        "symptom": "White chalky deposits and hard-water stains build up on shower glass, taps and tiles that regular cleaning won't remove.",
        "costRange": "RM 180–RM 550+ setiap bilik air"
      },
      "zh": {
        "title": "浴室顽固水垢和水渍",
        "symptom": "White chalky deposits and hard-water stains build up on shower glass, taps and tiles that regular cleaning won't remove.",
        "costRange": "每间浴室 RM 180–RM 550+"
      }
    }
  },
  {
    "slug": "move-out-condo-deep-clean",
    "serviceSlug": "deep-cleaning",
    "title": "Move-Out Condo Deep Cleaning",
    "symptom": "You're moving out and need the condo cleaned to a standard the landlord/agent will accept for your deposit refund.",
    "costRange": "RM 420–RM 1,800+ depending on unit size",
    "i18n": {
      "ms": {
        "title": "Pembersihan Mendalam Kondominium Sebelum Berpindah",
        "symptom": "You're moving out and need the condo cleaned to a standard the landlord/agent will accept for your deposit refund.",
        "costRange": "RM 420–RM 1,800+ bergantung kepada saiz unit"
      },
      "zh": {
        "title": "公寓退租深度清洁",
        "symptom": "You're moving out and need the condo cleaned to a standard the landlord/agent will accept for your deposit refund.",
        "costRange": "RM 420–RM 1,800+，视单位面积而定"
      }
    }
  },
  {
    "slug": "cement-splatter-tile-clean",
    "serviceSlug": "post-renovation-cleaning",
    "title": "Cement Splatter and Dust After Renovation",
    "symptom": "Renovation is complete but cement/paint splatter, silicone residue and construction dust are everywhere.",
    "costRange": "RM 650–RM 3,200+ depending on unit size",
    "i18n": {
      "ms": {
        "title": "Percikan Simen dan Debu Selepas Pengubahsuaian",
        "symptom": "Renovation is complete but cement/paint splatter, silicone residue and construction dust are everywhere.",
        "costRange": "RM 650–RM 3,200+ bergantung kepada saiz unit"
      },
      "zh": {
        "title": "装修后的水泥溅渍和粉尘",
        "symptom": "Renovation is complete but cement/paint splatter, silicone residue and construction dust are everywhere.",
        "costRange": "RM 650–RM 3,200+，视单位面积而定"
      }
    }
  },
  {
    "slug": "cctv-not-recording-storage-full",
    "serviceSlug": "cctv",
    "title": "CCTV Not Recording or Showing Blank Feed",
    "symptom": "Your CCTV cameras show no live feed, are stuck on a static image, or the DVR/NVR won't play back recordings.",
    "costRange": "RM 180–RM 850+ depending on system fault",
    "i18n": {
      "ms": {
        "title": "CCTV Tidak Merakam atau Paparan Kosong",
        "symptom": "Your CCTV cameras show no live feed, are stuck on a static image, or the DVR/NVR won't play back recordings.",
        "costRange": "RM 180–RM 850+ bergantung kepada kerosakan sistem"
      },
      "zh": {
        "title": "CCTV 无法录像或画面空白",
        "symptom": "Your CCTV cameras show no live feed, are stuck on a static image, or the DVR/NVR won't play back recordings.",
        "costRange": "RM 180–RM 850+，视系统故障而定"
      }
    }
  },
  {
    "slug": "autogate-remote-not-working",
    "serviceSlug": "autogate",
    "title": "Auto Gate Remote Not Working",
    "symptom": "The auto gate remote no longer opens the gate, or works only intermittently from a very short distance.",
    "costRange": "RM 120–RM 550+ depending on cause",
    "i18n": {
      "ms": {
        "title": "Alat Kawalan Jauh Pagar Auto Tidak Berfungsi",
        "symptom": "The auto gate remote no longer opens the gate, or works only intermittently from a very short distance.",
        "costRange": "RM 120–RM 550+ bergantung kepada punca"
      },
      "zh": {
        "title": "自动门遥控器失灵",
        "symptom": "The auto gate remote no longer opens the gate, or works only intermittently from a very short distance.",
        "costRange": "RM 120–RM 550+，视原因而定"
      }
    }
  },
  {
    "slug": "loose-metal-gate-hinges",
    "serviceSlug": "welding",
    "title": "Loose or Sagging Metal Gate Hinges",
    "symptom": "Your metal gate sags, drags on the ground, or the hinges are visibly loose or corroded.",
    "costRange": "RM 250–RM 1,200+ depending on gate size",
    "i18n": {
      "ms": {
        "title": "Engsel Pagar Besi Longgar atau Kendor",
        "symptom": "Your metal gate sags, drags on the ground, or the hinges are visibly loose or corroded.",
        "costRange": "RM 250–RM 1,200+ bergantung kepada saiz pagar"
      },
      "zh": {
        "title": "金属大门铰链松动或下垂",
        "symptom": "Your metal gate sags, drags on the ground, or the hinges are visibly loose or corroded.",
        "costRange": "RM 250–RM 1,200+，视大门尺寸而定"
      }
    }
  },
  {
    "slug": "stuck-sliding-window",
    "serviceSlug": "window-repair",
    "title": "Sliding Window Stuck or Jamming",
    "symptom": "Aluminium sliding windows won't slide, need excessive force, or come off the track when moved.",
    "costRange": "RM 180–RM 550+ per window",
    "i18n": {
      "ms": {
        "title": "Tingkap Gelangsar Tersangkut atau Seret",
        "symptom": "Aluminium sliding windows won't slide, need excessive force, or come off the track when moved.",
        "costRange": "RM 180–RM 550+ setiap tingkap"
      },
      "zh": {
        "title": "推拉窗卡住或滑动不畅",
        "symptom": "Aluminium sliding windows won't slide, need excessive force, or come off the track when moved.",
        "costRange": "每扇窗 RM 180–RM 550+"
      }
    }
  },
  {
    "slug": "aircon-not-cold",
    "serviceSlug": "aircon",
    "title": "Aircon Not Cold (Warm Air Blowing)",
    "symptom": "The aircon runs but blows warm or only slightly cool air, so the room never reaches the set temperature.",
    "costRange": "RM 129–RM 455 depending on the cause",
    "i18n": {
      "ms": {
        "title": "Aircond Tidak Sejuk (Hembusan Udara Panas)",
        "symptom": "The aircon runs but blows warm or only slightly cool air, so the room never reaches the set temperature.",
        "costRange": "RM 129–RM 455 bergantung kepada punca"
      },
      "zh": {
        "title": "空调不冷（吹出热风）",
        "symptom": "The aircon runs but blows warm or only slightly cool air, so the room never reaches the set temperature.",
        "costRange": "RM 129–RM 455，视原因而定"
      }
    }
  },
  {
    "slug": "aircon-water-leaking",
    "serviceSlug": "aircon",
    "title": "Aircon Water Leaking (Indoor Unit Dripping)",
    "symptom": "Water drips from the indoor unit or runs down the wall, usually from a blocked drain or a tilted unit.",
    "costRange": "RM 129–RM 455 depending on the cause",
    "i18n": {
      "ms": {
        "title": "Aircond Bocor Air (Unit Dalaman Menitis)",
        "symptom": "Water drips from the indoor unit or runs down the wall, usually from a blocked drain or a tilted unit.",
        "costRange": "RM 129–RM 455 bergantung kepada punca"
      },
      "zh": {
        "title": "空调漏水（室内机滴水）",
        "symptom": "Water drips from the indoor unit or runs down the wall, usually from a blocked drain or a tilted unit.",
        "costRange": "RM 129–RM 455，视原因而定"
      }
    }
  },
  {
    "slug": "aircon-making-noise",
    "serviceSlug": "aircon",
    "title": "Aircon Making Noise (Rattling, Buzzing, Grinding)",
    "symptom": "The indoor or outdoor unit makes rattling, buzzing, humming or grinding noises during operation.",
    "costRange": "RM 195–RM 455 depending on the faulty part",
    "i18n": {
      "ms": {
        "title": "Aircond Berbunyi Bising (Bergetar, Berdengung, Mengisar)",
        "symptom": "The indoor or outdoor unit makes rattling, buzzing, humming or grinding noises during operation.",
        "costRange": "RM 195–RM 455 bergantung kepada bahagian rosak"
      },
      "zh": {
        "title": "空调有噪音（咔嗒、嗡嗡、摩擦声）",
        "symptom": "The indoor or outdoor unit makes rattling, buzzing, humming or grinding noises during operation.",
        "costRange": "RM 195–RM 455，视故障部件而定"
      }
    }
  },
  {
    "slug": "aircon-bad-smell",
    "serviceSlug": "aircon",
    "title": "Aircon Bad Smell (Mouldy or Musty Odour)",
    "symptom": "The aircon blows a musty, mouldy or sour smell into the room, especially when it first starts.",
    "costRange": "RM 156–RM 455 depending on the treatment",
    "i18n": {
      "ms": {
        "title": "Aircond Berbau Busuk (Bau Kulat atau Apak)",
        "symptom": "The aircon blows a musty, mouldy or sour smell into the room, especially when it first starts.",
        "costRange": "RM 156–RM 455 bergantung kepada rawatan"
      },
      "zh": {
        "title": "空调有异味（霉味或发酸味）",
        "symptom": "The aircon blows a musty, mouldy or sour smell into the room, especially when it first starts.",
        "costRange": "RM 156–RM 455，视处理方式而定"
      }
    }
  },
  {
    "slug": "aircon-weak-airflow",
    "serviceSlug": "aircon",
    "title": "Aircon Weak Airflow (Not Blowing Strong Enough)",
    "symptom": "The aircon cools but the airflow is weak, so the room stays warm even at the highest fan speed.",
    "costRange": "RM 129–RM 455 depending on the cause",
    "i18n": {
      "ms": {
        "title": "Aliran Udara Aircond Lemah (Tidak Hembus Kuat)",
        "symptom": "The aircon cools but the airflow is weak, so the room stays warm even at the highest fan speed.",
        "costRange": "RM 129–RM 455 bergantung kepada punca"
      },
      "zh": {
        "title": "空调风量小（出风无力）",
        "symptom": "The aircon cools but the airflow is weak, so the room stays warm even at the highest fan speed.",
        "costRange": "RM 129–RM 455，视原因而定"
      }
    }
  },
  {
    "slug": "aircon-not-turning-on",
    "serviceSlug": "aircon",
    "title": "Aircon Not Turning On",
    "symptom": "The aircon does not respond to the remote or the power button, or it switches off by itself shortly after starting.",
    "costRange": "RM 114–RM 455 depending on the fault",
    "i18n": {
      "ms": {
        "title": "Aircond Tidak Boleh Dihidupkan",
        "symptom": "The aircon does not respond to the remote or the power button, or it switches off by itself shortly after starting.",
        "costRange": "RM 114–RM 455 bergantung kepada kerosakan"
      },
      "zh": {
        "title": "空调无法开机",
        "symptom": "The aircon does not respond to the remote or the power button, or it switches off by itself shortly after starting.",
        "costRange": "RM 114–RM 455，视故障而定"
      }
    }
  },
  {
    "slug": "aircon-tripping-mcb",
    "serviceSlug": "aircon",
    "title": "Aircon Tripping MCB / Circuit Breaker",
    "symptom": "The aircon trips the MCB or RCCB circuit breaker whenever it starts, cutting power to the room.",
    "costRange": "RM 195–RM 1,040 depending on the fault",
    "i18n": {
      "ms": {
        "title": "Aircond Menyebabkan MCB / Breaker Trip",
        "symptom": "The aircon trips the MCB or RCCB circuit breaker whenever it starts, cutting power to the room.",
        "costRange": "RM 195–RM 1,040 bergantung kepada kerosakan"
      },
      "zh": {
        "title": "空调导致漏电开关 / 断路器跳闸",
        "symptom": "The aircon trips the MCB or RCCB circuit breaker whenever it starts, cutting power to the room.",
        "costRange": "RM 195–RM 1,040，视故障而定"
      }
    }
  },
  {
    "slug": "ice-forming-on-aircon",
    "serviceSlug": "aircon",
    "title": "Ice Forming on Aircon (Frozen Coil or Pipes)",
    "symptom": "Frost or ice builds up on the evaporator coil or the copper pipes, and the unit stops cooling properly.",
    "costRange": "RM 129–RM 455 depending on the cause",
    "i18n": {
      "ms": {
        "title": "Ais Terbentuk pada Aircond (Gegelung atau Paip Beku)",
        "symptom": "Frost or ice builds up on the evaporator coil or the copper pipes, and the unit stops cooling properly.",
        "costRange": "RM 129–RM 455 bergantung kepada punca"
      },
      "zh": {
        "title": "空调结冰（蒸发器或管道结霜）",
        "symptom": "Frost or ice builds up on the evaporator coil or the copper pipes, and the unit stops cooling properly.",
        "costRange": "RM 129–RM 455，视原因而定"
      }
    }
  },
  {
    "slug": "aircon-remote-display-issue",
    "serviceSlug": "aircon",
    "title": "Aircon Remote or Display Not Working",
    "symptom": "The remote control does not respond, or the unit's display shows error codes, flickers or goes blank.",
    "costRange": "RM 114–RM 455 depending on the fault",
    "i18n": {
      "ms": {
        "title": "Remote atau Paparan Aircond Tidak Berfungsi",
        "symptom": "The remote control does not respond, or the unit's display shows error codes, flickers or goes blank.",
        "costRange": "RM 114–RM 455 bergantung kepada kerosakan"
      },
      "zh": {
        "title": "空调遥控器或显示屏不工作",
        "symptom": "The remote control does not respond, or the unit's display shows error codes, flickers or goes blank.",
        "costRange": "RM 114–RM 455，视故障而定"
      }
    }
  }
];

export function getLocalizedProblemNav(item: ProblemNavItem, locale: "en" | "ms" | "zh"): ProblemNavItem {
  if (locale === "en") return item;
  const override = item.i18n?.[locale];
  if (!override) return item;
  return {
    ...item,
    title: override.title || item.title,
    symptom: override.symptom || item.symptom,
    costRange: override.costRange || item.costRange,
  };
}
