// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe quote/pricing catalog: the sub-service name, price and blurb that
// the booking form and the localised pricing page render, and nothing else.
// Importing `config/services-data.ts` from a client component ships the entire
// content registry to the browser; import this instead.

export type QuoteCatalogSubService = { name: string; price: string; desc: string };
export type QuoteCatalogEntry = {
  slug: string;
  title: string;
  startPrice: string;
  tagline: string;
  warranty: string;
  subServices: QuoteCatalogSubService[];
  i18n?: Partial<Record<"ms" | "zh", {
    title: string;
    tagline: string;
    warranty: string;
    subServices: QuoteCatalogSubService[];
  }>>;
};

export const quoteCatalogBySlug: Record<string, QuoteCatalogEntry> = {
  "painting": {
    "slug": "painting",
    "title": "House Painting Services",
    "startPrice": "RM 450",
    "tagline": "Interior, exterior and wall repainting for homes, offices and shops across KL & Selangor, with surface preparation, floor and furniture protection, and clean handover. From RM 450.",
    "warranty": "1-Year Paint Peeling & Craftsmanship Guarantee",
    "subServices": [
      {
        "name": "Interior House Painting",
        "price": "From RM 450 / room",
        "desc": "Premium interior wall painting with low-odor, low-VOC washable paint."
      },
      {
        "name": "Exterior House Painting",
        "price": "From RM 2,200",
        "desc": "Weatherproof, anti-fungal, and UV-resistant exterior coatings for ultimate protection."
      },
      {
        "name": "Commercial & Office Painting",
        "price": "On Quote",
        "desc": "Corporate office layouts, shopfronts, and retail spaces painted on tight schedules with minimal business disruption."
      },
      {
        "name": "Wall Crack & Moisture Repair",
        "price": "From RM 180",
        "desc": "Sanding, skimming, structural crack filling, and applying premium moisture sealer primers."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Mengecat Rumah",
        "tagline": "Pengecatan interior & eksterior profesional untuk ruang kediaman dan komersial. Kemasan licin, cat premium, perlindungan tanpa kotor. Dari RM 450.",
        "warranty": "Jaminan Pengelupasan Cat & Kerja 1 Tahun",
        "subServices": [
          {
            "name": "Pengecatan Rumah Interior",
            "price": "Dari RM 450 / bilik",
            "desc": "Pengecatan dinding interior premium dengan cat boleh dicuci berbau rendah, VOC rendah."
          },
          {
            "name": "Pengecatan Rumah Eksterior",
            "price": "Dari RM 2,200",
            "desc": "Salutan eksterior tahan cuaca, anti-kulat, dan tahan UV untuk perlindungan optimum."
          },
          {
            "name": "Pengecatan Komersial & Pejabat",
            "price": "Atas Sebut Harga",
            "desc": "Susun atur pejabat korporat, kedai depan, dan ruang runcit dicat mengikut jadual ketat dengan gangguan perniagaan minimum."
          },
          {
            "name": "Pembaikan Retak & Lembapan Dinding",
            "price": "Dari RM 180",
            "desc": "Pengamplasan, pengapan, pengisian retak struktur, dan penyapuan primer penyekat lembapan premium."
          }
        ]
      },
      "zh": {
        "title": "房屋油漆服务",
        "tagline": "为住宅和商业空间提供专业室内外油漆服务。光滑饰面，优质涂料，全程无尘保护。从 RM 450 起。",
        "warranty": "1 年油漆剥落与工艺保修",
        "subServices": [
          {
            "name": "室内房屋油漆",
            "price": "从 RM 450 / 房间起",
            "desc": "使用低气味、低 VOC 可水洗涂料进行优质室内墙面油漆。"
          },
          {
            "name": "室外房屋油漆",
            "price": "从 RM 2,200 起",
            "desc": "防风雨、防霉菌、抗紫外线的外墙涂层，提供终极保护。"
          },
          {
            "name": "商业与办公室油漆",
            "price": "依报价",
            "desc": "在紧凑的时间表内为企业办公室布局、店面和零售空间上漆，将业务干扰降至最低。"
          },
          {
            "name": "墙面裂缝与防潮修复",
            "price": "从 RM 180 起",
            "desc": "打磨、批灰、结构性裂缝填补，以及涂抹优质防潮密封底漆。"
          }
        ]
      }
    }
  },
  "plumbing": {
    "slug": "plumbing",
    "title": "Plumbing & Leak Repair Services",
    "startPrice": "RM 150",
    "tagline": "Plumbing and leak repair for pipes, taps, toilets, drains, water heaters and pumps across KL & Selangor, with the scope confirmed before work. From RM 150.",
    "warranty": "30-Day Joint Seal & Workmanship Warranty",
    "subServices": [
      {
        "name": "Water Leakage Diagnosis & Repair",
        "price": "From RM 220",
        "desc": "Detection of hidden pipe leaks behind walls or underground, followed by precise repair."
      },
      {
        "name": "Toilet, Tap & Sink Installation",
        "price": "From RM 150",
        "desc": "Fitting new toilet bowls, modern kitchen faucets, basins, and heavy-duty sink plumbing."
      },
      {
        "name": "Drain Unclogging & Cleaning",
        "price": "From RM 180",
        "desc": "Clearing stubborn hair, grease, and debris blockages in kitchen drains, floor traps, and toilets."
      },
      {
        "name": "Water Heater & Pump Installation",
        "price": "From RM 180",
        "desc": "Setting up modern instant/storage water heaters and home water pressure booster pumps."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Paip & Baiki Kebocoran",
        "tagline": "Pembaikan paip yang boleh dipercayai, pembaikan kebocoran air, dan pemasangan lekapan baru. Alat ganti bertauliah SIRIM, respons pantas. Dari RM 150.",
        "warranty": "Jaminan Pengedap Sendi & Kerja 30 Hari",
        "subServices": [
          {
            "name": "Diagnosis & Pembaikan Kebocoran Air",
            "price": "Dari RM 220",
            "desc": "Pengesanan kebocoran paip tersembunyi di sebalik dinding atau bawah tanah, diikuti pembaikan tepat."
          },
          {
            "name": "Pemasangan Tandas, Paip Air & Singki",
            "price": "Dari RM 150",
            "desc": "Memasang mangkuk tandas baru, paip air dapur moden, besen, dan paip singki tugas berat."
          },
          {
            "name": "Penyahsumbatan & Pembersihan Saliran",
            "price": "Dari RM 180",
            "desc": "Membersihkan sumbatan rambut, minyak, dan serpihan yang degil di saliran dapur, perangkap lantai, dan tandas."
          },
          {
            "name": "Pemasangan Pemanas Air & Pam",
            "price": "Dari RM 180",
            "desc": "Menyediakan pemanas air segera/simpanan moden dan pam penambah tekanan air rumah."
          }
        ]
      },
      "zh": {
        "title": "水管与漏水维修服务",
        "tagline": "可靠的水管维修、漏水修复与新洁具安装。SIRIM 认证配件，快速响应。从 RM 150 起。",
        "warranty": "30 天接头密封与工艺保修",
        "subServices": [
          {
            "name": "漏水诊断与修复",
            "price": "从 RM 220 起",
            "desc": "检测墙内或地下隐藏的管道漏水，随后进行精确修复。"
          },
          {
            "name": "马桶、水龙头与水槽安装",
            "price": "从 RM 150 起",
            "desc": "安装新马桶、现代厨房水龙头、洗手盆与重型水槽管道。"
          },
          {
            "name": "疏通与清洁排水管",
            "price": "从 RM 180 起",
            "desc": "清除厨房排水管、地漏与马桶中顽固的毛发、油脂与杂物堵塞。"
          },
          {
            "name": "热水器与水泵安装",
            "price": "从 RM 180 起",
            "desc": "安装现代即热式/储水式热水器与家用增压泵。"
          }
        ]
      }
    }
  },
  "ceiling": {
    "slug": "ceiling",
    "title": "Ceiling & Partition Services",
    "startPrice": "RM 220",
    "tagline": "Plaster ceiling installation and repair, gypsum partitions, cornices, L-box features and skim finishing for homes and commercial spaces across KL & Selangor. From RM 220.",
    "warranty": "90-Day Structural Sagging & Crack-Free Warranty",
    "subServices": [
      {
        "name": "Water-Damaged Ceiling Repair",
        "price": "From RM 220",
        "desc": "Removing moldy, rotting plasterboard, addressing the leak source, and fitting a clean moisture-resistant panel."
      },
      {
        "name": "Plaster Ceiling Installation",
        "price": "From RM 10 / sq ft",
        "desc": "Elegant flat, tiered, or L-box plaster ceiling setups with custom cutout channels for downlights."
      },
      {
        "name": "Gypsum Board Partition Wall",
        "price": "From RM 11 / sq ft",
        "desc": "Durable, paint-ready partition walls to divide office rooms, bedrooms, or storage areas."
      },
      {
        "name": "Cornice & L-Box Concealed Light Trough",
        "price": "On Quote",
        "desc": "Custom decorative moldings and ambient indirect LED lighting plaster designs."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Siling & Partition",
        "tagline": "Pembaikan siling plaster profesional, partition papan gypsum, pemasangan kornis, dan pengedapan retak dinding estetik. Dari RM 220.",
        "warranty": "Jaminan Melendut Struktur & Bebas Retak 90 Hari",
        "subServices": [
          {
            "name": "Pembaikan Siling Rosak Air",
            "price": "Dari RM 220",
            "desc": "Menanggalkan papan plaster berkulat dan reput, menangani punca kebocoran, dan memasang panel tahan lembapan yang bersih."
          },
          {
            "name": "Pemasangan Siling Plaster",
            "price": "Dari RM 10 / kaki persegi",
            "desc": "Persediaan siling plaster rata, bertingkat, atau L-box yang anggun dengan saluran potongan khas untuk downlight."
          },
          {
            "name": "Dinding Partition Papan Gypsum",
            "price": "Dari RM 11 / kaki persegi",
            "desc": "Dinding partition tahan lasak, sedia dicat untuk membahagikan bilik pejabat, bilik tidur, atau kawasan simpanan."
          },
          {
            "name": "Kornis & Lekuk Lampu Tersembunyi L-Box",
            "price": "Atas Sebut Harga",
            "desc": "Moulding hiasan khas dan reka bentuk plaster pencahayaan LED tidak langsung ambien."
          }
        ]
      },
      "zh": {
        "title": "天花板与隔墙服务",
        "tagline": "专业石膏天花板维修、石膏板隔墙、线板安装以及美观的墙面裂缝密封。从 RM 220 起。",
        "warranty": "90 天结构防下垂与无裂缝保修",
        "subServices": [
          {
            "name": "水损天花板维修",
            "price": "从 RM 220 起",
            "desc": "拆除发霉腐烂的石膏板，处理漏水源头，并安装干净的防潮板材。"
          },
          {
            "name": "石膏天花板安装",
            "price": "从 RM 10 / 平方英尺起",
            "desc": "优雅的平面、分层或 L 型盒石膏天花板设计，配合定制切口用于安装筒灯。"
          },
          {
            "name": "石膏板隔墙",
            "price": "从 RM 11 / 平方英尺起",
            "desc": "耐用、可直接上漆的隔墙，用于划分办公室、卧室或储物区域。"
          },
          {
            "name": "线板与 L 型盒暗藏灯槽",
            "price": "依报价",
            "desc": "定制装饰线板与氛围间接 LED 照明石膏设计。"
          }
        ]
      }
    }
  },
  "waterproofing": {
    "slug": "waterproofing",
    "title": "Waterproofing & Leak Repair Services",
    "startPrice": "RM 300",
    "tagline": "Bathroom, roof, balcony and concrete waterproofing plus PU injection grouting for leaks across KL & Selangor, selected after assessing the cause. From RM 300.",
    "warranty": "Up to 5-Year Written Leak-Free Guarantee",
    "subServices": [
      {
        "name": "PU High-Pressure Injection Grouting",
        "price": "From RM 300 / point",
        "desc": "Smart non-destructive polyurethane injection to seal inter-floor concrete slab leaks."
      },
      {
        "name": "Bathroom & Wet Area Waterproofing",
        "price": "From RM 1,000",
        "desc": "Chemical waterproofing membrane application for showers, toilets, and wet commercial washrooms."
      },
      {
        "name": "Roof & Concrete Slab Waterproofing",
        "price": "On Quote",
        "desc": "Heavy-duty elastomeric UV-resistant acrylic or torch-on bituminous membranes for roof slabs and balconies."
      },
      {
        "name": "Wall Dampness & Efflorescence Repair",
        "price": "From RM 350",
        "desc": "Sanding off salt scaling, sanitizing mold, and applying commercial moisture-blocking barriers."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Kalis Air & Baiki Kebocoran",
        "tagline": "Kalis air profesional bilik air, bumbung, balkoni, dan slab konkrit. Grouting Poliuretana (PU), penghadang membran kimia. Dari RM 300.",
        "warranty": "Jaminan Bebas Bocor Bertulis Sehingga 5 Tahun",
        "subServices": [
          {
            "name": "Grouting Suntikan Tekanan Tinggi PU",
            "price": "Dari RM 300 / titik",
            "desc": "Suntikan poliuretana pintar yang tidak merosakkan untuk mengedap kebocoran slab konkrit antara tingkat."
          },
          {
            "name": "Kalis Air Bilik Air & Kawasan Basah",
            "price": "Dari RM 1,000",
            "desc": "Aplikasi membran kalis air kimia untuk pancuran, tandas, dan bilik mandi komersial basah."
          },
          {
            "name": "Kalis Air Bumbung & Slab Konkrit",
            "price": "Atas Sebut Harga",
            "desc": "Membran akrilik tahan UV elastomerik tugas berat atau bituminus torch-on untuk slab bumbung dan balkoni."
          },
          {
            "name": "Pembaikan Lembapan Dinding & Kesan Garam",
            "price": "Dari RM 350",
            "desc": "Mengamplas kerak garam, mensanitasi kulat, dan menyapu penghadang penyekat lembapan komersial."
          }
        ]
      },
      "zh": {
        "title": "防水与漏水维修服务",
        "tagline": "专业浴室、屋顶、阳台与混凝土板防水。聚氨酯（PU）灌浆，化学防水层。从 RM 300 起。",
        "warranty": "长达 5 年书面防漏保证",
        "subServices": [
          {
            "name": "PU 高压灌浆注射",
            "price": "从 RM 300 / 点起",
            "desc": "智能非破坏性聚氨酯注射，密封楼层间混凝土板漏水。"
          },
          {
            "name": "浴室与湿区防水",
            "price": "从 RM 1,000 起",
            "desc": "为淋浴间、卫生间与商业湿区洗手间涂抹化学防水层。"
          },
          {
            "name": "屋顶与混凝土板防水",
            "price": "依报价",
            "desc": "为屋顶板与阳台提供重型抗紫外线弹性丙烯酸或热熔沥青防水层。"
          },
          {
            "name": "墙面潮湿与盐析修复",
            "price": "从 RM 350 起",
            "desc": "打磨盐结晶、消毒霉菌，并涂抹商用防潮屏障。"
          }
        ]
      }
    }
  },
  "handyman": {
    "slug": "handyman",
    "title": "Handyman Services",
    "startPrice": "RM 100",
    "tagline": "TV mounting, door and lock repair, furniture assembly, curtain and shelf installation, cabinet adjustments and general maintenance across KL & Selangor. From RM 100.",
    "warranty": "30-Day Workmanship Safety Warranty",
    "subServices": [
      {
        "name": "Heavy TV Wall Mounting",
        "price": "From RM 150",
        "desc": "Safe, level wall-mounting of TVs up to 85\" on brick, concrete, or gypsum partition walls with hidden wire options."
      },
      {
        "name": "Door, Hinge & Lockset Repair",
        "price": "From RM 120",
        "desc": "Fixing sagging doors, replacing rusty hinges, and installing premium lever locks or smart digital locks."
      },
      {
        "name": "Furniture Assembly (IKEA/Taobao)",
        "price": "From RM 120",
        "desc": "Assembly of complex wardrobes, beds, display cabinets, office desks, and kitchen island carts."
      },
      {
        "name": "Curtains, Blinds & Shelves Hanging",
        "price": "From RM 100",
        "desc": "Secure wall mounting of heavy curtain tracks, roman blinds, floating shelves, mirrors, and picture frames."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Handyman",
        "tagline": "Pembaikan pintu & kunci profesional, pemasangan TV, pemasangan perabot, trek langsir, pelarasan kabinet, dan penyelenggaraan pejabat am. Dari RM 100.",
        "warranty": "Jaminan Keselamatan Kerja 30 Hari",
        "subServices": [
          {
            "name": "Pemasangan Dinding TV Berat",
            "price": "Dari RM 150",
            "desc": "Pemasangan dinding selamat dan rata untuk TV sehingga 85\" pada dinding bata, konkrit, atau partition gypsum dengan pilihan wayar tersembunyi."
          },
          {
            "name": "Pembaikan Pintu, Engsel & Kunci",
            "price": "Dari RM 120",
            "desc": "Membaiki pintu melendut, menggantikan engsel berkarat, dan memasang kunci tuil premium atau kunci digital pintar."
          },
          {
            "name": "Pemasangan Perabot (IKEA/Taobao)",
            "price": "Dari RM 120",
            "desc": "Pemasangan almari kompleks, katil, kabinet paparan, meja pejabat, dan troli pulau dapur."
          },
          {
            "name": "Penggantungan Langsir, Bidai & Rak",
            "price": "Dari RM 100",
            "desc": "Pemasangan dinding selamat untuk trek langsir berat, bidai roman, rak terapung, cermin, dan bingkai gambar."
          }
        ]
      },
      "zh": {
        "title": "家居杂工服务",
        "tagline": "专业门锁维修、电视挂墙、家具组装、窗帘轨道、橱柜调整以及一般办公室维护。从 RM 100 起。",
        "warranty": "30 天工艺安全保修",
        "subServices": [
          {
            "name": "重型电视挂墙",
            "price": "从 RM 150 起",
            "desc": "在砖墙、混凝土墙或石膏隔墙上安全水平地安装最高 85 英寸的电视，可选隐藏走线。"
          },
          {
            "name": "门、铰链与锁具维修",
            "price": "从 RM 120 起",
            "desc": "修复下垂的门、更换生锈的铰链，并安装优质把手锁或智能数字锁。"
          },
          {
            "name": "家具组装（IKEA/淘宝）",
            "price": "从 RM 120 起",
            "desc": "组装复杂的衣柜、床架、展示柜、办公桌与厨房中岛推车。"
          },
          {
            "name": "窗帘、百叶窗与置物架安装",
            "price": "从 RM 100 起",
            "desc": "安全安装重型窗帘轨道、罗马帘、悬浮置物架、镜子与相框。"
          }
        ]
      }
    }
  },
  "house-renovation": {
    "slug": "house-renovation",
    "title": "Complete House Renovation",
    "startPrice": "RM 22,000",
    "tagline": "End-to-end residential and commercial renovation: design, demolition, structural work, electrical, plumbing, painting, and handover. From RM 22,000.",
    "warranty": "12-Month Structural & Workmanship Warranty",
    "subServices": [
      {
        "name": "Full House Renovation Package",
        "price": "From RM 22,000",
        "desc": "Hacking, structural, ceiling, tiling, electrical, plumbing, painting, and final cleaning."
      },
      {
        "name": "Kitchen & Bathroom Makeover",
        "price": "From RM 10,000",
        "desc": "Demolition, retiling, waterproofing, new cabinetry, plumbing rerouting, and finishing."
      },
      {
        "name": "Condo Interior Refurbishment",
        "price": "From RM 30,000",
        "desc": "Full condo interior rebuild including management work-hour compliance and lift protection."
      },
      {
        "name": "Commercial Shoplot Renovation",
        "price": "On Quote",
        "desc": "Retail and F&B shop fit-outs with electrical upgrades, signage readiness, and fast-track delivery."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pengubahsuaian Rumah Menyeluruh",
        "tagline": "Pengubahsuaian kediaman dan komersial hujung-ke-hujung: reka bentuk, perobohan, kerja struktur, elektrik, paip, pengecatan, dan serahan. Dari RM 22,000.",
        "warranty": "Jaminan Struktur & Kerja 12 Bulan",
        "subServices": [
          {
            "name": "Pakej Pengubahsuaian Rumah Penuh",
            "price": "Dari RM 22,000",
            "desc": "Perobohan, struktur, siling, jubin, elektrik, paip, pengecatan, dan cucian akhir."
          },
          {
            "name": "Makeover Dapur & Bilik Mandi",
            "price": "Dari RM 10,000",
            "desc": "Perobohan, jubin semula, kalis air, kabinet baru, ubah hala paip, dan kemasan."
          },
          {
            "name": "Pemulihan Interior Kondominium",
            "price": "Dari RM 30,000",
            "desc": "Pemulihan interior kondominium penuh termasuk pematuhan waktu kerja pengurusan dan perlindungan lif."
          },
          {
            "name": "Pengubahsuaian Shoplot Komersial",
            "price": "Atas Sebut Harga",
            "desc": "Fit-out runcit dan F&B dengan peningkatan elektrik, kesediaan papan tanda, dan penghantaran pantas."
          }
        ]
      },
      "zh": {
        "title": "全屋翻新服务",
        "tagline": "端到端的住宅与商业翻新：设计、拆除、结构、水电、瓦工、木工、油漆与交付。从 RM 22,000 起。",
        "warranty": "12 个月结构与工艺保修",
        "subServices": [
          {
            "name": "全屋翻新配套",
            "price": "从 RM 22,000 起",
            "desc": "拆除、结构、天花板、瓷砖、水电、油漆与最终清洁。"
          },
          {
            "name": "厨房与卫生间翻新",
            "price": "从 RM 10,000 起",
            "desc": "拆除、重新铺砖、防水、新橱柜、水管改道与完工。"
          },
          {
            "name": "公寓室内翻新",
            "price": "从 RM 30,000 起",
            "desc": "全公寓室内重建，包括管理处工时合规与电梯保护。"
          },
          {
            "name": "商业店铺翻新",
            "price": "依报价",
            "desc": "零售与餐饮店铺装修，电路升级、招牌就位与快速交付。"
          }
        ]
      }
    }
  },
  "electrical": {
    "slug": "electrical",
    "title": "Licensed Electrical Services",
    "startPrice": "RM 150",
    "tagline": "Wiring, DB box upgrades, power point and switch installation, ceiling fan and lighting point setup by ST-licensed electricians. From RM 150.",
    "warranty": "12-Month Electrical Workmanship Warranty",
    "subServices": [
      {
        "name": "New Power Point & Switch Installation",
        "price": "From RM 150 / point",
        "desc": "Adding new 13A sockets, USB outlets, double-pole switches, and dimmer controls on existing or new circuits."
      },
      {
        "name": "DB Box Upgrade & Rewiring",
        "price": "From RM 2,200",
        "desc": "Replacing old fuse boxes with modern MCB+RCCB distribution boards and full or partial house rewiring."
      },
      {
        "name": "Lighting Point & Downlight Installation",
        "price": "From RM 120 / point",
        "desc": "Cutting and wiring new ceiling downlight points, pendant points, and track lighting on existing ceilings."
      },
      {
        "name": "Aircond, Water Heater & Oven Point",
        "price": "From RM 220 / point",
        "desc": "Heavy-load 20A–32A dedicated points with proper isolator and cable sizing per appliance."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Elektrik Berlesen",
        "tagline": "Pendawaian, naik taraf DB box, pemasangan power point dan suis, titik kipas siling dan pencahayaan oleh juruelektrik berdaftar ST. Dari RM 150.",
        "warranty": "Jaminan Kerja Elektrik 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Power Point & Suis Baru",
            "price": "Dari RM 150 / point",
            "desc": "Menambah soket 13A baru, outlet USB, suis double-pole, dan kawalan dimmer pada litar sedia ada atau baru."
          },
          {
            "name": "Naik Taraf DB Box & Pendawaian Semula",
            "price": "Dari RM 2,200",
            "desc": "Menggantikan kotak fius lama dengan papan agihan MCB+RCCB moden dan pendawaian semula rumah penuh atau separa."
          },
          {
            "name": "Titik Pencahayaan & Downlight",
            "price": "Dari RM 120 / point",
            "desc": "Memotong dan mendawai titik downlight siling, titik pendant, dan pencahayaan trek pada siling sedia ada."
          },
          {
            "name": "Titik Aircond, Pemanas Air & Ketuhar",
            "price": "Dari RM 220 / point",
            "desc": "Titik beban berat 20A–32A khusus dengan isolator dan saiz kabel yang betul setiap perkakas."
          }
        ]
      },
      "zh": {
        "title": "持牌电工服务",
        "tagline": "由 ST 注册电工承接的布线、配电箱升级、插座与开关安装、吊扇与照明点位。从 RM 150 起。",
        "warranty": "12 个月电工工艺保修",
        "subServices": [
          {
            "name": "新增插座与开关安装",
            "price": "从 RM 150 / 位起",
            "desc": "在现有或新回路上增加 13A 插座、USB 插座、双极开关与调光控制。"
          },
          {
            "name": "配电箱升级与重新布线",
            "price": "从 RM 2,200 起",
            "desc": "将老式保险丝盒替换为带 MCB+RCCB 的现代配电箱，并进行全屋或局部重新布线。"
          },
          {
            "name": "照明与筒灯点位安装",
            "price": "从 RM 120 / 位起",
            "desc": "在现有天花上切割并布置新的筒灯点位、吊灯点位与轨道灯。"
          },
          {
            "name": "空调、热水器与烤箱点位",
            "price": "从 RM 220 / 位起",
            "desc": "20A–32A 专用大功率点位，配备合适的隔离器与电缆规格。"
          }
        ]
      }
    }
  },
  "water-heater": {
    "slug": "water-heater",
    "title": "Water Heater Installation & Repair",
    "startPrice": "RM 180",
    "tagline": "Instant, storage, and heat-pump water heater supply, installation, repair, and descaling by ST-licensed technicians. From RM 180.",
    "warranty": "12-Month Installation Workmanship Warranty",
    "subServices": [
      {
        "name": "Instant Water Heater Installation",
        "price": "From RM 250",
        "desc": "Single-point instant shower heater supply and install with proper isolator, water-proof cover, and pressure test."
      },
      {
        "name": "Storage Tank Heater Installation",
        "price": "From RM 420",
        "desc": "Multi-point 15L–50L storage heater installation including wall mounting, pressure relief valve, and pipework."
      },
      {
        "name": "Water Heater Repair & Descaling",
        "price": "From RM 180",
        "desc": "Diagnosing leaks, RCCB trips, slow heating, and noises. Includes descaling and anode-rod check on storage tanks."
      },
      {
        "name": "Heat Pump Water Heater Install",
        "price": "From RM 2,200",
        "desc": "Energy-efficient heat-pump system installation for landed properties with outdoor condenser mounting."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pemasangan & Pembaikan Pemanas Air",
        "tagline": "Bekalan, pemasangan, pembaikan dan nyahkerak pemanas air segera, tangki simpanan dan pam haba oleh juruteknik berlesen ST. Dari RM 180.",
        "warranty": "Jaminan Kerja Pemasangan 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Pemanas Air Segera",
            "price": "Dari RM 250",
            "desc": "Bekalan dan pemasangan pemanas mandi segera satu titik dengan isolator, penutup kalis air dan ujian tekanan yang betul."
          },
          {
            "name": "Pemasangan Pemanas Tangki Simpanan",
            "price": "Dari RM 420",
            "desc": "Pemasangan pemanas simpanan pelbagai titik 15L–50L termasuk pelekap dinding, injap pelega tekanan dan kerja paip."
          },
          {
            "name": "Pembaikan & Nyahkerak Pemanas Air",
            "price": "Dari RM 180",
            "desc": "Mendiagnosis kebocoran, RCCB trip, pemanasan perlahan dan bunyi bising. Termasuk nyahkerak dan semakan rod anod pada tangki simpanan."
          },
          {
            "name": "Pemasangan Pemanas Air Pam Haba",
            "price": "Dari RM 2,200",
            "desc": "Pemasangan sistem pam haba cekap tenaga untuk hartanah bertanah dengan pelekap pemeluwap luar."
          }
        ]
      },
      "zh": {
        "title": "热水器安装与维修",
        "tagline": "由 ST 持牌技师提供即热式、储水式与热泵热水器的供应、安装、维修与除垢。从 RM 180 起。",
        "warranty": "12 个月安装工艺保修",
        "subServices": [
          {
            "name": "即热式热水器安装",
            "price": "从 RM 250 起",
            "desc": "单点即热淋浴热水器供应与安装，配备适当的隔离开关、防水罩与压力测试。"
          },
          {
            "name": "储水式热水器安装",
            "price": "从 RM 420 起",
            "desc": "15L–50L 多点储水式热水器安装，包括壁挂、泄压阀与管道工程。"
          },
          {
            "name": "热水器维修与除垢",
            "price": "从 RM 180 起",
            "desc": "诊断漏水、RCCB 跳闸、加热缓慢与异响。包括储水式热水器的除垢与阳极棒检查。"
          },
          {
            "name": "热泵热水器安装",
            "price": "从 RM 2,200 起",
            "desc": "为有地物业安装节能热泵系统，室外冷凝器挂装。"
          }
        ]
      }
    }
  },
  "ceiling-fan": {
    "slug": "ceiling-fan",
    "title": "Ceiling Fan Installation & Replacement",
    "startPrice": "RM 150",
    "tagline": "Safe ceiling fan mounting on concrete, plaster ceiling, and condo false ceiling with proper fan hook, regulator, and concealed wiring. From RM 150.",
    "warranty": "12-Month Mounting & Wiring Warranty",
    "subServices": [
      {
        "name": "New Ceiling Fan Installation",
        "price": "From RM 220",
        "desc": "Mounting your supplied fan on a solid fan hook with regulator, wiring, and swing-test included."
      },
      {
        "name": "Ceiling Fan Replacement",
        "price": "From RM 250",
        "desc": "Removing the old fan, safe disposal, and installing your new fan on the existing hook with fresh wiring."
      },
      {
        "name": "DC Motor Smart Fan Install",
        "price": "From RM 320",
        "desc": "Installing modern 5-blade DC inverter fans with remote and smart-home app pairing."
      },
      {
        "name": "Industrial / Shoplot Fan Install",
        "price": "From RM 420",
        "desc": "Large 60-inch industrial fans and high-CFM commercial installations for warehouses, gyms, and F&B."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pemasangan & Penggantian Kipas Siling",
        "tagline": "Pemasangan kipas siling yang selamat pada konkrit, siling plaster dan siling palsu kondominium dengan cangkuk kipas, regulator dan pendawaian tersembunyi yang betul. Dari RM 150.",
        "warranty": "Jaminan Pemasangan & Pendawaian 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Kipas Siling Baru",
            "price": "Dari RM 220",
            "desc": "Memasang kipas yang anda bekalkan pada cangkuk kipas kukuh dengan regulator, pendawaian dan ujian ayun termasuk."
          },
          {
            "name": "Penggantian Kipas Siling",
            "price": "Dari RM 250",
            "desc": "Menanggalkan kipas lama, pelupusan selamat, dan memasang kipas baru anda pada cangkuk sedia ada dengan pendawaian baharu."
          },
          {
            "name": "Pemasangan Kipas Pintar Motor DC",
            "price": "Dari RM 320",
            "desc": "Memasang kipas penyongsang DC 5 bilah moden dengan kawalan jauh dan pemasangan aplikasi rumah pintar."
          },
          {
            "name": "Pemasangan Kipas Industri / Lot Kedai",
            "price": "Dari RM 420",
            "desc": "Kipas industri 60-inci besar dan pemasangan komersial CFM tinggi untuk gudang, gim dan F&B."
          }
        ]
      },
      "zh": {
        "title": "吊扇安装与更换",
        "tagline": "在混凝土、石膏天花板与公寓吊顶上安全安装吊扇，配备合格的吊扇挂钩、调速器与隐蔽布线。从 RM 150 起。",
        "warranty": "12 个月安装与布线保修",
        "subServices": [
          {
            "name": "新吊扇安装",
            "price": "从 RM 220 起",
            "desc": "将您自购的吊扇安装在牢固的吊扇挂钩上，含调速器、布线与摆动测试。"
          },
          {
            "name": "吊扇更换",
            "price": "从 RM 250 起",
            "desc": "拆除旧吊扇、安全清运，并在现有挂钩上安装您的新吊扇，重新布线。"
          },
          {
            "name": "直流电机智能吊扇安装",
            "price": "从 RM 320 起",
            "desc": "安装现代 5 叶直流变频吊扇，配遥控与智能家居 App 配对。"
          },
          {
            "name": "工业 / 店铺吊扇安装",
            "price": "从 RM 420 起",
            "desc": "大型 60 英寸工业吊扇与高风量商业安装，适用于仓库、健身房与餐饮业。"
          }
        ]
      }
    }
  },
  "lighting": {
    "slug": "lighting",
    "title": "Lighting Design & Installation",
    "startPrice": "RM 120",
    "tagline": "Downlight, track light, pendant, cove, and outdoor lighting design, supply, and installation by ST-licensed electricians. From RM 120 / point.",
    "warranty": "12-Month Lighting Installation Warranty",
    "subServices": [
      {
        "name": "LED Downlight Installation",
        "price": "From RM 120 / point",
        "desc": "Cutting and wiring new downlight points with COB LED fixtures, drivers, and proper heat dissipation."
      },
      {
        "name": "Pendant & Chandelier Install",
        "price": "From RM 180",
        "desc": "Mounting heavy pendants and chandeliers on reinforced ceiling hooks with safety cables."
      },
      {
        "name": "Cove & Strip LED Installation",
        "price": "From RM 22 / ft",
        "desc": "Hidden cove LED strip with aluminum profile, dimmer, and driver concealed in ceiling void."
      },
      {
        "name": "Smart Lighting & Dimmer Retrofit",
        "price": "From RM 250 / point",
        "desc": "Wi-Fi, Zigbee, or DALI smart switches and dimmers compatible with Google Home, Alexa, and Apple Home."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Reka Bentuk & Pemasangan Pencahayaan",
        "tagline": "Reka bentuk, bekalan dan pemasangan lampu downlight, track, pendant, cove dan luar oleh juruelektrik berlesen ST. Dari RM 120 / titik.",
        "warranty": "Jaminan Pemasangan Pencahayaan 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Downlight LED",
            "price": "Dari RM 120 / titik",
            "desc": "Memotong dan memasang pendawaian titik downlight baharu dengan lekapan LED COB, pemacu dan pelesapan haba yang betul."
          },
          {
            "name": "Pemasangan Pendant & Chandelier",
            "price": "Dari RM 180",
            "desc": "Memasang pendant berat dan chandelier pada cangkuk siling diperkuat dengan kabel keselamatan."
          },
          {
            "name": "Pemasangan LED Cove & Jalur",
            "price": "Dari RM 22 / kaki",
            "desc": "Jalur LED cove tersembunyi dengan profil aluminium, malap dan pemacu disembunyikan dalam rongga siling."
          },
          {
            "name": "Retrofit Pencahayaan Pintar & Malap",
            "price": "Dari RM 250 / titik",
            "desc": "Suis pintar Wi-Fi, Zigbee atau DALI dan malap serasi dengan Google Home, Alexa dan Apple Home."
          }
        ]
      },
      "zh": {
        "title": "照明设计与安装",
        "tagline": "由 ST 持牌电工提供筒灯、轨道灯、吊灯、灯槽与户外照明的设计、供应与安装。从 RM 120 / 点位起。",
        "warranty": "12 个月照明安装保修",
        "subServices": [
          {
            "name": "LED 筒灯安装",
            "price": "从 RM 120 / 点位起",
            "desc": "开孔并布线新的筒灯点位，配 COB LED 灯具、驱动器与适当的散热。"
          },
          {
            "name": "吊灯与枝形吊灯安装",
            "price": "从 RM 180 起",
            "desc": "在加固天花板挂钩上安装重型吊灯与枝形吊灯，配安全钢丝绳。"
          },
          {
            "name": "灯槽与 LED 灯带安装",
            "price": "从 RM 22 / 英尺起",
            "desc": "隐藏式灯槽 LED 灯带，配铝槽、调光器与藏于吊顶内的驱动器。"
          },
          {
            "name": "智能照明与调光改造",
            "price": "从 RM 250 / 点位起",
            "desc": "Wi-Fi、Zigbee 或 DALI 智能开关与调光器，兼容 Google Home、Alexa 与 Apple Home。"
          }
        ]
      }
    }
  },
  "tiling": {
    "slug": "tiling",
    "title": "Professional Tiling & Tile Repair",
    "startPrice": "RM 14",
    "tagline": "Floor and wall tiling for new builds, renovations, and repairs. Homogeneous, porcelain, ceramic, mosaic, and large-format slabs. From RM 14 / sq ft.",
    "warranty": "12-Month Tile Adhesion & Grout Warranty",
    "subServices": [
      {
        "name": "Floor Tiling Installation",
        "price": "From RM 14 / sq ft",
        "desc": "Standard 300x300mm to 600x600mm floor tile installation with cement-sand screed and tile adhesive."
      },
      {
        "name": "Wall Tiling Installation",
        "price": "From RM 16 / sq ft",
        "desc": "Kitchen splashback, bathroom wall, and feature wall tiling with straight or brick-bond patterns."
      },
      {
        "name": "Large-Format Slab Tiling",
        "price": "From RM 26 / sq ft",
        "desc": "600x1200mm, 800x1800mm, 1200x2400mm slabs with self-levelling, suction-cup lifters, and lippage tuning."
      },
      {
        "name": "Tile Repair & Re-Grouting",
        "price": "From RM 22 / sq ft",
        "desc": "Removing hollow or cracked tiles, surface prep, replacement, and re-grouting with mould-resistant grout."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Jubin & Pembaikan Jubin Profesional",
        "tagline": "Jubin lantai dan dinding untuk pembinaan baru, pengubahsuaian, dan pembaikan. Homogen, porselin, seramik, mozek, dan slab format besar. Dari RM 14 / sq ft.",
        "warranty": "Jaminan Lekatan Jubin & Grout 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Jubin Lantai",
            "price": "Dari RM 14 / sq ft",
            "desc": "Pemasangan jubin lantai standard 300x300mm hingga 600x600mm dengan screed simen-pasir dan pelekat jubin."
          },
          {
            "name": "Pemasangan Jubin Dinding",
            "price": "Dari RM 16 / sq ft",
            "desc": "Splashback dapur, dinding bilik mandi, dan jubin dinding ciri dengan corak lurus atau bata."
          },
          {
            "name": "Slab Format Besar",
            "price": "Dari RM 26 / sq ft",
            "desc": "Slab 600x1200mm, 800x1800mm, 1200x2400mm dengan self-levelling, cawan sedutan, dan lippage tuning."
          },
          {
            "name": "Pembaikan & Grout Semula",
            "price": "Dari RM 22 / sq ft",
            "desc": "Menyingkirkan jubin berongga atau retak, penyediaan permukaan, penggantian, dan grout semula dengan grout tahan kulat."
          }
        ]
      },
      "zh": {
        "title": "专业瓷砖与瓷砖修补",
        "tagline": "新房、翻新与修补的地面和墙面瓷砖。瓷质、玻化、陶瓷、马赛克与超大板。从 RM 14 / sq ft 起。",
        "warranty": "12 个月瓷砖粘结与勾缝保修",
        "subServices": [
          {
            "name": "地面瓷砖铺贴",
            "price": "从 RM 14 / sq ft 起",
            "desc": "标准 300x300mm 至 600x600mm 地面瓷砖铺贴，使用水泥砂浆找平层与瓷砖胶。"
          },
          {
            "name": "墙面瓷砖铺贴",
            "price": "从 RM 16 / sq ft 起",
            "desc": "厨房防溅墙、卫生间墙面、主题墙铺贴，可选直拼或工字拼。"
          },
          {
            "name": "超大板铺贴",
            "price": "从 RM 26 / sq ft 起",
            "desc": "600x1200mm、800x1800mm、1200x2400mm 超大板，自流平、吸盘与找平器配套。"
          },
          {
            "name": "瓷砖修补与重新勾缝",
            "price": "从 RM 22 / sq ft 起",
            "desc": "拆除空鼓或开裂瓷砖、基层处理、换新与防霉勾缝剂重新勾缝。"
          }
        ]
      }
    }
  },
  "plaster-ceiling": {
    "slug": "plaster-ceiling",
    "title": "Plaster Ceiling Design & Build",
    "startPrice": "RM 10",
    "tagline": "Modern plaster ceiling with concealed LED trough, tiered design, L-box, and cove lighting for landed and high-rise properties. From RM 10 / sq ft.",
    "warranty": "10-Year Sag-Free & Crack-Free Warranty",
    "subServices": [
      {
        "name": "Flat Plaster Ceiling",
        "price": "From RM 10 / sq ft",
        "desc": "Clean, single-level flat ceiling with skim coat finish — ideal for minimalist modern interiors."
      },
      {
        "name": "Tiered & L-Box Ceiling",
        "price": "From RM 14 / sq ft",
        "desc": "Two or three-tier ceiling with concealed LED trough, L-box profile, and integrated downlight cutouts."
      },
      {
        "name": "Cove & Curved Ceiling",
        "price": "From RM 22 / sq ft",
        "desc": "Custom curved, cove, or barrel ceiling with flexible GI framing for ambient indirect lighting."
      },
      {
        "name": "Ceiling Repair & Re-Skim",
        "price": "From RM 8 / sq ft",
        "desc": "Removing water-damaged boards, structural reinforcement, and re-skim coating existing ceilings."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Reka Bentuk & Bina Siling Plaster Moden",
        "tagline": "Siling plaster moden dengan alur LED tersembunyi, reka bentuk bertingkat, L-box, dan pencahayaan cove untuk hartanah bertanah dan bertingkat tinggi. Dari RM 10 / sq ft.",
        "warranty": "Jaminan Bebas Lentur & Retak 10 Tahun",
        "subServices": [
          {
            "name": "Siling Plaster Rata",
            "price": "Dari RM 10 / sq ft",
            "desc": "Siling aras tunggal yang bersih dengan kemasan skim — sesuai untuk interior moden minimalis."
          },
          {
            "name": "Siling Bertingkat & L-Box",
            "price": "Dari RM 14 / sq ft",
            "desc": "Siling dua atau tiga aras dengan alur LED tersembunyi, profil L-box, dan potongan downlight bersepadu."
          },
          {
            "name": "Siling Cove & Melengkung",
            "price": "Dari RM 22 / sq ft",
            "desc": "Siling cove, melengkung, atau tong yang direka khas dengan rangka GI fleksibel untuk pencahayaan tidak langsung ambien."
          },
          {
            "name": "Pembaikan & Skim Semula Siling",
            "price": "Dari RM 8 / sq ft",
            "desc": "Menanggalkan papan rosak air, tetulang struktur, dan skim semula siling sedia ada."
          }
        ]
      },
      "zh": {
        "title": "现代石膏天花板设计与施工",
        "tagline": "为有地与高层物业打造的现代石膏天花板，含隐藏式 LED 灯槽、错层、L 盒与灯带。从 RM 10 / sq ft 起。",
        "warranty": "10 年防下垂与防开裂保修",
        "subServices": [
          {
            "name": "平顶石膏天花",
            "price": "从 RM 10 / sq ft 起",
            "desc": "整洁的单层平顶，刮腻子收光，适合极简现代的室内风格。"
          },
          {
            "name": "错层与 L 盒天花",
            "price": "从 RM 14 / sq ft 起",
            "desc": "两层或三层错层，含隐藏式 LED 灯槽、L 盒造型与筒灯开孔。"
          },
          {
            "name": "灯带与弧形天花",
            "price": "从 RM 22 / sq ft 起",
            "desc": "定制弧形、灯带或桶形天花，使用柔性 GI 骨架，营造间接氛围照明。"
          },
          {
            "name": "天花修补与重新找平",
            "price": "从 RM 8 / sq ft 起",
            "desc": "拆除受潮损坏的板材，结构加固后对旧天花重新刮腻子。"
          }
        ]
      }
    }
  },
  "skim-coat": {
    "slug": "skim-coat",
    "title": "Wall & Ceiling Skim Coat",
    "startPrice": "RM 5",
    "tagline": "Glass-smooth skim coating for walls and ceilings, paint-ready finish, full surface preparation and crack repair. From RM 5 / sq ft.",
    "warranty": "12-Month Smoothness & Adhesion Warranty",
    "subServices": [
      {
        "name": "Wall Skim Coating",
        "price": "From RM 5 / sq ft",
        "desc": "Two-coat skim coating on plastered or previously painted walls for a glass-smooth paint-ready finish."
      },
      {
        "name": "Ceiling Skim Coating",
        "price": "From RM 6 / sq ft",
        "desc": "Re-skim of existing plaster ceilings to refresh aged surfaces before repainting."
      },
      {
        "name": "Crack & Joint Repair",
        "price": "From RM 22 / linier ft",
        "desc": "Opening, routing, and filling of structural and settlement cracks with flexible acrylic filler."
      },
      {
        "name": "Full Condo Re-Skim Package",
        "price": "From RM 4,200",
        "desc": "Complete skim coat of an entire 1,000 sqft condo unit ready for repainting."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Skim Coat Dinding & Siling",
        "tagline": "Salutan skim licin kaca untuk dinding dan siling, kemasan siap-cat, penyediaan permukaan penuh dan pembaikan retak. Dari RM 5 / sq ft.",
        "warranty": "Jaminan Kelicinan & Lekatan 12 Bulan",
        "subServices": [
          {
            "name": "Salutan Skim Dinding",
            "price": "Dari RM 5 / sq ft",
            "desc": "Salutan skim dua lapisan atas plaster atau dinding yang sebelumnya dicat untuk kemasan siap-cat licin kaca."
          },
          {
            "name": "Salutan Skim Siling",
            "price": "Dari RM 6 / sq ft",
            "desc": "Skim semula siling plaster sedia ada untuk menyegarkan permukaan tua sebelum pengecatan semula."
          },
          {
            "name": "Pembaikan Retak & Sendi",
            "price": "Dari RM 22 / linier ft",
            "desc": "Membuka, meroute, dan mengisi retak struktur dan penyelesaian dengan pengisi akrilik fleksibel."
          },
          {
            "name": "Pakej Skim Semula Kondominium Penuh",
            "price": "Dari RM 4,200",
            "desc": "Salutan skim lengkap unit kondominium 1,000 sqft keseluruhan bersedia untuk pengecatan semula."
          }
        ]
      },
      "zh": {
        "title": "墙面与天花腻子",
        "tagline": "玻璃般光滑的墙面与天花腻子，可上漆的表面，全套基层处理与裂缝修补。从 RM 5 / sq ft 起。",
        "warranty": "12 个月平整度与粘结保修",
        "subServices": [
          {
            "name": "墙面腻子",
            "price": "从 RM 5 / sq ft 起",
            "desc": "在已抹灰或旧漆墙面上做两道腻子，达到玻璃般光滑、可上漆的效果。"
          },
          {
            "name": "天花腻子",
            "price": "从 RM 6 / sq ft 起",
            "desc": "对旧石膏天花重新刮腻子，让旧表面焕然一新再上漆。"
          },
          {
            "name": "裂缝与接缝修补",
            "price": "从 RM 22 / 延尺起",
            "desc": "开槽、清理后用弹性丙烯酸填料处理沉降与结构性裂缝。"
          },
          {
            "name": "整套公寓重刮腻子配套",
            "price": "从 RM 4,200 起",
            "desc": "1,000 sqft 公寓全屋刮腻子，准备上漆。"
          }
        ]
      }
    }
  },
  "flooring": {
    "slug": "flooring",
    "title": "Vinyl, SPC & Laminate Flooring",
    "startPrice": "RM 14",
    "tagline": "Modern click-lock flooring for homes and offices. Waterproof SPC, scratch-resistant laminate, and luxury vinyl planks. From RM 14 / sq ft.",
    "warranty": "5-Year Installation Workmanship Warranty",
    "subServices": [
      {
        "name": "SPC Click-Lock Flooring Install",
        "price": "From RM 14 / sq ft",
        "desc": "Waterproof stone polymer composite planks with built-in underlay, ideal for whole-home installation."
      },
      {
        "name": "Laminate Flooring Install",
        "price": "From RM 11 / sq ft",
        "desc": "Budget-friendly HDF laminate with wood-look finish, AC4–AC5 wear rating for residential traffic."
      },
      {
        "name": "Luxury Vinyl Plank (LVP) Install",
        "price": "From RM 16 / sq ft",
        "desc": "100% waterproof LVP with realistic wood grain, perfect for wet kitchens, bathrooms, and basement."
      },
      {
        "name": "Skirting & Transition Strip Fitting",
        "price": "From RM 8 / linier ft",
        "desc": "PVC, MDF, or aluminium skirting plus T-mould and reducer transitions for a clean room-to-room finish."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Lantai Vinyl, SPC & Laminate",
        "tagline": "Lantai click-lock moden untuk rumah dan pejabat. SPC kalis air, laminate tahan calar dan papan vinyl mewah. Dari RM 14 / kaki persegi.",
        "warranty": "Jaminan Kerja Pemasangan 5 Tahun",
        "subServices": [
          {
            "name": "Pemasangan Lantai SPC Click-Lock",
            "price": "Dari RM 14 / kaki persegi",
            "desc": "Papan komposit polimer batu kalis air dengan underlay terbina dalam, sesuai untuk pemasangan seluruh rumah."
          },
          {
            "name": "Pemasangan Lantai Laminate",
            "price": "Dari RM 11 / kaki persegi",
            "desc": "Laminate HDF mesra bajet dengan kemasan rupa kayu, penarafan haus AC4–AC5 untuk trafik kediaman."
          },
          {
            "name": "Pemasangan Papan Vinyl Mewah (LVP)",
            "price": "Dari RM 16 / kaki persegi",
            "desc": "LVP 100% kalis air dengan urat kayu realistik, sesuai untuk dapur basah, bilik mandi dan besmen."
          },
          {
            "name": "Pemasangan Skirting & Jalur Peralihan",
            "price": "Dari RM 8 / kaki linier",
            "desc": "Skirting PVC, MDF atau aluminium serta peralihan T-mould dan reducer untuk kemasan bilik-ke-bilik yang kemas."
          }
        ]
      },
      "zh": {
        "title": "Vinyl、SPC 与复合地板",
        "tagline": "适用于家庭与办公室的现代锁扣地板。防水 SPC、耐磨复合地板与豪华乙烯基地板。从 RM 14 / 平方英尺起。",
        "warranty": "5 年安装工艺保修",
        "subServices": [
          {
            "name": "SPC 锁扣地板安装",
            "price": "从 RM 14 / 平方英尺起",
            "desc": "带内置垫层的防水石塑复合地板，非常适合全屋铺装。"
          },
          {
            "name": "复合地板安装",
            "price": "从 RM 11 / 平方英尺起",
            "desc": "经济实惠的 HDF 复合地板，仿木纹表面处理，AC4–AC5 耐磨等级适合家用。"
          },
          {
            "name": "豪华乙烯基地板 (LVP) 安装",
            "price": "从 RM 16 / 平方英尺起",
            "desc": "100% 防水 LVP，木纹逼真，适合湿厨房、浴室与地下室。"
          },
          {
            "name": "踢脚线与收边条安装",
            "price": "从 RM 8 / 延英尺起",
            "desc": "PVC、MDF 或铝合金踢脚线，配 T 型条与高低扣，房间之间收口干净利落。"
          }
        ]
      }
    }
  },
  "epoxy-flooring": {
    "slug": "epoxy-flooring",
    "title": "Epoxy & Polyurethane Flooring",
    "startPrice": "RM 22",
    "tagline": "Heavy-duty epoxy floor coating for garages, warehouses, factories, showrooms, and commercial kitchens. From RM 22 / sq ft.",
    "warranty": "5-Year Delamination & Yellowing Warranty",
    "subServices": [
      {
        "name": "Self-Levelling Epoxy Floor",
        "price": "From RM 22 / sq ft",
        "desc": "Mirror-smooth 2–3mm self-levelling epoxy for residential, showroom, and light commercial floors."
      },
      {
        "name": "Flake / Quartz Broadcast Epoxy",
        "price": "From RM 26 / sq ft",
        "desc": "Decorative vinyl flake or coloured quartz broadcast with slip-resistant finish for garages and kitchens."
      },
      {
        "name": "Heavy-Duty Mortar Screed",
        "price": "From RM 38 / sq ft",
        "desc": "5–10mm trowel-applied epoxy mortar for warehouses, factories, and forklift traffic zones."
      },
      {
        "name": "Epoxy Floor Repair & Recoating",
        "price": "From RM 14 / sq ft",
        "desc": "Diamond-grinding the existing epoxy, repairing damaged areas, and applying fresh primer + topcoat."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Lantai Epoxy & Polyurethane",
        "tagline": "Salutan lantai epoxy tugas berat untuk garaj, gudang, kilang, bilik pameran dan dapur komersial. Dari RM 22 / kaki persegi.",
        "warranty": "Jaminan Delaminasi & Penguningan 5 Tahun",
        "subServices": [
          {
            "name": "Lantai Epoxy Rata-Sendiri",
            "price": "Dari RM 22 / kaki persegi",
            "desc": "Epoxy rata-sendiri 2–3mm licin cermin untuk lantai kediaman, bilik pameran dan komersial ringan."
          },
          {
            "name": "Epoxy Taburan Flake / Kuarza",
            "price": "Dari RM 26 / kaki persegi",
            "desc": "Taburan flake vinyl hiasan atau kuarza berwarna dengan kemasan rintangan gelincir untuk garaj dan dapur."
          },
          {
            "name": "Mortar Screed Tugas Berat",
            "price": "Dari RM 38 / kaki persegi",
            "desc": "Mortar epoxy sapuan trowel 5–10mm untuk gudang, kilang dan zon trafik forklift."
          },
          {
            "name": "Pembaikan & Salutan Semula Lantai Epoxy",
            "price": "Dari RM 14 / kaki persegi",
            "desc": "Mengisar intan epoxy sedia ada, membaiki kawasan rosak dan menyapu primer + topcoat baharu."
          }
        ]
      },
      "zh": {
        "title": "环氧与聚氨酯地坪",
        "tagline": "适用于车库、仓库、工厂、展厅与商业厨房的重型环氧地坪涂层。从 RM 22 / 平方英尺起。",
        "warranty": "5 年脱层与黄变保修",
        "subServices": [
          {
            "name": "自流平环氧地坪",
            "price": "从 RM 22 / 平方英尺起",
            "desc": "2–3mm 镜面自流平环氧，适合住宅、展厅与轻型商业地面。"
          },
          {
            "name": "彩片 / 石英撒砂环氧",
            "price": "从 RM 26 / 平方英尺起",
            "desc": "装饰乙烯基彩片或彩色石英撒砂，防滑表面，适合车库与厨房。"
          },
          {
            "name": "重型砂浆面层",
            "price": "从 RM 38 / 平方英尺起",
            "desc": "5–10mm 镘涂环氧砂浆，适合仓库、工厂与叉车通行区。"
          },
          {
            "name": "环氧地坪维修与翻新",
            "price": "从 RM 14 / 平方英尺起",
            "desc": "金刚石打磨现有环氧，修补损坏区域，重新施工底漆 + 面漆。"
          }
        ]
      }
    }
  },
  "roof-repair": {
    "slug": "roof-repair",
    "title": "Roof Repair & Waterproofing",
    "startPrice": "RM 380",
    "tagline": "Roof tile replacement, leak repair, gutter cleaning, flashing, and full torch-on waterproofing for landed properties. From RM 380.",
    "warranty": "10-Year Membrane & Workmanship Warranty",
    "subServices": [
      {
        "name": "Roof Leak Diagnosis & Repair",
        "price": "From RM 380",
        "desc": "Thermal imaging to locate the leak source, followed by tile, flashing, or membrane repair on the affected area."
      },
      {
        "name": "Ridge Re-Bedding & Re-Pointing",
        "price": "From RM 22 / linier ft",
        "desc": "Removing loose ridge mortar and re-bedding with flexible polymer mortar for a permanent seal."
      },
      {
        "name": "Gutter Cleaning & Realignment",
        "price": "From RM 320",
        "desc": "Clearing leaves and debris, realigning falls toward downpipes, and sealing leaking joints."
      },
      {
        "name": "Full Torch-On Membrane Waterproofing",
        "price": "From RM 26 / sq ft",
        "desc": "Two-layer torch-applied bituminous membrane system with 10-year manufacturer warranty for flat roofs."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pembaikan & Kalis Air Bumbung",
        "tagline": "Penggantian jubin bumbung, pembaikan bocor, pembersihan longkang, flashing dan kalis air torch-on penuh untuk hartanah bertanah. Dari RM 380.",
        "warranty": "Jaminan Membran & Kerja 10 Tahun",
        "subServices": [
          {
            "name": "Diagnosis & Pembaikan Bocor Bumbung",
            "price": "Dari RM 380",
            "desc": "Pengimejan terma untuk mengesan sumber bocor, diikuti pembaikan jubin, flashing atau membran pada kawasan terjejas."
          },
          {
            "name": "Re-Bedding & Re-Pointing Rabung",
            "price": "Dari RM 22 / kaki linier",
            "desc": "Menanggalkan mortar rabung longgar dan re-bedding dengan mortar polimer fleksibel untuk pengedapan kekal."
          },
          {
            "name": "Pembersihan & Penjajaran Semula Longkang",
            "price": "Dari RM 320",
            "desc": "Membersihkan daun dan serpihan, menjajarkan semula cerun ke arah paip turun dan mengedap sambungan bocor."
          },
          {
            "name": "Kalis Air Membran Torch-On Penuh",
            "price": "Dari RM 26 / kaki persegi",
            "desc": "Sistem membran bitumen dua lapisan sapu obor dengan jaminan pengeluar 10 tahun untuk bumbung rata."
          }
        ]
      },
      "zh": {
        "title": "屋顶维修与防水",
        "tagline": "有地物业的屋瓦更换、漏水维修、天沟清理、泛水板与全烤贴式防水。从 RM 380 起。",
        "warranty": "10 年卷材与工艺保修",
        "subServices": [
          {
            "name": "屋顶漏水诊断与维修",
            "price": "从 RM 380 起",
            "desc": "热成像定位漏水源，随后对受影响区域进行换瓦、泛水或卷材维修。"
          },
          {
            "name": "屋脊重新铺浆与勾缝",
            "price": "从 RM 22 / 延英尺起",
            "desc": "清除松动的屋脊砂浆，用柔性聚合物砂浆重新铺浆，永久密封。"
          },
          {
            "name": "天沟清理与调坡",
            "price": "从 RM 320 起",
            "desc": "清除树叶与杂物，将坡度调至落水口方向，并密封漏水接缝。"
          },
          {
            "name": "全烤贴式卷材防水",
            "price": "从 RM 26 / 平方英尺起",
            "desc": "双层火烤沥青卷材系统，平屋顶享 10 年制造商保修。"
          }
        ]
      }
    }
  },
  "kitchen-cabinet": {
    "slug": "kitchen-cabinet",
    "title": "Kitchen Cabinet & Countertop",
    "startPrice": "RM 7,500",
    "tagline": "Custom-built and modular kitchen cabinets with stone, solid surface, or laminate countertops. Design, supply, install. From RM 7,500.",
    "warranty": "5-Year Cabinet Structure Warranty",
    "subServices": [
      {
        "name": "Modular Kitchen Cabinet (10ft L-shape)",
        "price": "From RM 7,500",
        "desc": "Häfele or Blum hardware with 18mm melamine carcass, doors in laminate, acrylic, or spray-painted finish."
      },
      {
        "name": "Custom Plywood Kitchen",
        "price": "From RM 11,000",
        "desc": "Built-to-fit plywood cabinet with soft-close hardware, custom doors, and full-height pantry units."
      },
      {
        "name": "Quartz / Granite Countertop",
        "price": "From RM 220 / linier ft",
        "desc": "Caesarstone, Silestone, or local granite with undermount sink cutout and seamless joins."
      },
      {
        "name": "Kitchen Makeover (Doors & Hardware Only)",
        "price": "From RM 4,200",
        "desc": "Replacing doors, drawer fronts, handles, hinges, and runners to refresh an existing kitchen carcass."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Kabinet Dapur & Permukaan Kaunter",
        "tagline": "Kabinet dapur kustom dan modular dengan permukaan kaunter batu, solid surface atau laminate. Reka bentuk, bekalan, pemasangan. Dari RM 7,500.",
        "warranty": "Jaminan Struktur Kabinet 5 Tahun",
        "subServices": [
          {
            "name": "Kabinet Dapur Modular (L-shape 10 kaki)",
            "price": "Dari RM 7,500",
            "desc": "Perkakasan Häfele atau Blum dengan rangka melamin 18mm, pintu dalam kemasan laminate, akrilik atau cat semburan."
          },
          {
            "name": "Dapur Papan Lapis Kustom",
            "price": "Dari RM 11,000",
            "desc": "Kabinet papan lapis bina-mengikut-ukuran dengan perkakasan tutup lembut, pintu kustom dan unit pantry penuh tinggi."
          },
          {
            "name": "Permukaan Kaunter Kuarza / Granit",
            "price": "Dari RM 220 / kaki linier",
            "desc": "Caesarstone, Silestone atau granit tempatan dengan potongan singki bawah-duduk dan sambungan lancar."
          },
          {
            "name": "Makeover Dapur (Pintu & Perkakasan Sahaja)",
            "price": "Dari RM 4,200",
            "desc": "Menggantikan pintu, muka laci, pemegang, engsel dan rel untuk menyegarkan rangka dapur sedia ada."
          }
        ]
      },
      "zh": {
        "title": "厨房橱柜与台面",
        "tagline": "定制与模块化厨房橱柜，配石材、实体面材或防火板台面。设计、供应、安装。从 RM 7,500 起。",
        "warranty": "5 年柜体结构保修",
        "subServices": [
          {
            "name": "模块化厨房橱柜（10 英尺 L 型）",
            "price": "从 RM 7,500 起",
            "desc": "Häfele 或 Blum 五金配 18mm 三聚氰胺柜体，门板可选防火板、亚克力或喷漆饰面。"
          },
          {
            "name": "定制胶合板厨房",
            "price": "从 RM 11,000 起",
            "desc": "按尺寸定制的胶合板橱柜，配缓冲五金、定制门板与通顶 pantry 柜。"
          },
          {
            "name": "石英石 / 花岗岩台面",
            "price": "从 RM 220 / 延英尺起",
            "desc": "Caesarstone、Silestone 或本地花岗岩，台下盆开孔与无缝拼接。"
          },
          {
            "name": "厨房翻新（仅门板与五金）",
            "price": "从 RM 4,200 起",
            "desc": "更换门板、抽屉面板、拉手、铰链与滑轨，让现有柜体焕然一新。"
          }
        ]
      }
    }
  },
  "carpentry": {
    "slug": "carpentry",
    "title": "Custom Carpentry & Joinery",
    "startPrice": "RM 300",
    "tagline": "Built-in wardrobes, TV consoles, study desks, feature walls, shoe racks, and custom furniture. From RM 300 / linier ft.",
    "warranty": "5-Year Cabinet Structure Warranty",
    "subServices": [
      {
        "name": "Built-in Wardrobe",
        "price": "From RM 320 / linier ft",
        "desc": "Floor-to-ceiling wardrobe with internal drawers, shelves, hanging rails, and mirror or laminate doors."
      },
      {
        "name": "TV Console & Feature Wall",
        "price": "From RM 1,500",
        "desc": "Custom TV console with storage drawers, floating shelves, cable management, and matching feature wall panelling."
      },
      {
        "name": "Study Desk & Home Office",
        "price": "From RM 1,100",
        "desc": "Built-in study desk with cable management, drawers, overhead cabinets, and matching shelving."
      },
      {
        "name": "Shoe Cabinet & Entry Storage",
        "price": "From RM 1,800",
        "desc": "Slim depth shoe cabinet with tilt-out drawers, sitting bench, mirror, and integrated lighting."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pertukangan & Kerja Kayu Kustom",
        "tagline": "Almari pakaian tanam, konsol TV, meja belajar, dinding feature, rak kasut dan perabot kustom. Dari RM 300 / kaki linier.",
        "warranty": "Jaminan Struktur Kabinet 5 Tahun",
        "subServices": [
          {
            "name": "Almari Pakaian Tanam",
            "price": "Dari RM 320 / kaki linier",
            "desc": "Almari pakaian lantai-ke-siling dengan laci dalaman, para, rel gantungan dan pintu cermin atau laminate."
          },
          {
            "name": "Konsol TV & Dinding Feature",
            "price": "Dari RM 1,500",
            "desc": "Konsol TV kustom dengan laci storan, para terapung, pengurusan kabel dan panel dinding feature sepadan."
          },
          {
            "name": "Meja Belajar & Pejabat Rumah",
            "price": "Dari RM 1,100",
            "desc": "Meja belajar tanam dengan pengurusan kabel, laci, kabinet atas dan rak sepadan."
          },
          {
            "name": "Kabinet Kasut & Storan Pintu Masuk",
            "price": "Dari RM 1,800",
            "desc": "Kabinet kasut kedalaman nipis dengan laci tilt-out, bangku duduk, cermin dan pencahayaan bersepadu."
          }
        ]
      },
      "zh": {
        "title": "定制木工与细木作",
        "tagline": "定制入墙衣柜、电视柜、书桌、背景墙、鞋柜与定制家具。从 RM 300 / 延英尺起。",
        "warranty": "5 年柜体结构保修",
        "subServices": [
          {
            "name": "入墙衣柜",
            "price": "从 RM 320 / 延英尺起",
            "desc": "顶天立地衣柜，配内置抽屉、层板、挂衣杆与镜面或防火板门。"
          },
          {
            "name": "电视柜与背景墙",
            "price": "从 RM 1,500 起",
            "desc": "定制电视柜，配收纳抽屉、悬浮层板、走线管理与配套背景墙板。"
          },
          {
            "name": "书桌与家庭办公",
            "price": "从 RM 1,100 起",
            "desc": "入墙式书桌，配走线管理、抽屉、吊柜与配套层架。"
          },
          {
            "name": "鞋柜与玄关收纳",
            "price": "从 RM 1,800 起",
            "desc": "薄进深鞋柜，配翻斗抽屉、换鞋凳、镜子与内嵌灯光。"
          }
        ]
      }
    }
  },
  "door": {
    "slug": "door",
    "title": "Door Repair & Installation",
    "startPrice": "RM 250",
    "tagline": "Solid timber, engineered, fire-rated, and laminate doors — supply, install, plane, hinge, and lock fitting. From RM 250.",
    "warranty": "12-Month Door Hanging & Hardware Warranty",
    "subServices": [
      {
        "name": "Solid Timber Door Installation",
        "price": "From RM 550",
        "desc": "Solid meranti or chengal door with meranti frame, 3 SS304 hinges, architrave, and basic mortice lockset."
      },
      {
        "name": "Laminate Door Installation",
        "price": "From RM 250",
        "desc": "HDF-skin engineered door with smooth laminate finish, ideal for budget-friendly modern interiors."
      },
      {
        "name": "Door Planing & Adjustment",
        "price": "From RM 120",
        "desc": "Trimming a door that is scraping the floor or frame, rehanging on existing hinges, and adjusting the lockset."
      },
      {
        "name": "Fire-Rated Door Installation",
        "price": "From RM 950",
        "desc": "1-hour or 2-hour certified fire door with intumescent seals, suitable for kitchen, staircase, or fire-escape access."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pembaikan & Pemasangan Pintu",
        "tagline": "Pintu kayu pepejal, engineered, tahan api dan laminate — bekalan, pemasangan, ketam, engsel dan pemasangan kunci. Dari RM 250.",
        "warranty": "Jaminan Gantungan Pintu & Perkakasan 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Pintu Kayu Pepejal",
            "price": "Dari RM 550",
            "desc": "Pintu meranti atau chengal pepejal dengan bingkai meranti, 3 engsel SS304, architrave dan set kunci mortice asas."
          },
          {
            "name": "Pemasangan Pintu Laminate",
            "price": "Dari RM 250",
            "desc": "Pintu engineered kulit HDF dengan kemasan laminate licin, sesuai untuk dalaman moden mesra bajet."
          },
          {
            "name": "Ketam & Pelarasan Pintu",
            "price": "Dari RM 120",
            "desc": "Memotong pintu yang menggesel lantai atau bingkai, menggantung semula pada engsel sedia ada dan melaraskan set kunci."
          },
          {
            "name": "Pemasangan Pintu Tahan Api",
            "price": "Dari RM 950",
            "desc": "Pintu api bertauliah 1 jam atau 2 jam dengan pengedap intumescent, sesuai untuk dapur, tangga atau akses laluan kecemasan."
          }
        ]
      },
      "zh": {
        "title": "门维修与安装",
        "tagline": "实木、工程木、防火与防火板门——供应、安装、刨修、铰链与锁具安装。从 RM 250 起。",
        "warranty": "12 个月门扇安装与五金保修",
        "subServices": [
          {
            "name": "实木门安装",
            "price": "从 RM 550 起",
            "desc": "meranti 或 chengal 实木门，配 meranti 门框、3 个 SS304 铰链、门套与基础执手锁。"
          },
          {
            "name": "防火板门安装",
            "price": "从 RM 250 起",
            "desc": "HDF 贴面工程门，防火板饰面光滑，适合经济型现代室内。"
          },
          {
            "name": "门刨修与调校",
            "price": "从 RM 120 起",
            "desc": "刨修刮地或刮框的门，在现有铰链上重新挂门并调试锁具。"
          },
          {
            "name": "防火门安装",
            "price": "从 RM 950 起",
            "desc": "1 小时或 2 小时认证防火门，配膨胀密封条，适合厨房、楼梯间或消防疏散通道。"
          }
        ]
      }
    }
  },
  "window-repair": {
    "slug": "window-repair",
    "title": "Window Repair & Glass Replacement",
    "startPrice": "RM 200",
    "tagline": "Casement, sliding, top-hung, awning windows — glass replacement, seal repair, handle replacement, and alignment. From RM 200.",
    "warranty": "12-Month Hardware & Seal Warranty",
    "subServices": [
      {
        "name": "Glass Replacement",
        "price": "From RM 200",
        "desc": "Removing broken or cracked glass and installing new clear, tinted, frosted, or tempered glass to the same size and thickness."
      },
      {
        "name": "Window Seal Replacement",
        "price": "From RM 30 / linier ft",
        "desc": "Replacing worn or hardened EPDM rubber seals to stop water ingress and improve insulation."
      },
      {
        "name": "Window Handle & Hinge Repair",
        "price": "From RM 120",
        "desc": "Replacing broken, stiff, or corroded handles, hinges, stays, and locking mechanisms on casement or top-hung windows."
      },
      {
        "name": "Sliding Window Roller Replacement",
        "price": "From RM 150",
        "desc": "Replacing worn nylon or steel rollers and cleaning tracks for smooth sliding operation."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pembaikan Tingkap & Penggantian Kaca",
        "tagline": "Tingkap casement, gelangsar, top-hung, awning — penggantian kaca, pembaikan pengedap, penggantian pemegang dan penjajaran. Dari RM 200.",
        "warranty": "Jaminan Perkakasan & Pengedap 12 Bulan",
        "subServices": [
          {
            "name": "Penggantian Kaca",
            "price": "Dari RM 200",
            "desc": "Menanggalkan kaca pecah atau retak dan memasang kaca jernih, tinted, frosted atau tempered baharu mengikut saiz dan ketebalan sama."
          },
          {
            "name": "Penggantian Pengedap Tingkap",
            "price": "Dari RM 30 / kaki linier",
            "desc": "Menggantikan pengedap getah EPDM haus atau mengeras untuk menghentikan kemasukan air dan menambah baik penebatan."
          },
          {
            "name": "Pembaikan Pemegang & Engsel Tingkap",
            "price": "Dari RM 120",
            "desc": "Menggantikan pemegang, engsel, stay dan mekanisme kunci rosak, keras atau berkarat pada tingkap casement atau top-hung."
          },
          {
            "name": "Penggantian Roller Tingkap Gelangsar",
            "price": "Dari RM 150",
            "desc": "Menggantikan roller nilon atau keluli haus dan membersihkan trek untuk operasi gelongsor lancar."
          }
        ]
      },
      "zh": {
        "title": "窗户维修与玻璃更换",
        "tagline": "平开窗、推拉窗、上悬窗、外开下悬窗——玻璃更换、密封条维修、执手更换与调校。从 RM 200 起。",
        "warranty": "12 个月五金与密封保修",
        "subServices": [
          {
            "name": "玻璃更换",
            "price": "从 RM 200 起",
            "desc": "拆除碎裂或开裂玻璃，安装相同尺寸厚度的新白玻、茶色玻、磨砂玻或钢化玻璃。"
          },
          {
            "name": "窗户密封条更换",
            "price": "从 RM 30 / 延英尺起",
            "desc": "更换老化变硬的 EPDM 橡胶密封条，阻止渗水并改善保温。"
          },
          {
            "name": "窗户执手与铰链维修",
            "price": "从 RM 120 起",
            "desc": "更换平开窗或上悬窗上损坏、卡涩或腐蚀的执手、铰链、撑挡与锁闭机构。"
          },
          {
            "name": "推拉窗滑轮更换",
            "price": "从 RM 150 起",
            "desc": "更换磨损的尼龙或钢滑轮并清洁轨道，恢复顺滑推拉。"
          }
        ]
      }
    }
  },
  "locksmith": {
    "slug": "locksmith",
    "title": "Locksmith & Smart Lock Services",
    "startPrice": "RM 180",
    "tagline": "Digital smart locks, key cutting, lock replacement, door reinforcement, and emergency lockout service. From RM 180.",
    "warranty": "12-Month Lock Installation & Hardware Warranty",
    "subServices": [
      {
        "name": "Smart Lock Installation",
        "price": "From RM 420",
        "desc": "Supply and install digital keypad, Bluetooth, Wi-Fi, or biometric fingerprint lock with app pairing and user registration."
      },
      {
        "name": "Mortice / Deadbolt Lock Replacement",
        "price": "From RM 220",
        "desc": "Remove existing mortice or deadbolt lock and install a new Yale, Imperial, or Hafele lock with 3 keys."
      },
      {
        "name": "Key Cutting & Re-Keying",
        "price": "From RM 30",
        "desc": "Cutting new keys to existing locks, or re-keying the lock to a new key so old keys stop working (ideal after moving in or lost key)."
      },
      {
        "name": "Emergency Lockout (Landed House)",
        "price": "From RM 180",
        "desc": "Non-destructive entry to your home or room during lockout, with proof of ownership. Available same-day within KL & Selangor."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Tukang Kunci & Kunci Pintar",
        "tagline": "Kunci pintar digital, pemotongan kunci, penggantian kunci, pengukuhan pintu dan perkhidmatan kecemasan terkunci. Dari RM 180.",
        "warranty": "Jaminan Pemasangan Kunci & Perkakasan 12 Bulan",
        "subServices": [
          {
            "name": "Pemasangan Kunci Pintar",
            "price": "Dari RM 420",
            "desc": "Bekalan dan pemasangan kunci pad kekunci digital, Bluetooth, Wi-Fi atau cap jari biometrik dengan pemasangan aplikasi dan pendaftaran pengguna."
          },
          {
            "name": "Penggantian Kunci Mortice / Deadbolt",
            "price": "Dari RM 220",
            "desc": "Menanggalkan kunci mortice atau deadbolt sedia ada dan memasang kunci Yale, Imperial atau Hafele baharu dengan 3 kunci."
          },
          {
            "name": "Pemotongan Kunci & Re-Key",
            "price": "Dari RM 30",
            "desc": "Memotong kunci baharu untuk kunci sedia ada, atau re-key kunci kepada kunci baharu supaya kunci lama tidak berfungsi (sesuai selepas berpindah atau kehilangan kunci)."
          },
          {
            "name": "Kecemasan Terkunci (Rumah Landed)",
            "price": "Dari RM 180",
            "desc": "Kemasukan tanpa merosakkan ke rumah atau bilik anda semasa terkunci, dengan bukti pemilikan. Tersedia hari sama dalam KL & Selangor."
          }
        ]
      },
      "zh": {
        "title": "锁匠与智能锁服务",
        "tagline": "数字智能锁、配钥匙、换锁、门体加固与紧急开锁服务。从 RM 180 起。",
        "warranty": "12 个月锁具安装与五金保修",
        "subServices": [
          {
            "name": "智能锁安装",
            "price": "从 RM 420 起",
            "desc": "供应并安装数字密码、蓝牙、Wi-Fi 或生物指纹锁，含 App 配对与用户录入。"
          },
          {
            "name": "执手锁 / 呆锁更换",
            "price": "从 RM 220 起",
            "desc": "拆除现有执手锁或呆锁，安装带 3 把钥匙的新 Yale、Imperial 或 Hafele 锁。"
          },
          {
            "name": "配钥匙与换锁芯",
            "price": "从 RM 30 起",
            "desc": "为现有锁配新钥匙，或换锁芯改用新钥匙使旧钥匙失效（适合搬新家或丢钥匙后）。"
          },
          {
            "name": "紧急开锁（有地住宅）",
            "price": "从 RM 180 起",
            "desc": "被锁门外时无损开启您的家门或房门，需提供所有权证明。吉隆坡与雪兰莪当日可达。"
          }
        ]
      }
    }
  },
  "glass-aluminium": {
    "slug": "glass-aluminium",
    "title": "Glass & Aluminium Fabrication",
    "startPrice": "RM 320",
    "tagline": "Shower screens, glass partitions, aluminium windows, sliding doors, and mirror installation across KL & Selangor. From RM 320.",
    "warranty": "12-Month Leak-Free & Hardware Warranty",
    "subServices": [
      {
        "name": "Frameless Shower Screen",
        "price": "From RM 420 / panel",
        "desc": "10–12mm tempered glass with concealed hinges and anti-leak seals. Custom cut to your bathroom layout."
      },
      {
        "name": "Aluminium Sliding Window",
        "price": "From RM 320 / sq ft",
        "desc": "Locally fabricated aluminium sliding window with 5mm clear or tinted glass, nylon rollers, and weatherstrip."
      },
      {
        "name": "Glass Office Partition",
        "price": "From RM 220 / sq ft",
        "desc": "10–12mm tempered glass partition with aluminium or frameless channel, including door and hardware."
      },
      {
        "name": "Wall Mirror Installation",
        "price": "From RM 320",
        "desc": "5–6mm silver-backed mirror with concealed aluminium channel fixings, suitable for bathrooms, gyms, and dressing rooms."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Fabrikasi Kaca & Aluminium",
        "tagline": "Skrin pancuran, partition kaca, tingkap aluminium, pintu gelangsar dan pemasangan cermin di seluruh KL & Selangor. Dari RM 320.",
        "warranty": "Jaminan Bebas Bocor & Perkakasan 12 Bulan",
        "subServices": [
          {
            "name": "Skrin Pancuran Tanpa Bingkai",
            "price": "Dari RM 420 / panel",
            "desc": "Kaca tempered 10–12mm dengan engsel tersembunyi dan pengedap anti-bocor. Potongan kustom mengikut susun atur bilik mandi anda."
          },
          {
            "name": "Tingkap Gelangsar Aluminium",
            "price": "Dari RM 320 / kaki persegi",
            "desc": "Tingkap gelangsar aluminium fabrikasi tempatan dengan kaca jernih atau tinted 5mm, roller nilon dan weatherstrip."
          },
          {
            "name": "Partition Pejabat Kaca",
            "price": "Dari RM 220 / kaki persegi",
            "desc": "Partition kaca tempered 10–12mm dengan saluran aluminium atau tanpa bingkai, termasuk pintu dan perkakasan."
          },
          {
            "name": "Pemasangan Cermin Dinding",
            "price": "Dari RM 320",
            "desc": "Cermin silver-backed 5–6mm dengan pengikat saluran aluminium tersembunyi, sesuai untuk bilik mandi, gim dan bilik persalinan."
          }
        ]
      },
      "zh": {
        "title": "玻璃与铝业工程",
        "tagline": "吉隆坡与雪兰莪的淋浴屏、玻璃隔断、铝合金窗、推拉门与镜子安装。从 RM 320 起。",
        "warranty": "12 个月防漏与五金保修",
        "subServices": [
          {
            "name": "无框淋浴屏",
            "price": "从 RM 420 / 扇起",
            "desc": "10–12mm 钢化玻璃配暗藏铰链与防漏密封。按您的浴室布局定制裁切。"
          },
          {
            "name": "铝合金推拉窗",
            "price": "从 RM 320 / 平方英尺起",
            "desc": "本地制作的铝合金推拉窗，配 5mm 白玻或茶色玻、尼龙滑轮与密封毛条。"
          },
          {
            "name": "玻璃办公隔断",
            "price": "从 RM 220 / 平方英尺起",
            "desc": "10–12mm 钢化玻璃隔断，配铝合金或无框地槽，含门与五金。"
          },
          {
            "name": "墙镜安装",
            "price": "从 RM 320 起",
            "desc": "5–6mm 镀银镜，配暗藏铝槽固定件，适合浴室、健身房与更衣室。"
          }
        ]
      }
    }
  },
  "cleaning": {
    "slug": "cleaning",
    "title": "Residential & Office Cleaning",
    "startPrice": "RM 180",
    "tagline": "Weekly, fortnightly, or monthly cleaning for homes, condos, and small offices. Background-checked cleaners, eco products. From RM 180 / session.",
    "warranty": "24-Hour Re-Clean Satisfaction Guarantee",
    "subServices": [
      {
        "name": "Weekly Condo Cleaning (1,000 sqft)",
        "price": "From RM 180 / visit",
        "desc": "3-bed condo or apartment cleaned weekly, including kitchen, bathrooms, and common areas."
      },
      {
        "name": "Bi-Weekly Terrace House Cleaning",
        "price": "From RM 250 / visit",
        "desc": "Two-storey terrace house cleaned every fortnight, including ground floor, first floor, and outdoor areas."
      },
      {
        "name": "Office Cleaning (Small Office, 1,500 sqft)",
        "price": "From RM 320 / visit",
        "desc": "After-hours office cleaning including workstations, meeting rooms, pantry, and restrooms."
      },
      {
        "name": "One-Off Spring Clean",
        "price": "From RM 420",
        "desc": "One-time deep clean including ceiling fans, light fixtures, behind furniture, and window interiors."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pembersihan Kediaman & Pejabat",
        "tagline": "Pembersihan mingguan, dua minggu sekali atau bulanan untuk rumah, kondominium dan pejabat kecil. Pembersih diperiksa latar belakang, produk mesra alam. Dari RM 180 / sesi.",
        "warranty": "Jaminan Kepuasan Cuci Semula 24 Jam",
        "subServices": [
          {
            "name": "Pembersihan Kondominium Mingguan (1,000 kaki persegi)",
            "price": "Dari RM 180 / lawatan",
            "desc": "Kondominium 3 bilik atau apartmen dibersihkan setiap minggu, termasuk dapur, bilik mandi dan kawasan bersama."
          },
          {
            "name": "Pembersihan Rumah Teres Dua Minggu Sekali",
            "price": "Dari RM 250 / lawatan",
            "desc": "Rumah teres dua tingkat dibersihkan setiap dua minggu, termasuk tingkat bawah, tingkat satu dan kawasan luar."
          },
          {
            "name": "Pembersihan Pejabat (Pejabat Kecil, 1,500 kaki persegi)",
            "price": "Dari RM 320 / lawatan",
            "desc": "Pembersihan pejabat selepas waktu kerja termasuk stesen kerja, bilik mesyuarat, pantry dan tandas."
          },
          {
            "name": "Cucian Musim Sekali Sahaja",
            "price": "Dari RM 420",
            "desc": "Pembersihan menyeluruh sekali termasuk kipas siling, lekapan lampu, belakang perabot dan bahagian dalam tingkap."
          }
        ]
      },
      "zh": {
        "title": "住宅与办公室清洁",
        "tagline": "住宅、公寓与小型办公室的每周、每两周或每月清洁。背景审查的清洁员，环保清洁剂。从 RM 180 / 次起。",
        "warranty": "24 小时返工满意保证",
        "subServices": [
          {
            "name": "每周公寓清洁（1,000 平方英尺）",
            "price": "从 RM 180 / 次起",
            "desc": "三房公寓每周清洁，包括厨房、浴室与公共区域。"
          },
          {
            "name": "每两周排屋清洁",
            "price": "从 RM 250 / 次起",
            "desc": "双层排屋每两周清洁，包括楼下、楼上与室外区域。"
          },
          {
            "name": "办公室清洁（小型办公室，1,500 平方英尺）",
            "price": "从 RM 320 / 次起",
            "desc": "下班后办公室清洁，包括工位、会议室、茶水间与洗手间。"
          },
          {
            "name": "单次大扫除",
            "price": "从 RM 420 起",
            "desc": "一次性深度清洁，包括吊扇、灯具、家具背后与窗户内侧。"
          }
        ]
      }
    }
  },
  "deep-cleaning": {
    "slug": "deep-cleaning",
    "title": "Deep Cleaning & Move-In/Out",
    "startPrice": "RM 420",
    "tagline": "Top-to-bottom deep cleaning for move-in, move-out, post-illness, or seasonal refresh. From RM 420.",
    "warranty": "24-Hour Re-Clean Satisfaction Guarantee",
    "subServices": [
      {
        "name": "Condo Move-Out Deep Clean (1,000 sqft)",
        "price": "From RM 420",
        "desc": "Full top-to-bottom clean including inside cabinets, oven, fridge, fans, and window tracks. Move-out ready."
      },
      {
        "name": "Terrace House Deep Clean (2,000 sqft)",
        "price": "From RM 650",
        "desc": "Two-storey home including outdoor areas, garage, and staircases. Move-in or move-out ready."
      },
      {
        "name": "Post-Illness Disinfection Clean",
        "price": "From RM 500",
        "desc": "Hospital-grade disinfection of all touchpoints, fabrics, and air spaces. Recommended after flu, COVID, or stomach bugs."
      },
      {
        "name": "Allergy Season Refresh",
        "price": "From RM 480",
        "desc": "HEPA-vacuum deep clean with dust-mite treatment on mattresses, sofas, and curtains."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Cucian Menyeluruh & Pindah Masuk/Keluar",
        "tagline": "Cucian menyeluruh atas-ke-bawah untuk pindah masuk, pindah keluar, selepas sakit atau penyegaran bermusim. Dari RM 420.",
        "warranty": "Jaminan Kepuasan Cuci Semula 24 Jam",
        "subServices": [
          {
            "name": "Cucian Menyeluruh Pindah Keluar Kondominium (1,000 kaki persegi)",
            "price": "Dari RM 420",
            "desc": "Cucian atas-ke-bawah penuh termasuk bahagian dalam kabinet, ketuhar, peti sejuk, kipas dan trek tingkap. Sedia pindah keluar."
          },
          {
            "name": "Cucian Menyeluruh Rumah Teres (2,000 kaki persegi)",
            "price": "Dari RM 650",
            "desc": "Rumah dua tingkat termasuk kawasan luar, garaj dan tangga. Sedia pindah masuk atau keluar."
          },
          {
            "name": "Cucian Disinfeksi Selepas Sakit",
            "price": "Dari RM 500",
            "desc": "Disinfeksi gred hospital semua titik sentuh, fabrik dan ruang udara. Disyorkan selepas selesema, COVID atau sakit perut."
          },
          {
            "name": "Penyegaran Musim Alahan",
            "price": "Dari RM 480",
            "desc": "Cucian menyeluruh vakum HEPA dengan rawatan hama habuk pada tilam, sofa dan langsir."
          }
        ]
      },
      "zh": {
        "title": "深度清洁与搬家保洁",
        "tagline": "入住、退租、病后消毒或季节性焕新的全屋自上而下深度清洁。从 RM 420 起。",
        "warranty": "24 小时返工满意保证",
        "subServices": [
          {
            "name": "公寓退租深度清洁（1,000 平方英尺）",
            "price": "从 RM 420 起",
            "desc": "全屋自上而下清洁，包括柜内、烤箱、冰箱、吊扇与窗轨。达到退租标准。"
          },
          {
            "name": "排屋深度清洁（2,000 平方英尺）",
            "price": "从 RM 650 起",
            "desc": "双层住宅含室外区域、车库与楼梯。达到入住或退租标准。"
          },
          {
            "name": "病后消毒清洁",
            "price": "从 RM 500 起",
            "desc": "所有接触点、织物与空气的医用级消毒。建议流感、新冠或肠胃病后使用。"
          },
          {
            "name": "过敏季焕新",
            "price": "从 RM 480 起",
            "desc": "HEPA 吸尘深度清洁，床垫、沙发与窗帘的尘螨处理。"
          }
        ]
      }
    }
  },
  "post-renovation-cleaning": {
    "slug": "post-renovation-cleaning",
    "title": "Post-Renovation Cleaning",
    "startPrice": "RM 650",
    "tagline": "Construction debris removal, paint dust, grout haze, and silicone cleanup after renovation. From RM 650.",
    "warranty": "7-Day Spot-Check Free Re-Clean Guarantee",
    "subServices": [
      {
        "name": "Condo Post-Renovation Clean (1,000 sqft)",
        "price": "From RM 650",
        "desc": "Full post-renovation clean for a 3-bed condo after a typical kitchen + bathroom renovation."
      },
      {
        "name": "Terrace House Post-Renovation Clean (2,000 sqft)",
        "price": "From RM 1,400",
        "desc": "Whole-house post-renovation clean including outdoor areas, garage, and windows."
      },
      {
        "name": "New Tiles Grout Haze Removal",
        "price": "From RM 10 / sq ft",
        "desc": "Specialist grout haze removal on newly laid porcelain or ceramic tiles using pH-balanced acidic cleaner."
      },
      {
        "name": "Construction Debris Removal",
        "price": "From RM 320",
        "desc": "Bagging and disposal of leftover construction materials, packaging, and debris. Skip bin coordination if needed."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pembersihan Selepas Pengubahsuaian",
        "tagline": "Penyingkiran serpihan pembinaan, habuk cat, kabut grout dan pembersihan silikon selepas pengubahsuaian. Dari RM 650.",
        "warranty": "Jaminan Cuci Semula Percuma Pemeriksaan Rawak 7 Hari",
        "subServices": [
          {
            "name": "Cucian Selepas Pengubahsuaian Kondominium (1,000 kaki persegi)",
            "price": "Dari RM 650",
            "desc": "Cucian selepas pengubahsuaian penuh untuk kondominium 3 bilik selepas pengubahsuaian dapur + bilik mandi biasa."
          },
          {
            "name": "Cucian Selepas Pengubahsuaian Rumah Teres (2,000 kaki persegi)",
            "price": "Dari RM 1,400",
            "desc": "Cucian selepas pengubahsuaian seluruh rumah termasuk kawasan luar, garaj dan tingkap."
          },
          {
            "name": "Penyingkiran Kabut Grout Jubin Baharu",
            "price": "Dari RM 10 / kaki persegi",
            "desc": "Penyingkiran kabut grout pakar pada jubin porselin atau seramik baru dipasang menggunakan pencuci berasid seimbang pH."
          },
          {
            "name": "Penyingkiran Serpihan Pembinaan",
            "price": "Dari RM 320",
            "desc": "Pembungkusan dan pelupusan bahan pembinaan, pembungkusan dan serpihan tertinggal. Penyelarasan tong skip jika perlu."
          }
        ]
      },
      "zh": {
        "title": "装修后开荒保洁",
        "tagline": "装修后的建筑废料清运、涂料粉尘、砖缝浮灰与玻璃胶渍清洁。从 RM 650 起。",
        "warranty": "7 天免费抽查返工保证",
        "subServices": [
          {
            "name": "公寓装修后开荒（1,000 平方英尺）",
            "price": "从 RM 650 起",
            "desc": "三房公寓在典型厨卫装修后的全屋开荒保洁。"
          },
          {
            "name": "排屋装修后开荒（2,000 平方英尺）",
            "price": "从 RM 1,400 起",
            "desc": "整栋房屋装修后开荒，含室外区域、车库与窗户。"
          },
          {
            "name": "新瓷砖砖缝浮灰清除",
            "price": "从 RM 10 / 平方英尺起",
            "desc": "使用 pH 平衡酸性清洁剂，专业清除新铺抛光砖或瓷砖上的砖缝浮灰。"
          },
          {
            "name": "建筑垃圾清运",
            "price": "从 RM 320 起",
            "desc": "剩余建筑材料、包装与废料的装袋清运。需要时可协调租用垃圾桶。"
          }
        ]
      }
    }
  },
  "cctv": {
    "slug": "cctv",
    "title": "CCTV & Security Camera Installation",
    "startPrice": "RM 420",
    "tagline": "Hikvision, Dahua, Ezviz, TP-Link, Tuya CCTV supply, install, network setup, and remote viewing. From RM 420 / camera.",
    "warranty": "12-Month Camera & Installation Warranty",
    "subServices": [
      {
        "name": "Condo Wi-Fi CCTV Package (4 cameras)",
        "price": "From RM 2,200",
        "desc": "4x 4MP Wi-Fi cameras with cloud storage, mobile app setup, and remote viewing. Ideal for 1,000-1,500 sqft condos."
      },
      {
        "name": "Landed House PoE CCTV (8 cameras)",
        "price": "From RM 4,200",
        "desc": "8x 4MP PoE bullet cameras, 8-channel NVR with 2TB HDD, 1-week continuous recording, full cable routing."
      },
      {
        "name": "Single Camera Add-On",
        "price": "From RM 420",
        "desc": "Adding one more camera to an existing system (Hikvision/Dahua/Ezviz/Tapo) including cable, mounting, and app pairing."
      },
      {
        "name": "CCTV System Health Check & Relocation",
        "price": "From RM 220",
        "desc": "On-site health check, cleaning, re-aim, app reconfiguration, or relocation of existing CCTV cameras."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Pemasangan CCTV & Kamera Keselamatan",
        "tagline": "Bekalan, pemasangan, persediaan rangkaian dan tontonan jauh CCTV Hikvision, Dahua, Ezviz, TP-Link, Tuya. Dari RM 420 / kamera.",
        "warranty": "Jaminan Kamera & Pemasangan 12 Bulan",
        "subServices": [
          {
            "name": "Pakej CCTV Wi-Fi Kondominium (4 kamera)",
            "price": "Dari RM 2,200",
            "desc": "4x kamera Wi-Fi 4MP dengan storan awan, persediaan aplikasi mudah alih dan tontonan jauh. Sesuai untuk kondominium 1,000-1,500 kaki persegi."
          },
          {
            "name": "CCTV PoE Rumah Landed (8 kamera)",
            "price": "Dari RM 4,200",
            "desc": "8x kamera bullet PoE 4MP, NVR 8 saluran dengan HDD 2TB, rakaman berterusan 1 minggu, laluan kabel penuh."
          },
          {
            "name": "Tambahan Kamera Tunggal",
            "price": "Dari RM 420",
            "desc": "Menambah satu lagi kamera pada sistem sedia ada (Hikvision/Dahua/Ezviz/Tapo) termasuk kabel, pemasangan dan pemasangan aplikasi."
          },
          {
            "name": "Pemeriksaan Kesihatan & Pemindahan Sistem CCTV",
            "price": "Dari RM 220",
            "desc": "Pemeriksaan kesihatan di tapak, pembersihan, sasaran semula, konfigurasi semula aplikasi atau pemindahan kamera CCTV sedia ada."
          }
        ]
      },
      "zh": {
        "title": "CCTV 与监控摄像头安装",
        "tagline": "Hikvision、Dahua、Ezviz、TP-Link、Tuya 监控的供应、安装、网络设置与远程查看。从 RM 420 / 台起。",
        "warranty": "12 个月摄像头与安装保修",
        "subServices": [
          {
            "name": "公寓 Wi-Fi 监控套餐（4 台）",
            "price": "从 RM 2,200 起",
            "desc": "4 台 4MP Wi-Fi 摄像头，配云存储、手机 App 设置与远程查看。适合 1,000-1,500 平方英尺公寓。"
          },
          {
            "name": "有地住宅 PoE 监控（8 台）",
            "price": "从 RM 4,200 起",
            "desc": "8 台 4MP PoE 枪机、8 路 NVR 配 2TB 硬盘、1 周连续录像、完整布线。"
          },
          {
            "name": "单台加装摄像头",
            "price": "从 RM 420 起",
            "desc": "在现有系统（Hikvision/Dahua/Ezviz/Tapo）上加装一台摄像头，含线缆、安装与 App 配对。"
          },
          {
            "name": "监控系统健康检查与移机",
            "price": "从 RM 220 起",
            "desc": "现场健康检查、清洁、重新调校角度、App 重新配置，或迁移现有监控摄像头。"
          }
        ]
      }
    }
  },
  "autogate": {
    "slug": "autogate",
    "title": "Auto Gate & Motorised Gate",
    "startPrice": "RM 2,200",
    "tagline": "Swing, sliding, and folding autogate supply, install, and motor servicing across KL & Selangor. From RM 2,200.",
    "warranty": "12-Month Motor & Installation Warranty",
    "subServices": [
      {
        "name": "Single Swing Autogate",
        "price": "From RM 2,200",
        "desc": "Single-leaf swing gate motor with 2 remotes, safety sensor, and basic installation. Most popular for terrace houses."
      },
      {
        "name": "Double Swing Autogate",
        "price": "From RM 3,200",
        "desc": "Two-leaf swing gate with dual motors, synchronisation, 2 remotes, and 2 safety sensors."
      },
      {
        "name": "Sliding Autogate",
        "price": "From RM 3,800",
        "desc": "Sliding gate with rack-and-pinion motor, ground track, and 2 remotes. Ideal for narrow driveways."
      },
      {
        "name": "Autogate Motor Replacement & Service",
        "price": "From RM 950",
        "desc": "Replacement of failed motor with new unit, control board reconfiguration, and safety sensor re-test."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Autogate & Pagar Bermotor",
        "tagline": "Bekalan, pemasangan dan servis motor autogate hayun, gelangsar dan lipat di seluruh KL & Selangor. Dari RM 2,200.",
        "warranty": "Jaminan Motor & Pemasangan 12 Bulan",
        "subServices": [
          {
            "name": "Autogate Hayun Tunggal",
            "price": "Dari RM 2,200",
            "desc": "Motor pagar hayun satu daun dengan 2 remote, sensor keselamatan dan pemasangan asas. Paling popular untuk rumah teres."
          },
          {
            "name": "Autogate Hayun Berkembar",
            "price": "Dari RM 3,200",
            "desc": "Pagar hayun dua daun dengan motor dwi, penyegerakan, 2 remote dan 2 sensor keselamatan."
          },
          {
            "name": "Autogate Gelangsar",
            "price": "Dari RM 3,800",
            "desc": "Pagar gelangsar dengan motor rack-and-pinion, trek tanah dan 2 remote. Sesuai untuk laluan kereta sempit."
          },
          {
            "name": "Penggantian & Servis Motor Autogate",
            "price": "Dari RM 950",
            "desc": "Penggantian motor rosak dengan unit baharu, konfigurasi semula papan kawalan dan ujian semula sensor keselamatan."
          }
        ]
      },
      "zh": {
        "title": "电动门与自动门系统",
        "tagline": "吉隆坡与雪兰莪平开、推拉与折叠电动门的供应、安装与电机保养。从 RM 2,200 起。",
        "warranty": "12 个月电机与安装保修",
        "subServices": [
          {
            "name": "单开平开电动门",
            "price": "从 RM 2,200 起",
            "desc": "单开门电机，配 2 个遥控器、安全传感器与基础安装。排屋最热门选择。"
          },
          {
            "name": "双开平开电动门",
            "price": "从 RM 3,200 起",
            "desc": "双开门配双电机、同步控制、2 个遥控器与 2 个安全传感器。"
          },
          {
            "name": "推拉电动门",
            "price": "从 RM 3,800 起",
            "desc": "齿轮齿条电机推拉门，配地轨与 2 个遥控器。适合狭窄车道。"
          },
          {
            "name": "电动门电机更换与保养",
            "price": "从 RM 950 起",
            "desc": "更换故障电机，重新配置控制板，重测安全传感器。"
          }
        ]
      }
    }
  },
  "welding": {
    "slug": "welding",
    "title": "Welding & Metal Fabrication",
    "startPrice": "RM 280",
    "tagline": "Custom grilles, gates, structural repair, staircase fabrication, and on-site welding across KL & Selangor. From RM 280.",
    "warranty": "12-Month Welding & Fabrication Warranty",
    "subServices": [
      {
        "name": "Custom Window Grille",
        "price": "From RM 42 / sq ft",
        "desc": "Powder-coated mild steel window grille in your chosen design (geometric, classic, or modern). Includes anti-rust primer."
      },
      {
        "name": "Main Gate Fabrication",
        "price": "From RM 2,800",
        "desc": "Custom main gate with mild steel frame, infill design of your choice, and hot-dip galvanised + powder-coat finish."
      },
      {
        "name": "On-Site Welding Repair",
        "price": "From RM 280",
        "desc": "Emergency or scheduled welding repair at your location — broken hinges, gate, grille, railing, or structural steel."
      },
      {
        "name": "Staircase Stringer Fabrication",
        "price": "From RM 420 / linier ft",
        "desc": "Custom mild steel staircase stringer fabricated to your measurements, primed and painted for indoor or outdoor use."
      }
    ],
    "i18n": {
      "ms": {
        "title": "Kimpalan & Fabrikasi Logam",
        "tagline": "Grilles kustom, pagar, pembaikan struktur, fabrikasi tangga dan kimpalan di tapak di seluruh KL & Selangor. Dari RM 280.",
        "warranty": "Jaminan Kimpalan & Fabrikasi 12 Bulan",
        "subServices": [
          {
            "name": "Grille Tingkap Kustom",
            "price": "Dari RM 42 / kaki persegi",
            "desc": "Grille tingkap keluli lembut powder-coated dalam reka bentuk pilihan anda (geometri, klasik atau moden). Termasuk primer anti-karat."
          },
          {
            "name": "Fabrikasi Pagar Utama",
            "price": "Dari RM 2,800",
            "desc": "Pagar utama kustom dengan rangka keluli lembut, reka bentuk isian pilihan anda dan kemasan galvanis celup panas + powder-coat."
          },
          {
            "name": "Pembaikan Kimpalan Di Tapak",
            "price": "Dari RM 280",
            "desc": "Pembaikan kimpalan kecemasan atau berjadual di lokasi anda — engsel, pagar, grille, railing atau keluli struktur patah."
          },
          {
            "name": "Fabrikasi Stringer Tangga",
            "price": "Dari RM 420 / kaki linier",
            "desc": "Stringer tangga keluli lembut kustom difabrikasi mengikut ukuran anda, di-primer dan dicat untuk kegunaan dalaman atau luaran."
          }
        ]
      },
      "zh": {
        "title": "焊接与金属加工",
        "tagline": "吉隆坡与雪兰莪的定制防护格栅、大门、结构维修、楼梯制作与现场焊接。从 RM 280 起。",
        "warranty": "12 个月焊接与加工保修",
        "subServices": [
          {
            "name": "定制窗户防护格栅",
            "price": "从 RM 42 / 平方英尺起",
            "desc": "粉末喷涂低碳钢窗栅，款式任选（几何、经典或现代）。含防锈底漆。"
          },
          {
            "name": "大门定制",
            "price": "从 RM 2,800 起",
            "desc": "定制大门，低碳钢框架，任选填充设计，热镀锌 + 粉末喷涂饰面。"
          },
          {
            "name": "现场焊接维修",
            "price": "从 RM 280 起",
            "desc": "上门紧急或预约焊接维修——铰链、大门、格栅、栏杆或结构钢断裂。"
          },
          {
            "name": "楼梯龙骨制作",
            "price": "从 RM 420 / 延英尺起",
            "desc": "按您尺寸定制的低碳钢楼梯龙骨，底漆加面漆，室内外皆可。"
          }
        ]
      }
    }
  }
};

export const quoteCatalogList = Object.values(quoteCatalogBySlug);

export function getLocalizedQuoteEntry(entry: QuoteCatalogEntry, locale: "en" | "ms" | "zh"): QuoteCatalogEntry {
  if (locale === "en") return entry;
  const override = entry.i18n?.[locale];
  if (!override) return entry;
  return {
    ...entry,
    title: override.title || entry.title,
    tagline: override.tagline || entry.tagline,
    warranty: override.warranty || entry.warranty,
    subServices: override.subServices?.length ? override.subServices : entry.subServices,
  };
}
