// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts

export type ServiceSummary = {
  slug: string;
  title: string;
  startPrice: string;
  icon: string;
  tagline: string;
  subServices: { name: string }[];
  warranty: string;
  i18n?: Partial<Record<"ms" | "zh", {
    title: string;
    tagline: string;
    subServices: { name: string }[];
    warranty: string;
  }>>;
};

export const serviceSummaryBySlug: Record<string, ServiceSummary> = {
  "painting": {
    "slug": "painting",
    "title": "House Painting Services",
    "startPrice": "RM 450",
    "icon": "paint-brush",
    "tagline": "Interior, exterior and wall repainting for homes, offices and shops across KL & Selangor, with surface preparation, floor and furniture protection, and clean handover. From RM 450.",
    "subServices": [
      {
        "name": "Interior House Painting"
      },
      {
        "name": "Exterior House Painting"
      },
      {
        "name": "Commercial & Office Painting"
      },
      {
        "name": "Wall Crack & Moisture Repair"
      },
      {
        "name": "Condo & Apartment Painting"
      },
      {
        "name": "Ceiling Painting"
      },
      {
        "name": "Wall Preparation & Priming"
      },
      {
        "name": "Feature Wall Painting"
      }
    ],
    "warranty": "1-Year Paint Peeling & Craftsmanship Guarantee",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Mengecat Rumah",
        "tagline": "Pengecatan interior & eksterior profesional untuk ruang kediaman dan komersial. Kemasan licin, cat premium, perlindungan tanpa kotor. Dari RM 450.",
        "subServices": [
          {
            "name": "Pengecatan Rumah Interior"
          },
          {
            "name": "Pengecatan Rumah Eksterior"
          },
          {
            "name": "Pengecatan Komersial & Pejabat"
          },
          {
            "name": "Pembaikan Retak & Lembapan Dinding"
          },
          {
            "name": "Pengecatan Kondominium & Apartmen"
          },
          {
            "name": "Pengecatan Siling"
          },
          {
            "name": "Persediaan & Primer Dinding"
          },
          {
            "name": "Pengecatan Dinding Ciri"
          }
        ],
        "warranty": "Jaminan Pengelupasan Cat & Kerja 1 Tahun"
      },
      "zh": {
        "title": "房屋油漆服务",
        "tagline": "为住宅和商业空间提供专业室内外油漆服务。光滑饰面，优质涂料，全程无尘保护。从 RM 450 起。",
        "subServices": [
          {
            "name": "室内房屋油漆"
          },
          {
            "name": "室外房屋油漆"
          },
          {
            "name": "商业与办公室油漆"
          },
          {
            "name": "墙面裂缝与防潮修复"
          },
          {
            "name": "公寓与组屋油漆"
          },
          {
            "name": "天花板油漆"
          },
          {
            "name": "墙面处理与底漆"
          },
          {
            "name": "特色墙面油漆"
          }
        ],
        "warranty": "1 年油漆剥落与工艺保修"
      }
    }
  },
  "plumbing": {
    "slug": "plumbing",
    "title": "Plumbing & Leak Repair Services",
    "startPrice": "RM 280",
    "icon": "droplet",
    "tagline": "Plumbing and leak repair for pipes, taps, toilets, drains, water heaters and pumps across KL & Selangor, with the scope confirmed before work. From RM 280.",
    "subServices": [
      {
        "name": "Water Leakage Diagnosis & Repair"
      },
      {
        "name": "Toilet, Tap & Sink Installation"
      },
      {
        "name": "Drain Unclogging & Cleaning"
      },
      {
        "name": "Water Heater & Pump Installation"
      },
      {
        "name": "Bathroom Plumbing Renovation"
      },
      {
        "name": "Kitchen Plumbing Renovation"
      },
      {
        "name": "Pipe Replacement & Rerouting"
      },
      {
        "name": "Drainage & Floor Trap Upgrade"
      },
      {
        "name": "Shower & Rain Shower Installation"
      },
      {
        "name": "Renovation Plumbing Work"
      }
    ],
    "warranty": "30-Day Joint Seal & Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Paip & Baiki Kebocoran",
        "tagline": "Pembaikan paip yang boleh dipercayai, pembaikan kebocoran air, dan pemasangan lekapan baru. Alat ganti bertauliah SIRIM, respons pantas. Dari RM 280.",
        "subServices": [
          {
            "name": "Diagnosis & Pembaikan Kebocoran Air"
          },
          {
            "name": "Pemasangan Tandas, Paip Air & Singki"
          },
          {
            "name": "Penyahsumbatan & Pembersihan Saliran"
          },
          {
            "name": "Pemasangan Pemanas Air & Pam"
          },
          {
            "name": "Kerja Paip Pengubahsuaian Bilik Mandi"
          },
          {
            "name": "Kerja Paip Pengubahsuaian Dapur"
          },
          {
            "name": "Penggantian & Penyusunan Semula Paip"
          },
          {
            "name": "Naik Taraf Saliran & Perangkap Lantai"
          },
          {
            "name": "Pemasangan Pancuran & Rain Shower"
          },
          {
            "name": "Kerja Paip Pengubahsuaian"
          }
        ],
        "warranty": "Jaminan Pengedap Sendi & Kerja 30 Hari"
      },
      "zh": {
        "title": "水管与漏水维修服务",
        "tagline": "可靠的水管维修、漏水修复与新洁具安装。SIRIM 认证配件，快速响应。从 RM 280 起。",
        "subServices": [
          {
            "name": "漏水诊断与修复"
          },
          {
            "name": "马桶、水龙头与水槽安装"
          },
          {
            "name": "疏通与清洁排水管"
          },
          {
            "name": "热水器与水泵安装"
          },
          {
            "name": "卫生间水管翻新"
          },
          {
            "name": "厨房水管翻新"
          },
          {
            "name": "水管更换与改管"
          },
          {
            "name": "排水与地漏升级"
          },
          {
            "name": "花洒与顶喷安装"
          },
          {
            "name": "装修水管工程"
          }
        ],
        "warranty": "30 天接头密封与工艺保修"
      }
    }
  },
  "ceiling": {
    "slug": "ceiling",
    "title": "Ceiling & Partition Services",
    "startPrice": "RM 220",
    "icon": "layout-grid",
    "tagline": "Plaster ceiling installation and repair, gypsum partitions, cornices, L-box features and skim finishing for homes and commercial spaces across KL & Selangor. From RM 220.",
    "subServices": [
      {
        "name": "Water-Damaged Ceiling Repair"
      },
      {
        "name": "Plaster Ceiling Installation"
      },
      {
        "name": "Gypsum Board Partition Wall"
      },
      {
        "name": "Cornice & L-Box Concealed Light Trough"
      }
    ],
    "warranty": "90-Day Structural Sagging & Crack-Free Warranty",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Siling & Partition",
        "tagline": "Pembaikan siling plaster profesional, partition papan gypsum, pemasangan kornis, dan pengedapan retak dinding estetik. Dari RM 220.",
        "subServices": [
          {
            "name": "Pembaikan Siling Rosak Air"
          },
          {
            "name": "Pemasangan Siling Plaster"
          },
          {
            "name": "Dinding Partition Papan Gypsum"
          },
          {
            "name": "Kornis & Lekuk Lampu Tersembunyi L-Box"
          }
        ],
        "warranty": "Jaminan Melendut Struktur & Bebas Retak 90 Hari"
      },
      "zh": {
        "title": "天花板与隔墙服务",
        "tagline": "专业石膏天花板维修、石膏板隔墙、线板安装以及美观的墙面裂缝密封。从 RM 220 起。",
        "subServices": [
          {
            "name": "水损天花板维修"
          },
          {
            "name": "石膏天花板安装"
          },
          {
            "name": "石膏板隔墙"
          },
          {
            "name": "线板与 L 型盒暗藏灯槽"
          }
        ],
        "warranty": "90 天结构防下垂与无裂缝保修"
      }
    }
  },
  "waterproofing": {
    "slug": "waterproofing",
    "title": "Waterproofing & Leak Repair Services",
    "startPrice": "RM 300",
    "icon": "shield",
    "tagline": "Bathroom, roof, balcony and concrete waterproofing plus PU injection grouting for leaks across KL & Selangor, selected after assessing the cause. From RM 300.",
    "subServices": [
      {
        "name": "PU High-Pressure Injection Grouting"
      },
      {
        "name": "Bathroom & Wet Area Waterproofing"
      },
      {
        "name": "Roof & Concrete Slab Waterproofing"
      },
      {
        "name": "Wall Dampness & Efflorescence Repair"
      },
      {
        "name": "Toilet Waterproofing"
      },
      {
        "name": "Balcony Waterproofing"
      },
      {
        "name": "Concrete Slab & Car Porch Waterproofing"
      },
      {
        "name": "Water Leakage Repair"
      },
      {
        "name": "Ceiling Water Damage Repair"
      },
      {
        "name": "Waterproofing Repair & Re-Coating"
      }
    ],
    "warranty": "Up to 5-Year Written Leak-Free Guarantee",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Kalis Air & Baiki Kebocoran",
        "tagline": "Kalis air profesional bilik air, bumbung, balkoni, dan slab konkrit. Grouting Poliuretana (PU), penghadang membran kimia. Dari RM 300.",
        "subServices": [
          {
            "name": "Grouting Suntikan Tekanan Tinggi PU"
          },
          {
            "name": "Kalis Air Bilik Air & Kawasan Basah"
          },
          {
            "name": "Kalis Air Bumbung & Slab Konkrit"
          },
          {
            "name": "Pembaikan Lembapan Dinding & Kesan Garam"
          },
          {
            "name": "Kalis Air Tandas"
          },
          {
            "name": "Kalis Air Balkoni"
          },
          {
            "name": "Kalis Air Slab Konkrit & Porch Kereta"
          },
          {
            "name": "Pembaikan Kebocoran Air"
          },
          {
            "name": "Pembaikan Siling Rosak Air"
          },
          {
            "name": "Pembaikan & Sapu Semula Kalis Air"
          }
        ],
        "warranty": "Jaminan Bebas Bocor Bertulis Sehingga 5 Tahun"
      },
      "zh": {
        "title": "防水与漏水维修服务",
        "tagline": "专业浴室、屋顶、阳台与混凝土板防水。聚氨酯（PU）灌浆，化学防水层。从 RM 300 起。",
        "subServices": [
          {
            "name": "PU 高压灌浆注射"
          },
          {
            "name": "浴室与湿区防水"
          },
          {
            "name": "屋顶与混凝土板防水"
          },
          {
            "name": "墙面潮湿与盐析修复"
          },
          {
            "name": "马桶防水"
          },
          {
            "name": "阳台防水"
          },
          {
            "name": "混凝土板与车棚防水"
          },
          {
            "name": "漏水修复"
          },
          {
            "name": "天花板水损修复"
          },
          {
            "name": "防水层维修与重涂"
          }
        ],
        "warranty": "长达 5 年书面防漏保证"
      }
    }
  },
  "handyman": {
    "slug": "handyman",
    "title": "Handyman Services",
    "startPrice": "RM 280",
    "icon": "wrench",
    "tagline": "TV mounting, door and lock repair, furniture assembly, curtain and shelf installation, cabinet adjustments and general maintenance across KL & Selangor. From RM 280.",
    "subServices": [
      {
        "name": "Heavy TV Wall Mounting"
      },
      {
        "name": "Door, Hinge & Lockset Repair"
      },
      {
        "name": "Furniture Assembly (IKEA/Taobao)"
      },
      {
        "name": "Curtains, Blinds & Shelves Hanging"
      }
    ],
    "warranty": "30-Day Workmanship Safety Warranty",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Handyman",
        "tagline": "Pembaikan pintu & kunci profesional, pemasangan TV, pemasangan perabot, trek langsir, pelarasan kabinet, dan penyelenggaraan pejabat am. Dari RM 280.",
        "subServices": [
          {
            "name": "Pemasangan Dinding TV Berat"
          },
          {
            "name": "Pembaikan Pintu, Engsel & Kunci"
          },
          {
            "name": "Pemasangan Perabot (IKEA/Taobao)"
          },
          {
            "name": "Penggantungan Langsir, Bidai & Rak"
          }
        ],
        "warranty": "Jaminan Keselamatan Kerja 30 Hari"
      },
      "zh": {
        "title": "家居杂工服务",
        "tagline": "专业门锁维修、电视挂墙、家具组装、窗帘轨道、橱柜调整以及一般办公室维护。从 RM 280 起。",
        "subServices": [
          {
            "name": "重型电视挂墙"
          },
          {
            "name": "门、铰链与锁具维修"
          },
          {
            "name": "家具组装（IKEA/淘宝）"
          },
          {
            "name": "窗帘、百叶窗与置物架安装"
          }
        ],
        "warranty": "30 天工艺安全保修"
      }
    }
  },
  "house-renovation": {
    "slug": "house-renovation",
    "title": "Complete House Renovation",
    "startPrice": "RM 22,000",
    "icon": "house",
    "tagline": "End-to-end residential and commercial renovation: design, demolition, structural work, electrical, plumbing, painting, and handover. From RM 22,000.",
    "subServices": [
      {
        "name": "Full House Renovation Package"
      },
      {
        "name": "Partial House Renovation"
      },
      {
        "name": "Terrace House Renovation"
      },
      {
        "name": "Semi-D Renovation"
      },
      {
        "name": "Bungalow Renovation"
      },
      {
        "name": "Condo Interior Refurbishment"
      },
      {
        "name": "Apartment Renovation"
      },
      {
        "name": "Kitchen & Bathroom Makeover"
      },
      {
        "name": "House Extension"
      },
      {
        "name": "Commercial Shoplot Renovation"
      },
      {
        "name": "Office Renovation & Fit-Out"
      },
      {
        "name": "Retail Shop Renovation"
      },
      {
        "name": "Restaurant & F&B Renovation"
      },
      {
        "name": "Office Partition & Workspace Build"
      },
      {
        "name": "Renovation Contractor Services"
      }
    ],
    "warranty": "12-Month Structural & Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Pengubahsuaian Rumah Menyeluruh",
        "tagline": "Pengubahsuaian kediaman dan komersial hujung-ke-hujung: reka bentuk, perobohan, kerja struktur, elektrik, paip, pengecatan, dan serahan. Dari RM 22,000.",
        "subServices": [
          {
            "name": "Pakej Pengubahsuaian Rumah Penuh"
          },
          {
            "name": "Pengubahsuaian Separa Rumah"
          },
          {
            "name": "Pengubahsuaian Rumah Teres"
          },
          {
            "name": "Pengubahsuaian Semi-D"
          },
          {
            "name": "Pengubahsuaian Banglo"
          },
          {
            "name": "Pemulihan Interior Kondominium"
          },
          {
            "name": "Pengubahsuaian Apartmen"
          },
          {
            "name": "Makeover Dapur & Bilik Mandi"
          },
          {
            "name": "Sambungan Rumah"
          },
          {
            "name": "Pengubahsuaian Shoplot Komersial"
          },
          {
            "name": "Pengubahsuaian & Fit-Out Pejabat"
          },
          {
            "name": "Pengubahsuaian Kedai Runcit"
          },
          {
            "name": "Pengubahsuaian Restoran & F&B"
          },
          {
            "name": "Partisi Pejabat & Pembinaan Ruang Kerja"
          },
          {
            "name": "Perkhidmatan Kontraktor Pengubahsuaian"
          }
        ],
        "warranty": "Jaminan Struktur & Kerja 12 Bulan"
      },
      "zh": {
        "title": "全屋翻新服务",
        "tagline": "端到端的住宅与商业翻新：设计、拆除、结构、水电、瓦工、木工、油漆与交付。从 RM 22,000 起。",
        "subServices": [
          {
            "name": "全屋翻新配套"
          },
          {
            "name": "局部房屋翻新"
          },
          {
            "name": "排屋翻新"
          },
          {
            "name": "半独立式翻新"
          },
          {
            "name": "独栋洋房翻新"
          },
          {
            "name": "公寓室内翻新"
          },
          {
            "name": "公寓单元翻新"
          },
          {
            "name": "厨房与卫生间翻新"
          },
          {
            "name": "房屋扩建"
          },
          {
            "name": "商业店铺翻新"
          },
          {
            "name": "办公室装修与整备"
          },
          {
            "name": "零售店面装修"
          },
          {
            "name": "餐厅与餐饮门店装修"
          },
          {
            "name": "办公室隔断与工位搭建"
          },
          {
            "name": "翻新承包商服务"
          }
        ],
        "warranty": "12 个月结构与工艺保修"
      }
    }
  },
  "electrical": {
    "slug": "electrical",
    "title": "Licensed Electrical Services",
    "startPrice": "RM 280",
    "icon": "zap",
    "tagline": "Wiring, DB box upgrades, power point and switch installation, ceiling fan and lighting point setup by ST-licensed electricians. From RM 280.",
    "subServices": [
      {
        "name": "New Power Point & Switch Installation"
      },
      {
        "name": "DB Box Upgrade & Rewiring"
      },
      {
        "name": "Lighting Point & Downlight Installation"
      },
      {
        "name": "Aircond, Water Heater & Oven Point"
      },
      {
        "name": "House Rewiring"
      },
      {
        "name": "Additional Power Points"
      },
      {
        "name": "Switch Installation"
      },
      {
        "name": "Kitchen Electrical"
      },
      {
        "name": "Bathroom Electrical"
      },
      {
        "name": "Renovation Electrical Work"
      }
    ],
    "warranty": "12-Month Electrical Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Elektrik Berlesen",
        "tagline": "Pendawaian, naik taraf DB box, pemasangan power point dan suis, titik kipas siling dan pencahayaan oleh juruelektrik berdaftar ST. Dari RM 280.",
        "subServices": [
          {
            "name": "Pemasangan Power Point & Suis Baru"
          },
          {
            "name": "Naik Taraf DB Box & Pendawaian Semula"
          },
          {
            "name": "Titik Pencahayaan & Downlight"
          },
          {
            "name": "Titik Aircond, Pemanas Air & Ketuhar"
          },
          {
            "name": "Pendawaian Semula Rumah"
          },
          {
            "name": "Power Point Tambahan"
          },
          {
            "name": "Pemasangan Suis"
          },
          {
            "name": "Elektrik Dapur"
          },
          {
            "name": "Elektrik Bilik Mandi"
          },
          {
            "name": "Kerja Elektrik Pengubahsuaian"
          }
        ],
        "warranty": "Jaminan Kerja Elektrik 12 Bulan"
      },
      "zh": {
        "title": "持牌电工服务",
        "tagline": "由 ST 注册电工承接的布线、配电箱升级、插座与开关安装、吊扇与照明点位。从 RM 280 起。",
        "subServices": [
          {
            "name": "新增插座与开关安装"
          },
          {
            "name": "配电箱升级与重新布线"
          },
          {
            "name": "照明与筒灯点位安装"
          },
          {
            "name": "空调、热水器与烤箱点位"
          },
          {
            "name": "全屋重新布线"
          },
          {
            "name": "新增电源插座"
          },
          {
            "name": "开关安装"
          },
          {
            "name": "厨房电路"
          },
          {
            "name": "卫生间电路"
          },
          {
            "name": "装修电气工程"
          }
        ],
        "warranty": "12 个月电工工艺保修"
      }
    }
  },
  "water-heater": {
    "slug": "water-heater",
    "title": "Water Heater Installation & Repair",
    "startPrice": "RM 180",
    "icon": "flame",
    "tagline": "Instant, storage, and heat-pump water heater supply, installation, repair, and descaling by ST-licensed technicians. From RM 180.",
    "subServices": [
      {
        "name": "Instant Water Heater Installation"
      },
      {
        "name": "Storage Tank Heater Installation"
      },
      {
        "name": "Water Heater Repair & Descaling"
      },
      {
        "name": "Heat Pump Water Heater Install"
      }
    ],
    "warranty": "12-Month Installation Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Pemasangan & Pembaikan Pemanas Air",
        "tagline": "Bekalan, pemasangan, pembaikan dan nyahkerak pemanas air segera, tangki simpanan dan pam haba oleh juruteknik berlesen ST. Dari RM 180.",
        "subServices": [
          {
            "name": "Pemasangan Pemanas Air Segera"
          },
          {
            "name": "Pemasangan Pemanas Tangki Simpanan"
          },
          {
            "name": "Pembaikan & Nyahkerak Pemanas Air"
          },
          {
            "name": "Pemasangan Pemanas Air Pam Haba"
          }
        ],
        "warranty": "Jaminan Kerja Pemasangan 12 Bulan"
      },
      "zh": {
        "title": "热水器安装与维修",
        "tagline": "由 ST 持牌技师提供即热式、储水式与热泵热水器的供应、安装、维修与除垢。从 RM 180 起。",
        "subServices": [
          {
            "name": "即热式热水器安装"
          },
          {
            "name": "储水式热水器安装"
          },
          {
            "name": "热水器维修与除垢"
          },
          {
            "name": "热泵热水器安装"
          }
        ],
        "warranty": "12 个月安装工艺保修"
      }
    }
  },
  "ceiling-fan": {
    "slug": "ceiling-fan",
    "title": "Ceiling Fan Installation & Replacement",
    "startPrice": "RM 150",
    "icon": "fan",
    "tagline": "Safe ceiling fan mounting on concrete, plaster ceiling, and condo false ceiling with proper fan hook, regulator, and concealed wiring. From RM 150.",
    "subServices": [
      {
        "name": "New Ceiling Fan Installation"
      },
      {
        "name": "Ceiling Fan Replacement"
      },
      {
        "name": "DC Motor Smart Fan Install"
      },
      {
        "name": "Industrial / Shoplot Fan Install"
      }
    ],
    "warranty": "12-Month Mounting & Wiring Warranty",
    "i18n": {
      "ms": {
        "title": "Pemasangan & Penggantian Kipas Siling",
        "tagline": "Pemasangan kipas siling yang selamat pada konkrit, siling plaster dan siling palsu kondominium dengan cangkuk kipas, regulator dan pendawaian tersembunyi yang betul. Dari RM 150.",
        "subServices": [
          {
            "name": "Pemasangan Kipas Siling Baru"
          },
          {
            "name": "Penggantian Kipas Siling"
          },
          {
            "name": "Pemasangan Kipas Pintar Motor DC"
          },
          {
            "name": "Pemasangan Kipas Industri / Lot Kedai"
          }
        ],
        "warranty": "Jaminan Pemasangan & Pendawaian 12 Bulan"
      },
      "zh": {
        "title": "吊扇安装与更换",
        "tagline": "在混凝土、石膏天花板与公寓吊顶上安全安装吊扇，配备合格的吊扇挂钩、调速器与隐蔽布线。从 RM 150 起。",
        "subServices": [
          {
            "name": "新吊扇安装"
          },
          {
            "name": "吊扇更换"
          },
          {
            "name": "直流电机智能吊扇安装"
          },
          {
            "name": "工业 / 店铺吊扇安装"
          }
        ],
        "warranty": "12 个月安装与布线保修"
      }
    }
  },
  "lighting": {
    "slug": "lighting",
    "title": "Lighting Design & Installation",
    "startPrice": "RM 120",
    "icon": "lightbulb",
    "tagline": "Downlight, track light, pendant, cove, and outdoor lighting design, supply, and installation by ST-licensed electricians. From RM 120 / point.",
    "subServices": [
      {
        "name": "LED Downlight Installation"
      },
      {
        "name": "Pendant & Chandelier Install"
      },
      {
        "name": "Cove & Strip LED Installation"
      },
      {
        "name": "Smart Lighting & Dimmer Retrofit"
      }
    ],
    "warranty": "12-Month Lighting Installation Warranty",
    "i18n": {
      "ms": {
        "title": "Reka Bentuk & Pemasangan Pencahayaan",
        "tagline": "Reka bentuk, bekalan dan pemasangan lampu downlight, track, pendant, cove dan luar oleh juruelektrik berlesen ST. Dari RM 120 / titik.",
        "subServices": [
          {
            "name": "Pemasangan Downlight LED"
          },
          {
            "name": "Pemasangan Pendant & Chandelier"
          },
          {
            "name": "Pemasangan LED Cove & Jalur"
          },
          {
            "name": "Retrofit Pencahayaan Pintar & Malap"
          }
        ],
        "warranty": "Jaminan Pemasangan Pencahayaan 12 Bulan"
      },
      "zh": {
        "title": "照明设计与安装",
        "tagline": "由 ST 持牌电工提供筒灯、轨道灯、吊灯、灯槽与户外照明的设计、供应与安装。从 RM 120 / 点位起。",
        "subServices": [
          {
            "name": "LED 筒灯安装"
          },
          {
            "name": "吊灯与枝形吊灯安装"
          },
          {
            "name": "灯槽与 LED 灯带安装"
          },
          {
            "name": "智能照明与调光改造"
          }
        ],
        "warranty": "12 个月照明安装保修"
      }
    }
  },
  "tiling": {
    "slug": "tiling",
    "title": "Professional Tiling & Tile Repair",
    "startPrice": "RM 14 / sq ft",
    "icon": "grid-3x3",
    "tagline": "Floor and wall tiling for new builds, renovations, and repairs. Homogeneous, porcelain, ceramic, mosaic, and large-format slabs. From RM 14 / sq ft.",
    "subServices": [
      {
        "name": "Floor Tiling Installation"
      },
      {
        "name": "Wall Tiling Installation"
      },
      {
        "name": "Floor Tile Replacement & Tile Hacking"
      },
      {
        "name": "Porcelain Tiles Installation"
      },
      {
        "name": "Ceramic Tiles Installation"
      },
      {
        "name": "Large-Format Slab Tiling"
      },
      {
        "name": "Mosaic Tiles Installation"
      },
      {
        "name": "Bathroom Tiling & Waterproofing"
      },
      {
        "name": "Kitchen Backsplash Tiling"
      },
      {
        "name": "Tile Repair & Re-Grouting"
      },
      {
        "name": "Floor Leveling & Self-Leveling"
      }
    ],
    "warranty": "12-Month Tile Adhesion & Grout Warranty",
    "i18n": {
      "ms": {
        "title": "Jubin & Pembaikan Jubin Profesional",
        "tagline": "Jubin lantai dan dinding untuk pembinaan baru, pengubahsuaian, dan pembaikan. Homogen, porselin, seramik, mozek, dan slab format besar. Dari RM 14 / kaki persegi.",
        "subServices": [
          {
            "name": "Pemasangan Jubin Lantai"
          },
          {
            "name": "Pemasangan Jubin Dinding"
          },
          {
            "name": "Penggantian Jubin & Pemecahan Jubin"
          },
          {
            "name": "Pemasangan Jubin Porselin"
          },
          {
            "name": "Pemasangan Jubin Seramik"
          },
          {
            "name": "Pemasangan Slab Format Besar"
          },
          {
            "name": "Pemasangan Jubin Mozek"
          },
          {
            "name": "Jubin Bilik Mandi & Kalis Air"
          },
          {
            "name": "Jubin Backsplash Dapur"
          },
          {
            "name": "Pembaikan Jubin & Grout Semula"
          },
          {
            "name": "Pemerataan Lantai & Self-Leveling"
          }
        ],
        "warranty": "Jaminan Lekatan Jubin & Grout 12 Bulan"
      },
      "zh": {
        "title": "专业瓷砖与瓷砖修补",
        "tagline": "新房、翻新与修补的地面和墙面瓷砖。瓷质、玻化、陶瓷、马赛克与超大板。从 RM 14 / 平方呎 起。",
        "subServices": [
          {
            "name": "地面瓷砖铺贴"
          },
          {
            "name": "墙面瓷砖铺贴"
          },
          {
            "name": "地面瓷砖更换与拆除"
          },
          {
            "name": "抛光砖铺贴"
          },
          {
            "name": "陶瓷砖铺贴"
          },
          {
            "name": "超大板铺贴"
          },
          {
            "name": "马赛克瓷砖铺贴"
          },
          {
            "name": "卫生间贴砖与防水"
          },
          {
            "name": "厨房挡水板贴砖"
          },
          {
            "name": "瓷砖修补与重新勾缝"
          },
          {
            "name": "地面找平与自流平"
          }
        ],
        "warranty": "12 个月瓷砖粘结与勾缝保修"
      }
    }
  },
  "plaster-ceiling": {
    "slug": "plaster-ceiling",
    "title": "Plaster Ceiling Design & Build",
    "startPrice": "RM 10 / sq ft",
    "icon": "layers",
    "tagline": "Modern plaster ceiling with concealed LED trough, tiered design, L-box, and cove lighting for landed and high-rise properties. From RM 10 / sq ft.",
    "subServices": [
      {
        "name": "Flat Plaster Ceiling"
      },
      {
        "name": "False Ceiling Installation"
      },
      {
        "name": "Gypsum Ceiling"
      },
      {
        "name": "Tiered & L-Box Ceiling"
      },
      {
        "name": "Cove & Curved Ceiling"
      },
      {
        "name": "Gypsum Partition & Office Partition"
      },
      {
        "name": "Room Partition"
      },
      {
        "name": "Feature Wall & Wall Panel"
      },
      {
        "name": "Skim Coat & Wall Plastering"
      },
      {
        "name": "Wall Crack Repair & Repainting"
      },
      {
        "name": "Ceiling Repair & Re-Skim"
      }
    ],
    "warranty": "10-Year Sag-Free & Crack-Free Warranty",
    "i18n": {
      "ms": {
        "title": "Reka Bentuk & Bina Siling Plaster Moden",
        "tagline": "Siling plaster moden dengan alur LED tersembunyi, reka bentuk bertingkat, L-box, dan pencahayaan cove untuk hartanah bertanah dan bertingkat tinggi. Dari RM 10 / kaki persegi.",
        "subServices": [
          {
            "name": "Siling Plaster Rata"
          },
          {
            "name": "Pemasangan Siling Palsu"
          },
          {
            "name": "Siling Gipsum"
          },
          {
            "name": "Siling Bertingkat & L-Box"
          },
          {
            "name": "Siling Cove & Melengkung"
          },
          {
            "name": "Partisi Gipsum & Partisi Pejabat"
          },
          {
            "name": "Partisi Bilik"
          },
          {
            "name": "Dinding Ciri & Panel Dinding"
          },
          {
            "name": "Skim Coat & Melepa Dinding"
          },
          {
            "name": "Pembaikan Retak Dinding & Mengecat Semula"
          },
          {
            "name": "Pembaikan & Skim Semula Siling"
          }
        ],
        "warranty": "Jaminan Bebas Lentur & Retak 10 Tahun"
      },
      "zh": {
        "title": "现代石膏天花板设计与施工",
        "tagline": "为有地与高层物业打造的现代石膏天花板，含隐藏式 LED 灯槽、错层、L 盒与灯带。从 RM 10 / 平方呎 起。",
        "subServices": [
          {
            "name": "平顶石膏天花"
          },
          {
            "name": "假天花安装"
          },
          {
            "name": "石膏板天花"
          },
          {
            "name": "错层与 L 盒天花"
          },
          {
            "name": "灯带与弧形天花"
          },
          {
            "name": "石膏隔断与办公室隔断"
          },
          {
            "name": "房间隔断"
          },
          {
            "name": "背景墙与墙板"
          },
          {
            "name": "刮腻子与墙面抹灰"
          },
          {
            "name": "墙面裂缝修补与重漆"
          },
          {
            "name": "天花修补与重新找平"
          }
        ],
        "warranty": "10 年防下垂与防开裂保修"
      }
    }
  },
  "skim-coat": {
    "slug": "skim-coat",
    "title": "Wall & Ceiling Skim Coat",
    "startPrice": "RM 5 / sq ft",
    "icon": "paint-roller",
    "tagline": "Glass-smooth skim coating for walls and ceilings, paint-ready finish, full surface preparation and crack repair. From RM 5 / sq ft.",
    "subServices": [
      {
        "name": "Wall Skim Coating"
      },
      {
        "name": "Ceiling Skim Coating"
      },
      {
        "name": "Crack & Joint Repair"
      },
      {
        "name": "Full Condo Re-Skim Package"
      }
    ],
    "warranty": "12-Month Smoothness & Adhesion Warranty",
    "i18n": {
      "ms": {
        "title": "Skim Coat Dinding & Siling",
        "tagline": "Salutan skim licin kaca untuk dinding dan siling, kemasan siap-cat, penyediaan permukaan penuh dan pembaikan retak. Dari RM 5 / kaki persegi.",
        "subServices": [
          {
            "name": "Salutan Skim Dinding"
          },
          {
            "name": "Salutan Skim Siling"
          },
          {
            "name": "Pembaikan Retak & Sendi"
          },
          {
            "name": "Pakej Skim Semula Kondominium Penuh"
          }
        ],
        "warranty": "Jaminan Kelicinan & Lekatan 12 Bulan"
      },
      "zh": {
        "title": "墙面与天花腻子",
        "tagline": "玻璃般光滑的墙面与天花腻子，可上漆的表面，全套基层处理与裂缝修补。从 RM 5 / 平方呎 起。",
        "subServices": [
          {
            "name": "墙面腻子"
          },
          {
            "name": "天花腻子"
          },
          {
            "name": "裂缝与接缝修补"
          },
          {
            "name": "整套公寓重刮腻子配套"
          }
        ],
        "warranty": "12 个月平整度与粘结保修"
      }
    }
  },
  "flooring": {
    "slug": "flooring",
    "title": "Vinyl, SPC & Laminate Flooring",
    "startPrice": "RM 14 / sq ft",
    "icon": "square",
    "tagline": "Modern click-lock flooring for homes and offices. Waterproof SPC, scratch-resistant laminate, and luxury vinyl planks. From RM 14 / sq ft.",
    "subServices": [
      {
        "name": "SPC Click-Lock Flooring Install"
      },
      {
        "name": "Laminate Flooring Install"
      },
      {
        "name": "Luxury Vinyl Plank (LVP) Install"
      },
      {
        "name": "Vinyl Flooring Installation"
      },
      {
        "name": "Floor Tile Installation"
      },
      {
        "name": "Floor Tile Replacement & Subfloor Hacking"
      },
      {
        "name": "Porcelain & Ceramic Tiles"
      },
      {
        "name": "Large Format & Mosaic Tiles"
      },
      {
        "name": "Floor Leveling & Screeding"
      },
      {
        "name": "Hollow Tile & Uneven Floor Repair"
      },
      {
        "name": "Skirting & Transition Strip Fitting"
      }
    ],
    "warranty": "5-Year Installation Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Lantai Vinyl, SPC & Laminate",
        "tagline": "Lantai click-lock moden untuk rumah dan pejabat. SPC kalis air, laminate tahan calar dan papan vinyl mewah. Dari RM 14 / kaki persegi.",
        "subServices": [
          {
            "name": "Pemasangan Lantai SPC Click-Lock"
          },
          {
            "name": "Pemasangan Lantai Laminate"
          },
          {
            "name": "Pemasangan Papan Vinyl Mewah (LVP)"
          },
          {
            "name": "Pemasangan Lantai Vinyl"
          },
          {
            "name": "Pemasangan Jubin Lantai"
          },
          {
            "name": "Penggantian Jubin Lantai & Pemecahan Subfloor"
          },
          {
            "name": "Jubin Porselin & Seramik"
          },
          {
            "name": "Jubin Format Besar & Mozek"
          },
          {
            "name": "Pemerataan Lantai & Screed"
          },
          {
            "name": "Pembaikan Jubin Berongga & Lantai Tidak Rata"
          },
          {
            "name": "Pemasangan Skirting & Jalur Peralihan"
          }
        ],
        "warranty": "Jaminan Kerja Pemasangan 5 Tahun"
      },
      "zh": {
        "title": "Vinyl、SPC 与复合地板",
        "tagline": "适用于家庭与办公室的现代锁扣地板。防水 SPC、耐磨复合地板与豪华乙烯基地板。从 RM 14 / 平方英尺起。",
        "subServices": [
          {
            "name": "SPC 锁扣地板安装"
          },
          {
            "name": "复合地板安装"
          },
          {
            "name": "豪华乙烯基地板 (LVP) 安装"
          },
          {
            "name": "乙烯基地板安装"
          },
          {
            "name": "地面瓷砖安装"
          },
          {
            "name": "地面瓷砖更换与基层拆除"
          },
          {
            "name": "抛光砖与陶瓷砖"
          },
          {
            "name": "大板与马赛克瓷砖"
          },
          {
            "name": "地面找平与地台"
          },
          {
            "name": "空鼓砖与不平地面维修"
          },
          {
            "name": "踢脚线与收边条安装"
          }
        ],
        "warranty": "5 年安装工艺保修"
      }
    }
  },
  "epoxy-flooring": {
    "slug": "epoxy-flooring",
    "title": "Epoxy & Polyurethane Flooring",
    "startPrice": "RM 22 / sq ft",
    "icon": "circle-dot",
    "tagline": "Heavy-duty epoxy floor coating for garages, warehouses, factories, showrooms, and commercial kitchens. From RM 22 / sq ft.",
    "subServices": [
      {
        "name": "Self-Levelling Epoxy Floor"
      },
      {
        "name": "Flake / Quartz Broadcast Epoxy"
      },
      {
        "name": "Heavy-Duty Mortar Screed"
      },
      {
        "name": "Epoxy Floor Repair & Recoating"
      }
    ],
    "warranty": "5-Year Delamination & Yellowing Warranty",
    "i18n": {
      "ms": {
        "title": "Lantai Epoxy & Polyurethane",
        "tagline": "Salutan lantai epoxy tugas berat untuk garaj, gudang, kilang, bilik pameran dan dapur komersial. Dari RM 22 / kaki persegi.",
        "subServices": [
          {
            "name": "Lantai Epoxy Rata-Sendiri"
          },
          {
            "name": "Epoxy Taburan Flake / Kuarza"
          },
          {
            "name": "Mortar Screed Tugas Berat"
          },
          {
            "name": "Pembaikan & Salutan Semula Lantai Epoxy"
          }
        ],
        "warranty": "Jaminan Delaminasi & Penguningan 5 Tahun"
      },
      "zh": {
        "title": "环氧与聚氨酯地坪",
        "tagline": "适用于车库、仓库、工厂、展厅与商业厨房的重型环氧地坪涂层。从 RM 22 / 平方英尺起。",
        "subServices": [
          {
            "name": "自流平环氧地坪"
          },
          {
            "name": "彩片 / 石英撒砂环氧"
          },
          {
            "name": "重型砂浆面层"
          },
          {
            "name": "环氧地坪维修与翻新"
          }
        ],
        "warranty": "5 年脱层与黄变保修"
      }
    }
  },
  "roof-repair": {
    "slug": "roof-repair",
    "title": "Roof Repair & Waterproofing",
    "startPrice": "RM 380",
    "icon": "home",
    "tagline": "Roof tile replacement, leak repair, gutter cleaning, flashing, and full torch-on waterproofing for landed properties. From RM 380.",
    "subServices": [
      {
        "name": "Roof Leak Diagnosis & Repair"
      },
      {
        "name": "Ridge Re-Bedding & Re-Pointing"
      },
      {
        "name": "Gutter Cleaning & Realignment"
      },
      {
        "name": "Full Torch-On Membrane Waterproofing"
      }
    ],
    "warranty": "10-Year Membrane & Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Pembaikan & Kalis Air Bumbung",
        "tagline": "Penggantian jubin bumbung, pembaikan bocor, pembersihan longkang, flashing dan kalis air torch-on penuh untuk hartanah bertanah. Dari RM 380.",
        "subServices": [
          {
            "name": "Diagnosis & Pembaikan Bocor Bumbung"
          },
          {
            "name": "Re-Bedding & Re-Pointing Rabung"
          },
          {
            "name": "Pembersihan & Penjajaran Semula Longkang"
          },
          {
            "name": "Kalis Air Membran Torch-On Penuh"
          }
        ],
        "warranty": "Jaminan Membran & Kerja 10 Tahun"
      },
      "zh": {
        "title": "屋顶维修与防水",
        "tagline": "有地物业的屋瓦更换、漏水维修、天沟清理、泛水板与全烤贴式防水。从 RM 380 起。",
        "subServices": [
          {
            "name": "屋顶漏水诊断与维修"
          },
          {
            "name": "屋脊重新铺浆与勾缝"
          },
          {
            "name": "天沟清理与调坡"
          },
          {
            "name": "全烤贴式卷材防水"
          }
        ],
        "warranty": "10 年卷材与工艺保修"
      }
    }
  },
  "kitchen-cabinet": {
    "slug": "kitchen-cabinet",
    "title": "Kitchen Cabinet & Countertop",
    "startPrice": "RM 7,500",
    "icon": "utensils",
    "tagline": "Custom-built and modular kitchen cabinets with stone, solid surface, or laminate countertops. Design, supply, install. From RM 7,500.",
    "subServices": [
      {
        "name": "Modular Kitchen Cabinet (10ft L-shape)"
      },
      {
        "name": "Custom Plywood Kitchen"
      },
      {
        "name": "Quartz / Granite Countertop"
      },
      {
        "name": "Kitchen Makeover (Doors & Hardware Only)"
      }
    ],
    "warranty": "5-Year Cabinet Structure Warranty",
    "i18n": {
      "ms": {
        "title": "Kabinet Dapur & Permukaan Kaunter",
        "tagline": "Kabinet dapur kustom dan modular dengan permukaan kaunter batu, solid surface atau laminate. Reka bentuk, bekalan, pemasangan. Dari RM 7,500.",
        "subServices": [
          {
            "name": "Kabinet Dapur Modular (L-shape 10 kaki)"
          },
          {
            "name": "Dapur Papan Lapis Kustom"
          },
          {
            "name": "Permukaan Kaunter Kuarza / Granit"
          },
          {
            "name": "Makeover Dapur (Pintu & Perkakasan Sahaja)"
          }
        ],
        "warranty": "Jaminan Struktur Kabinet 5 Tahun"
      },
      "zh": {
        "title": "厨房橱柜与台面",
        "tagline": "定制与模块化厨房橱柜，配石材、实体面材或防火板台面。设计、供应、安装。从 RM 7,500 起。",
        "subServices": [
          {
            "name": "模块化厨房橱柜（10 英尺 L 型）"
          },
          {
            "name": "定制胶合板厨房"
          },
          {
            "name": "石英石 / 花岗岩台面"
          },
          {
            "name": "厨房翻新（仅门板与五金）"
          }
        ],
        "warranty": "5 年柜体结构保修"
      }
    }
  },
  "carpentry": {
    "slug": "carpentry",
    "title": "Custom Carpentry & Joinery",
    "startPrice": "RM 300",
    "icon": "ruler",
    "tagline": "Built-in wardrobes, TV consoles, study desks, feature walls, shoe racks, and custom furniture. From RM 300 / linier ft.",
    "subServices": [
      {
        "name": "Built-in Wardrobe"
      },
      {
        "name": "TV Console & Feature Wall"
      },
      {
        "name": "Study Desk & Home Office"
      },
      {
        "name": "Shoe Cabinet & Entry Storage"
      },
      {
        "name": "Walk-in Wardrobe & Closet System"
      },
      {
        "name": "Vanity Cabinet & Dressing Table"
      },
      {
        "name": "Storage Cabinet & Display Shelving"
      },
      {
        "name": "Feature Wall & Wall Panelling"
      },
      {
        "name": "Dining Bench & Banquette Seating"
      },
      {
        "name": "Wardrobe & Cabinet Repair"
      }
    ],
    "warranty": "5-Year Cabinet Structure Warranty",
    "i18n": {
      "ms": {
        "title": "Pertukangan & Kerja Kayu Kustom",
        "tagline": "Almari pakaian tanam, konsol TV, meja belajar, dinding feature, rak kasut dan perabot kustom. Dari RM 300 / kaki linier.",
        "subServices": [
          {
            "name": "Almari Pakaian Tanam"
          },
          {
            "name": "Konsol TV & Dinding Feature"
          },
          {
            "name": "Meja Belajar & Pejabat Rumah"
          },
          {
            "name": "Kabinet Kasut & Storan Pintu Masuk"
          },
          {
            "name": "Walk-in Wardrobe & Sistem Closet"
          },
          {
            "name": "Kabinet Vanity & Meja Solek"
          },
          {
            "name": "Kabinet Storan & Rak Pameran"
          },
          {
            "name": "Dinding Feature & Panel Dinding"
          },
          {
            "name": "Bangku Makan & Tempat Duduk Banquette"
          },
          {
            "name": "Pembaikan Almari & Kabinet"
          }
        ],
        "warranty": "Jaminan Struktur Kabinet 5 Tahun"
      },
      "zh": {
        "title": "定制木工与细木作",
        "tagline": "定制入墙衣柜、电视柜、书桌、背景墙、鞋柜与定制家具。从 RM 300 / 延英尺起。",
        "subServices": [
          {
            "name": "入墙衣柜"
          },
          {
            "name": "电视柜与背景墙"
          },
          {
            "name": "书桌与家庭办公"
          },
          {
            "name": "鞋柜与玄关收纳"
          },
          {
            "name": "步入式衣帽间与衣橱系统"
          },
          {
            "name": "浴室柜与梳妆台"
          },
          {
            "name": "储物柜与展示架"
          },
          {
            "name": "背景墙与护墙板"
          },
          {
            "name": "餐椅长凳与卡座"
          },
          {
            "name": "衣柜与柜体维修"
          }
        ],
        "warranty": "5 年柜体结构保修"
      }
    }
  },
  "door": {
    "slug": "door",
    "title": "Door Repair & Installation",
    "startPrice": "RM 250",
    "icon": "door-open",
    "tagline": "Solid timber, engineered, fire-rated, and laminate doors — supply, install, plane, hinge, and lock fitting. From RM 250.",
    "subServices": [
      {
        "name": "Solid Timber Door Installation"
      },
      {
        "name": "Laminate Door Installation"
      },
      {
        "name": "Door Planing & Adjustment"
      },
      {
        "name": "Fire-Rated Door Installation"
      },
      {
        "name": "Door Replacement"
      },
      {
        "name": "Door Frame Repair & Replacement"
      },
      {
        "name": "Bathroom & Kitchen PVC Door Replacement"
      },
      {
        "name": "Sliding & Bi-Fold Door Installation"
      },
      {
        "name": "Main Entrance Door Installation"
      },
      {
        "name": "Door Closer & Hardware Installation"
      }
    ],
    "warranty": "12-Month Door Hanging & Hardware Warranty",
    "i18n": {
      "ms": {
        "title": "Pembaikan & Pemasangan Pintu",
        "tagline": "Pintu kayu pepejal, engineered, tahan api dan laminate — bekalan, pemasangan, ketam, engsel dan pemasangan kunci. Dari RM 250.",
        "subServices": [
          {
            "name": "Pemasangan Pintu Kayu Pepejal"
          },
          {
            "name": "Pemasangan Pintu Laminate"
          },
          {
            "name": "Ketam & Pelarasan Pintu"
          },
          {
            "name": "Pemasangan Pintu Tahan Api"
          },
          {
            "name": "Penggantian Pintu"
          },
          {
            "name": "Pembaikan & Penggantian Bingkai Pintu"
          },
          {
            "name": "Penggantian Pintu PVC Bilik Mandi & Dapur"
          },
          {
            "name": "Pemasangan Pintu Gelangsar & Bi-Fold"
          },
          {
            "name": "Pemasangan Pintu Utama"
          },
          {
            "name": "Pemasangan Door Closer & Perkakasan"
          }
        ],
        "warranty": "Jaminan Gantungan Pintu & Perkakasan 12 Bulan"
      },
      "zh": {
        "title": "门维修与安装",
        "tagline": "实木、工程木、防火与防火板门——供应、安装、刨修、铰链与锁具安装。从 RM 250 起。",
        "subServices": [
          {
            "name": "实木门安装"
          },
          {
            "name": "防火板门安装"
          },
          {
            "name": "门刨修与调校"
          },
          {
            "name": "防火门安装"
          },
          {
            "name": "门扇更换"
          },
          {
            "name": "门框维修与更换"
          },
          {
            "name": "厨卫 PVC 门更换"
          },
          {
            "name": "推拉门与折叠门安装"
          },
          {
            "name": "入户大门安装"
          },
          {
            "name": "闭门器与五金安装"
          }
        ],
        "warranty": "12 个月门扇安装与五金保修"
      }
    }
  },
  "window-repair": {
    "slug": "window-repair",
    "title": "Window Repair & Glass Replacement",
    "startPrice": "RM 200",
    "icon": "square-stack",
    "tagline": "Casement, sliding, top-hung, awning windows — glass replacement, seal repair, handle replacement, and alignment. From RM 200.",
    "subServices": [
      {
        "name": "Glass Replacement"
      },
      {
        "name": "Window Seal Replacement"
      },
      {
        "name": "Window Handle & Hinge Repair"
      },
      {
        "name": "Sliding Window Roller Replacement"
      },
      {
        "name": "Window Installation"
      },
      {
        "name": "Window Replacement"
      },
      {
        "name": "Window Grille Installation"
      },
      {
        "name": "Window Frame Repair & Realignment"
      },
      {
        "name": "Louvre & Top-Hung Window Repair"
      },
      {
        "name": "Window Waterproofing & Resealing"
      }
    ],
    "warranty": "12-Month Hardware & Seal Warranty",
    "i18n": {
      "ms": {
        "title": "Pembaikan Tingkap & Penggantian Kaca",
        "tagline": "Tingkap casement, gelangsar, top-hung, awning — penggantian kaca, pembaikan pengedap, penggantian pemegang dan penjajaran. Dari RM 200.",
        "subServices": [
          {
            "name": "Penggantian Kaca"
          },
          {
            "name": "Penggantian Pengedap Tingkap"
          },
          {
            "name": "Pembaikan Pemegang & Engsel Tingkap"
          },
          {
            "name": "Penggantian Roller Tingkap Gelangsar"
          },
          {
            "name": "Pemasangan Tingkap"
          },
          {
            "name": "Penggantian Tingkap"
          },
          {
            "name": "Pemasangan Grill Tingkap"
          },
          {
            "name": "Pembaikan & Penjajaran Bingkai Tingkap"
          },
          {
            "name": "Pembaikan Tingkap Louvre & Top-Hung"
          },
          {
            "name": "Kalis Air & Pengedapan Semula Tingkap"
          }
        ],
        "warranty": "Jaminan Perkakasan & Pengedap 12 Bulan"
      },
      "zh": {
        "title": "窗户维修与玻璃更换",
        "tagline": "平开窗、推拉窗、上悬窗、外开下悬窗——玻璃更换、密封条维修、执手更换与调校。从 RM 200 起。",
        "subServices": [
          {
            "name": "玻璃更换"
          },
          {
            "name": "窗户密封条更换"
          },
          {
            "name": "窗户执手与铰链维修"
          },
          {
            "name": "推拉窗滑轮更换"
          },
          {
            "name": "窗户安装"
          },
          {
            "name": "窗户更换"
          },
          {
            "name": "窗户防盗网安装"
          },
          {
            "name": "窗框维修与校正"
          },
          {
            "name": "百叶窗与上悬窗维修"
          },
          {
            "name": "窗户防水与重新打胶"
          }
        ],
        "warranty": "12 个月五金与密封保修"
      }
    }
  },
  "locksmith": {
    "slug": "locksmith",
    "title": "Locksmith & Smart Lock Services",
    "startPrice": "RM 180",
    "icon": "key",
    "tagline": "Digital smart locks, key cutting, lock replacement, door reinforcement, and emergency lockout service. From RM 180.",
    "subServices": [
      {
        "name": "Smart Lock Installation"
      },
      {
        "name": "Mortice / Deadbolt Lock Replacement"
      },
      {
        "name": "Key Cutting & Re-Keying"
      },
      {
        "name": "Emergency Lockout (Landed House)"
      }
    ],
    "warranty": "12-Month Lock Installation & Hardware Warranty",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Tukang Kunci & Kunci Pintar",
        "tagline": "Kunci pintar digital, pemotongan kunci, penggantian kunci, pengukuhan pintu dan perkhidmatan kecemasan terkunci. Dari RM 180.",
        "subServices": [
          {
            "name": "Pemasangan Kunci Pintar"
          },
          {
            "name": "Penggantian Kunci Mortice / Deadbolt"
          },
          {
            "name": "Pemotongan Kunci & Re-Key"
          },
          {
            "name": "Kecemasan Terkunci (Rumah Landed)"
          }
        ],
        "warranty": "Jaminan Pemasangan Kunci & Perkakasan 12 Bulan"
      },
      "zh": {
        "title": "锁匠与智能锁服务",
        "tagline": "数字智能锁、配钥匙、换锁、门体加固与紧急开锁服务。从 RM 180 起。",
        "subServices": [
          {
            "name": "智能锁安装"
          },
          {
            "name": "执手锁 / 呆锁更换"
          },
          {
            "name": "配钥匙与换锁芯"
          },
          {
            "name": "紧急开锁（有地住宅）"
          }
        ],
        "warranty": "12 个月锁具安装与五金保修"
      }
    }
  },
  "glass-aluminium": {
    "slug": "glass-aluminium",
    "title": "Glass & Aluminium Fabrication",
    "startPrice": "RM 320",
    "icon": "panel-top",
    "tagline": "Shower screens, glass partitions, aluminium windows, sliding doors, and mirror installation across KL & Selangor. From RM 320.",
    "subServices": [
      {
        "name": "Frameless Shower Screen"
      },
      {
        "name": "Aluminium Sliding Window"
      },
      {
        "name": "Glass Office Partition"
      },
      {
        "name": "Wall Mirror Installation"
      },
      {
        "name": "Glass Partition"
      },
      {
        "name": "Sliding Glass Door"
      },
      {
        "name": "Aluminium Casement Window"
      },
      {
        "name": "Glass Railing & Balustrade"
      },
      {
        "name": "Aluminium Composite Panel Cladding"
      },
      {
        "name": "Glass Repair & Reglazing"
      }
    ],
    "warranty": "12-Month Leak-Free & Hardware Warranty",
    "i18n": {
      "ms": {
        "title": "Fabrikasi Kaca & Aluminium",
        "tagline": "Skrin pancuran, partition kaca, tingkap aluminium, pintu gelangsar dan pemasangan cermin di seluruh KL & Selangor. Dari RM 320.",
        "subServices": [
          {
            "name": "Skrin Pancuran Tanpa Bingkai"
          },
          {
            "name": "Tingkap Gelangsar Aluminium"
          },
          {
            "name": "Partition Pejabat Kaca"
          },
          {
            "name": "Pemasangan Cermin Dinding"
          },
          {
            "name": "Partition Kaca"
          },
          {
            "name": "Pintu Kaca Gelangsar"
          },
          {
            "name": "Tingkap Casement Aluminium"
          },
          {
            "name": "Railing & Balustrade Kaca"
          },
          {
            "name": "Cladding Panel Komposit Aluminium"
          },
          {
            "name": "Pembaikan Kaca & Reglazing"
          }
        ],
        "warranty": "Jaminan Bebas Bocor & Perkakasan 12 Bulan"
      },
      "zh": {
        "title": "玻璃与铝业工程",
        "tagline": "吉隆坡与雪兰莪的淋浴屏、玻璃隔断、铝合金窗、推拉门与镜子安装。从 RM 320 起。",
        "subServices": [
          {
            "name": "无框淋浴屏"
          },
          {
            "name": "铝合金推拉窗"
          },
          {
            "name": "玻璃办公隔断"
          },
          {
            "name": "墙镜安装"
          },
          {
            "name": "玻璃隔断"
          },
          {
            "name": "推拉玻璃门"
          },
          {
            "name": "铝合金平开窗"
          },
          {
            "name": "玻璃栏杆与护栏"
          },
          {
            "name": "铝塑板幕墙饰面"
          },
          {
            "name": "玻璃维修与换玻"
          }
        ],
        "warranty": "12 个月防漏与五金保修"
      }
    }
  },
  "cctv": {
    "slug": "cctv",
    "title": "CCTV & Security Camera Installation",
    "startPrice": "RM 420",
    "icon": "camera",
    "tagline": "Hikvision, Dahua, Ezviz, TP-Link, Tuya CCTV supply, install, network setup, and remote viewing. From RM 420 / camera.",
    "subServices": [
      {
        "name": "Condo Wi-Fi CCTV Package (4 cameras)"
      },
      {
        "name": "Landed House PoE CCTV (8 cameras)"
      },
      {
        "name": "Single Camera Add-On"
      },
      {
        "name": "CCTV System Health Check & Relocation"
      }
    ],
    "warranty": "12-Month Camera & Installation Warranty",
    "i18n": {
      "ms": {
        "title": "Pemasangan CCTV & Kamera Keselamatan",
        "tagline": "Bekalan, pemasangan, persediaan rangkaian dan tontonan jauh CCTV Hikvision, Dahua, Ezviz, TP-Link, Tuya. Dari RM 420 / kamera.",
        "subServices": [
          {
            "name": "Pakej CCTV Wi-Fi Kondominium (4 kamera)"
          },
          {
            "name": "CCTV PoE Rumah Landed (8 kamera)"
          },
          {
            "name": "Tambahan Kamera Tunggal"
          },
          {
            "name": "Pemeriksaan Kesihatan & Pemindahan Sistem CCTV"
          }
        ],
        "warranty": "Jaminan Kamera & Pemasangan 12 Bulan"
      },
      "zh": {
        "title": "CCTV 与监控摄像头安装",
        "tagline": "Hikvision、Dahua、Ezviz、TP-Link、Tuya 监控的供应、安装、网络设置与远程查看。从 RM 420 / 台起。",
        "subServices": [
          {
            "name": "公寓 Wi-Fi 监控套餐（4 台）"
          },
          {
            "name": "有地住宅 PoE 监控（8 台）"
          },
          {
            "name": "单台加装摄像头"
          },
          {
            "name": "监控系统健康检查与移机"
          }
        ],
        "warranty": "12 个月摄像头与安装保修"
      }
    }
  },
  "autogate": {
    "slug": "autogate",
    "title": "Auto Gate & Motorised Gate",
    "startPrice": "RM 2,200",
    "icon": "move",
    "tagline": "Swing, sliding, and folding autogate supply, install, and motor servicing across KL & Selangor. From RM 2,200.",
    "subServices": [
      {
        "name": "Single Swing Autogate"
      },
      {
        "name": "Double Swing Autogate"
      },
      {
        "name": "Sliding Autogate"
      },
      {
        "name": "Autogate Motor Replacement & Service"
      }
    ],
    "warranty": "12-Month Motor & Installation Warranty",
    "i18n": {
      "ms": {
        "title": "Autogate & Pagar Bermotor",
        "tagline": "Bekalan, pemasangan dan servis motor autogate hayun, gelangsar dan lipat di seluruh KL & Selangor. Dari RM 2,200.",
        "subServices": [
          {
            "name": "Autogate Hayun Tunggal"
          },
          {
            "name": "Autogate Hayun Berkembar"
          },
          {
            "name": "Autogate Gelangsar"
          },
          {
            "name": "Penggantian & Servis Motor Autogate"
          }
        ],
        "warranty": "Jaminan Motor & Pemasangan 12 Bulan"
      },
      "zh": {
        "title": "电动门与自动门系统",
        "tagline": "吉隆坡与雪兰莪平开、推拉与折叠电动门的供应、安装与电机保养。从 RM 2,200 起。",
        "subServices": [
          {
            "name": "单开平开电动门"
          },
          {
            "name": "双开平开电动门"
          },
          {
            "name": "推拉电动门"
          },
          {
            "name": "电动门电机更换与保养"
          }
        ],
        "warranty": "12 个月电机与安装保修"
      }
    }
  },
  "welding": {
    "slug": "welding",
    "title": "Welding & Metal Fabrication",
    "startPrice": "RM 280",
    "icon": "welding-spark",
    "tagline": "Custom grilles, gates, structural repair, staircase fabrication, and on-site welding across KL & Selangor. From RM 280.",
    "subServices": [
      {
        "name": "Custom Window Grille"
      },
      {
        "name": "Main Gate Fabrication"
      },
      {
        "name": "On-Site Welding Repair"
      },
      {
        "name": "Staircase Stringer Fabrication"
      },
      {
        "name": "Iron Works"
      },
      {
        "name": "Metal Grille Installation"
      },
      {
        "name": "Metal Gate Repair"
      },
      {
        "name": "Stainless Steel Railing Fabrication"
      },
      {
        "name": "Steel Structure & Awning Fabrication"
      },
      {
        "name": "Anti-Rust Treatment & Repainting"
      }
    ],
    "warranty": "12-Month Welding & Fabrication Warranty",
    "i18n": {
      "ms": {
        "title": "Kimpalan & Fabrikasi Logam",
        "tagline": "Grilles kustom, pagar, pembaikan struktur, fabrikasi tangga dan kimpalan di tapak di seluruh KL & Selangor. Dari RM 280.",
        "subServices": [
          {
            "name": "Grille Tingkap Kustom"
          },
          {
            "name": "Fabrikasi Pagar Utama"
          },
          {
            "name": "Pembaikan Kimpalan Di Tapak"
          },
          {
            "name": "Fabrikasi Stringer Tangga"
          },
          {
            "name": "Kerja Besi"
          },
          {
            "name": "Pemasangan Grill Logam"
          },
          {
            "name": "Pembaikan Pagar Logam"
          },
          {
            "name": "Fabrikasi Railing Keluli Tahan Karat"
          },
          {
            "name": "Fabrikasi Struktur Keluli & Awning"
          },
          {
            "name": "Rawatan Kalis Karat & Cat Semula"
          }
        ],
        "warranty": "Jaminan Kimpalan & Fabrikasi 12 Bulan"
      },
      "zh": {
        "title": "焊接与金属加工",
        "tagline": "吉隆坡与雪兰莪的定制防护格栅、大门、结构维修、楼梯制作与现场焊接。从 RM 280 起。",
        "subServices": [
          {
            "name": "定制窗户防护格栅"
          },
          {
            "name": "大门定制"
          },
          {
            "name": "现场焊接维修"
          },
          {
            "name": "楼梯龙骨制作"
          },
          {
            "name": "铁艺工程"
          },
          {
            "name": "金属格栅安装"
          },
          {
            "name": "金属大门维修"
          },
          {
            "name": "不锈钢栏杆制作"
          },
          {
            "name": "钢结构与雨棚制作"
          },
          {
            "name": "除锈处理与重新喷漆"
          }
        ],
        "warranty": "12 个月焊接与加工保修"
      }
    }
  },
  "aircon": {
    "slug": "aircon",
    "title": "Aircon Service, Repair & Installation",
    "startPrice": "RM 129",
    "icon": "snowflake",
    "tagline": "Air-conditioner basic servicing, chemical wash, chemical overhaul, gas top-up, repair, new installation and dismantling for homes and offices across KL & Selangor. From RM 129.",
    "subServices": [
      {
        "name": "Basic Servicing"
      },
      {
        "name": "Chemical Wash"
      },
      {
        "name": "Chemical Overhaul"
      },
      {
        "name": "Gas Top-Up"
      },
      {
        "name": "Installation"
      },
      {
        "name": "Repair"
      },
      {
        "name": "Ceiling Cassette"
      },
      {
        "name": "Dismantling & Relocation"
      }
    ],
    "warranty": "1-Month Workmanship Warranty (3-Month Parts Warranty)",
    "i18n": {
      "ms": {
        "title": "Servis, Baiki & Pemasangan Aircond",
        "tagline": "Servis asas, cucian kimia, overhaul kimia, top-up gas, pembaikan, pemasangan baharu dan pembongkaran penghawa dingin untuk rumah dan pejabat di seluruh KL & Selangor. Dari RM 129.",
        "subServices": [
          {
            "name": "Servis Asas"
          },
          {
            "name": "Cucian Kimia"
          },
          {
            "name": "Overhaul Kimia"
          },
          {
            "name": "Top-Up Gas"
          },
          {
            "name": "Pemasangan"
          },
          {
            "name": "Pembaikan"
          },
          {
            "name": "Kaset Siling"
          },
          {
            "name": "Pembongkaran & Pindahan"
          }
        ],
        "warranty": "Jaminan Kerja 1 Bulan (Jaminan Alat Ganti 3 Bulan)"
      },
      "zh": {
        "title": "空调保养、维修与安装",
        "tagline": "为吉隆坡与雪兰莪的住宅和办公室提供空调基本保养、化学清洗、全面大修、加雪种、维修、新安装与拆除。从 RM 129 起。",
        "subServices": [
          {
            "name": "基本保养"
          },
          {
            "name": "化学清洗"
          },
          {
            "name": "化学大修"
          },
          {
            "name": "加雪种"
          },
          {
            "name": "安装"
          },
          {
            "name": "维修"
          },
          {
            "name": "天花卡式机"
          },
          {
            "name": "拆除与搬迁"
          }
        ],
        "warranty": "1 个月工艺保修（3 个月配件保修）"
      }
    }
  },
  "kitchen-renovation": {
    "slug": "kitchen-renovation",
    "title": "Kitchen Renovation",
    "startPrice": "RM 8,000",
    "icon": "cooking-pot",
    "tagline": "Complete kitchen makeover: hacking, tiling, waterproofing, cabinetry, countertop, plumbing, electrical and lighting across KL & Selangor. From RM 8,000.",
    "subServices": [
      {
        "name": "Full Kitchen Renovation"
      },
      {
        "name": "Kitchen Cabinet Installation"
      },
      {
        "name": "Kitchen Countertop Replacement"
      },
      {
        "name": "Kitchen Backsplash Tile Installation"
      },
      {
        "name": "Kitchen Island & Peninsula"
      },
      {
        "name": "Wet Kitchen Renovation"
      },
      {
        "name": "Dry Kitchen Renovation"
      },
      {
        "name": "Kitchen Extension"
      },
      {
        "name": "Kitchen Plumbing & Electrical"
      }
    ],
    "warranty": "12-Month Workmanship Warranty",
    "i18n": {
      "ms": {
        "title": "Pengubahsuaian Dapur",
        "tagline": "Makeover dapur lengkap: pecah, jubin, kalis air, kabinet, countertop, paip, elektrik dan pencahayaan di KL & Selangor. Dari RM 8,000.",
        "subServices": [
          {
            "name": "Pengubahsuaian Dapur Penuh"
          },
          {
            "name": "Pemasangan Kabinet Dapur"
          },
          {
            "name": "Penggantian Countertop Dapur"
          },
          {
            "name": "Pemasangan Jubin Backsplash Dapur"
          },
          {
            "name": "Island & Peninsula Dapur"
          },
          {
            "name": "Pengubahsuaian Dapur Basah"
          },
          {
            "name": "Pengubahsuaian Dapur Kering"
          },
          {
            "name": "Sambungan Dapur"
          },
          {
            "name": "Paip & Elektrik Dapur"
          }
        ],
        "warranty": "Jaminan Kerja 12 Bulan"
      },
      "zh": {
        "title": "厨房翻新",
        "tagline": "吉隆坡与雪兰莪全套厨房改造：拆除、贴砖、防水、橱柜、台面、水电与照明。从 RM 8,000 起。",
        "subServices": [
          {
            "name": "全套厨房翻新"
          },
          {
            "name": "厨房橱柜安装"
          },
          {
            "name": "厨房台面更换"
          },
          {
            "name": "厨房防溅墙瓷砖安装"
          },
          {
            "name": "厨房中岛与半岛"
          },
          {
            "name": "湿厨房翻新"
          },
          {
            "name": "干厨房翻新"
          },
          {
            "name": "厨房扩建"
          },
          {
            "name": "厨房水电"
          }
        ],
        "warranty": "12 个月工艺保修"
      }
    }
  },
  "bathroom-renovation": {
    "slug": "bathroom-renovation",
    "title": "Bathroom Renovation",
    "startPrice": "RM 6,000",
    "icon": "bath",
    "tagline": "Full bathroom and toilet makeover: hacking, waterproofing, tiling, plumbing, sanitary, electrical and ventilation in KL & Selangor. From RM 6,000.",
    "subServices": [
      {
        "name": "Full Bathroom Renovation"
      },
      {
        "name": "Toilet Renovation"
      },
      {
        "name": "Bathroom Makeover"
      },
      {
        "name": "Shower Area Renovation"
      },
      {
        "name": "Bathroom Tiling"
      },
      {
        "name": "Bathroom Waterproofing"
      },
      {
        "name": "Bathroom Plumbing"
      },
      {
        "name": "Sanitary Installation"
      },
      {
        "name": "Bathroom Floor Replacement"
      },
      {
        "name": "Bathroom Wall Tile Replacement"
      },
      {
        "name": "Bathroom Ceiling Repair"
      },
      {
        "name": "Bathroom Leak Repair"
      }
    ],
    "warranty": "12-Month Workmanship + Up to 5-Year Waterproofing Warranty",
    "i18n": {
      "ms": {
        "title": "Pengubahsuaian Bilik Mandi",
        "tagline": "Makeover bilik mandi dan tandas penuh: pecah, kalis air, jubin, paip, sanitari, elektrik dan pengudaraan di KL & Selangor. Dari RM 6,000.",
        "subServices": [
          {
            "name": "Pengubahsuaian Bilik Mandi Penuh"
          },
          {
            "name": "Pengubahsuaian Tandas"
          },
          {
            "name": "Makeover Bilik Mandi"
          },
          {
            "name": "Pengubahsuaian Kawasan Pancuran"
          },
          {
            "name": "Jubin Bilik Mandi"
          },
          {
            "name": "Kalis Air Bilik Mandi"
          },
          {
            "name": "Paip Bilik Mandi"
          },
          {
            "name": "Pemasangan Sanitari"
          },
          {
            "name": "Penggantian Lantai Bilik Mandi"
          },
          {
            "name": "Penggantian Jubin Dinding Bilik Mandi"
          },
          {
            "name": "Pembaikan Siling Bilik Mandi"
          },
          {
            "name": "Pembaikan Bocor Bilik Mandi"
          }
        ],
        "warranty": "Jaminan Kerja 12 Bulan + Jaminan Kalis Air Sehingga 5 Tahun"
      },
      "zh": {
        "title": "卫生间翻新",
        "tagline": "吉隆坡与雪兰莪全套卫生间与厕所改造：拆除、防水、贴砖、水管、洁具、电与通风。从 RM 6,000 起。",
        "subServices": [
          {
            "name": "全套卫生间翻新"
          },
          {
            "name": "厕所翻新"
          },
          {
            "name": "卫生间改造"
          },
          {
            "name": "淋浴区翻新"
          },
          {
            "name": "卫生间贴砖"
          },
          {
            "name": "卫生间防水"
          },
          {
            "name": "卫生间水管"
          },
          {
            "name": "洁具安装"
          },
          {
            "name": "卫生间地面更换"
          },
          {
            "name": "卫生间墙砖更换"
          },
          {
            "name": "卫生间天花维修"
          },
          {
            "name": "卫生间漏水维修"
          }
        ],
        "warranty": "12 个月工艺保修 + 最长 5 年防水保修"
      }
    }
  },
  "awning-installation": {
    "slug": "awning-installation",
    "title": "Awning Installation Services",
    "startPrice": "RM 380",
    "icon": "awning-canopy",
    "tagline": "Custom awnings and awning roofing for car porches, entrances, windows, balconies and yards across the Klang Valley (KL & Selangor) — polycarbonate, metal deck, aluminium composite (ACP), glass and fabric systems, plus retractable awnings and outdoor roller blinds, fabricated and installed to suit your site. Starting from RM 380 with per-sq-ft rates for every material, project-quoted with a 12-month workmanship warranty.",
    "subServices": [
      {
        "name": "Car Porch Awning Installation"
      },
      {
        "name": "Polycarbonate Awning"
      },
      {
        "name": "Metal Deck Awning"
      },
      {
        "name": "Aluminium Composite (ACP) Awning"
      },
      {
        "name": "Glass Awning"
      },
      {
        "name": "Canvas & Fabric Awning"
      },
      {
        "name": "Balcony, Patio & Window Awning"
      },
      {
        "name": "Awning Replacement & Repair"
      },
      {
        "name": "Outdoor Roller Blinds"
      }
    ],
    "warranty": "12-month workmanship warranty on fabrication & installation, as stated in your quotation",
    "i18n": {
      "ms": {
        "title": "Perkhidmatan Pemasangan Awning",
        "tagline": "Awning tersuai dan bumbung awning untuk car porch, pintu masuk, tingkap, balkoni dan halaman rumah di seluruh Lembah Klang (KL & Selangor) — sistem polikarbonat, metal deck, panel komposit aluminium (ACP), kaca dan fabrik, serta awning boleh-tarik dan bidai luar (roller blind), difabrikasi dan dipasang mengikut tapak anda. Bermula dari RM 380 dengan kadar sekaki persegi untuk setiap bahan, sebut harga projek dengan waranti mutu kerja 12 bulan.",
        "subServices": [
          {
            "name": "Pemasangan Awning Car Porch"
          },
          {
            "name": "Awning Polikarbonat"
          },
          {
            "name": "Awning Metal Deck"
          },
          {
            "name": "Awning Panel Komposit Aluminium (ACP)"
          },
          {
            "name": "Awning Kaca"
          },
          {
            "name": "Awning Kanvas & Fabrik"
          },
          {
            "name": "Awning Balkoni, Patio & Tingkap"
          },
          {
            "name": "Penggantian & Pembaikan Awning"
          },
          {
            "name": "Bidai Luar (Roller Blind)"
          }
        ],
        "warranty": "Waranti mutu kerja 12 bulan untuk fabrikasi & pemasangan, seperti yang dinyatakan dalam sebut harga anda"
      },
      "zh": {
        "title": "雨棚安装服务",
        "tagline": "为巴生谷（吉隆坡与雪兰莪）的车棚、入口、窗户、阳台及庭院定制雨棚与雨棚屋顶——聚碳酸酯、金属瓦、铝塑板（ACP）、玻璃与布艺系统，另有伸缩雨棚与户外卷帘，按现场尺寸制作安装。小型工程从 RM 380 起，每种材料均公布每平方尺起步价，按项目报价，含12个月工艺保修。",
        "subServices": [
          {
            "name": "车棚雨棚安装"
          },
          {
            "name": "聚碳酸酯雨棚"
          },
          {
            "name": "金属瓦雨棚"
          },
          {
            "name": "铝塑板（ACP）雨棚"
          },
          {
            "name": "玻璃雨棚"
          },
          {
            "name": "帆布与布艺雨棚"
          },
          {
            "name": "阳台、露台与窗户雨棚"
          },
          {
            "name": "雨棚更换与维修"
          },
          {
            "name": "户外卷帘"
          }
        ],
        "warranty": "12 个月制作与安装工艺保修，以报价单为准"
      }
    }
  }
};

export const serviceSummaryList = Object.values(serviceSummaryBySlug);
