// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-bp1-map.ts (npm run gen:bp1-map)
//
// BP-1 phase 1 programmatic-consolidation map.
//
// 37 of the 52 published suburbs are also coverage areas in
// `config/area-data.ts`. For those slugs the `/suburbs/<slug>/<svc>` URL is a
// literal duplicate of `/areas/<slug>/<svc>` (same place, same service, same
// offer) and is now 301-redirected instead of generated. The remaining
// 15 suburbs have no `/areas` twin and keep their own self-canonical
// `/suburbs/<slug>/<svc>` pages.
//
// AREA_SLUGS / SERVICE_SLUGS exist so the middleware can tell a *retired* URL
// apart from an *invented* one. Without them, /areas/not-a-place/painting/near-me
// answered 301 → /areas/not-a-place/painting → 404: a redirect onto a soft-404,
// which is worse for crawlers than the plain 404 the route returned before BP-1.
// With them a 301 only ever fires for a URL that genuinely was a generated page.
//
// This module is imported by `middleware.ts`, so it must stay tiny: no imports,
// no derivation, plain string arrays only.

/** Suburb slugs that are ALSO area slugs — their /suburbs/<slug>/<svc> URLs 301 to /areas/<slug>/<svc>. */
export const SUBURB_TWIN_SLUGS: readonly string[] = [
  "kuala-lumpur",
  "cheras",
  "ampang",
  "setapak",
  "wangsa-maju",
  "kepong",
  "sri-petaling",
  "bukit-jalil",
  "mont-kiara",
  "bangsar",
  "desa-parkcity",
  "taman-melawati",
  "petaling-jaya",
  "subang-jaya",
  "shah-alam",
  "puchong",
  "damansara",
  "kota-damansara",
  "ara-damansara",
  "sunway",
  "usj",
  "bandar-utama",
  "ss2",
  "klang",
  "setia-alam",
  "kota-kemuning",
  "batu-caves",
  "selayang",
  "rawang",
  "sungai-buloh",
  "kajang",
  "semenyih",
  "seri-kembangan",
  "pandan-indah",
  "putrajaya",
  "cyberjaya",
  "sentul",
];

/** Suburb slugs with NO /areas twin — these keep real, self-canonical /suburbs pages. */
export const SUBURB_ORIGINAL_SLUGS: readonly string[] = [
  "hulu-kelang",
  "port-klang",
  "bukit-tinggi",
  "meru",
  "bukit-jelutong",
  "glenmarie",
  "kundang",
  "balakong",
  "bandar-puteri",
  "dengkil",
  "selangor",
  "bandar-botanic",
  "kampung-baru",
  "kampung-pandan",
  "kampung-datuk-keramat",
];

/** Every coverage-area slug that has a generated /areas/<slug> hub. */
export const AREA_SLUGS: readonly string[] = [
  "kuala-lumpur",
  "petaling-jaya",
  "subang-jaya",
  "puchong",
  "shah-alam",
  "klang",
  "cheras",
  "ampang",
  "kajang",
  "mont-kiara",
  "bangsar",
  "damansara",
  "kepong",
  "setapak",
  "sri-petaling",
  "kota-damansara",
  "ara-damansara",
  "sunway",
  "usj",
  "putrajaya",
  "cyberjaya",
  "wangsa-maju",
  "bukit-jalil",
  "desa-parkcity",
  "taman-melawati",
  "bandar-utama",
  "ss2",
  "setia-alam",
  "kota-kemuning",
  "batu-caves",
  "selayang",
  "rawang",
  "sungai-buloh",
  "semenyih",
  "seri-kembangan",
  "pandan-indah",
  "sentul",
];

/** Every service slug that has a generated /services/<slug> page. */
export const SERVICE_SLUGS: readonly string[] = [
  "painting",
  "plumbing",
  "ceiling",
  "waterproofing",
  "handyman",
  "house-renovation",
  "electrical",
  "water-heater",
  "ceiling-fan",
  "lighting",
  "tiling",
  "plaster-ceiling",
  "skim-coat",
  "flooring",
  "epoxy-flooring",
  "roof-repair",
  "kitchen-cabinet",
  "carpentry",
  "door",
  "window-repair",
  "locksmith",
  "glass-aluminium",
  "cctv",
  "autogate",
  "welding",
  "aircon",
  "kitchen-renovation",
  "bathroom-renovation",
  "awning-installation",
];
