/**
 * BP-1 phase 1 — generates the programmatic-consolidation slug map.
 *
 * WHY THIS EXISTS
 * ---------------
 * 37 of the 52 suburbs in `config/suburb-data.ts` are ALSO published as
 * coverage areas in `config/area-data.ts`. Before BP-1 the site generated
 * `/suburbs/<x>/<svc>` for all 52 × 29 services (1,508 pages) and used a
 * `canonicalPath` override to point the 1,073 twin pages at their stronger
 * `/areas/<x>/<svc>` sibling. A canonical is a *hint* — Google still crawled,
 * rendered and stored 1,073 pages it was then told to discard, and any
 * internal link pointing at a twin leaked equity into a redirect hop.
 *
 * BP-1 phase 1 stops generating the twins entirely and 301s them to `/areas`.
 * The twin set is derived here (never hand-maintained) so it can never drift
 * from the data, and emitted as a deliberately tiny module because
 * `middleware.ts` imports it on every request — pulling `config/area-data.ts`
 * (66 KB) or `config/services-data.ts` (624 KB) into the edge bundle would be
 * a needless per-request cost.
 *
 * Run via `npm run gen:bp1-map` (wired into `prebuild` and `predev`).
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { areaPages } from "@/config/area-data";
import { suburbPages } from "@/config/suburb-data";
import { servicesData } from "@/config/services-data";

const OUT = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "config",
  "suburb-twin-slugs.generated.ts",
);

const areaSlugs = new Set(areaPages.map((area) => area.slug));
const suburbSlugs = suburbPages.map((suburb) => suburb.slug);

const duplicates = suburbSlugs.filter((slug, index) => suburbSlugs.indexOf(slug) !== index);
if (duplicates.length > 0) {
  console.error(`❌ gen:bp1-map — duplicate suburb slugs: ${[...new Set(duplicates)].join(", ")}`);
  process.exit(1);
}

const twinSlugs = suburbSlugs.filter((slug) => areaSlugs.has(slug));
const originalSlugs = suburbSlugs.filter((slug) => !areaSlugs.has(slug));

if (twinSlugs.length === 0) {
  console.error("❌ gen:bp1-map — derived 0 twin slugs; area/suburb data may have changed shape.");
  process.exit(1);
}

// Every twin must resolve to an area page that will actually exist after the
// build — a 301 to a 404 is worse than no redirect at all.
for (const slug of twinSlugs) {
  if (!areaPages.some((area) => area.slug === slug)) {
    console.error(`❌ gen:bp1-map — twin slug "${slug}" has no matching area page.`);
    process.exit(1);
  }
}

const banner = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-bp1-map.ts (npm run gen:bp1-map)
//
// BP-1 phase 1 programmatic-consolidation map.
//
// ${twinSlugs.length} of the ${suburbPages.length} published suburbs are also coverage areas in
// \`config/area-data.ts\`. For those slugs the \`/suburbs/<slug>/<svc>\` URL is a
// literal duplicate of \`/areas/<slug>/<svc>\` (same place, same service, same
// offer) and is now 301-redirected instead of generated. The remaining
// ${originalSlugs.length} suburbs have no \`/areas\` twin and keep their own self-canonical
// \`/suburbs/<slug>/<svc>\` pages.
//
// AREA_SLUGS / SERVICE_SLUGS exist so the middleware can tell a *retired* URL
// apart from an *invented* one. Without them, /areas/not-a-place/painting/near-me
// answered 301 → /areas/not-a-place/painting → 404: a redirect onto a soft-404,
// which is worse for crawlers than the plain 404 the route returned before BP-1.
// With them a 301 only ever fires for a URL that genuinely was a generated page.
//
// This module is imported by \`middleware.ts\`, so it must stay tiny: no imports,
// no derivation, plain string arrays only.

/** Suburb slugs that are ALSO area slugs — their /suburbs/<slug>/<svc> URLs 301 to /areas/<slug>/<svc>. */
export const SUBURB_TWIN_SLUGS: readonly string[] = [
${twinSlugs.map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}
];

/** Suburb slugs with NO /areas twin — these keep real, self-canonical /suburbs pages. */
export const SUBURB_ORIGINAL_SLUGS: readonly string[] = [
${originalSlugs.map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}
];

/** Every coverage-area slug that has a generated /areas/<slug> hub. */
export const AREA_SLUGS: readonly string[] = [
${areaPages.map((area) => `  ${JSON.stringify(area.slug)},`).join("\n")}
];

/** Every service slug that has a generated /services/<slug> page. */
export const SERVICE_SLUGS: readonly string[] = [
${Object.keys(servicesData).map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}
];
`;

await writeFile(OUT, banner, "utf8");

console.log(
  `✅ gen:bp1-map — ${twinSlugs.length} twin slugs (→ /areas) + ${originalSlugs.length} original slugs (kept) ` +
    `written to config/suburb-twin-slugs.generated.ts`,
);
