import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { servicesData } from "@/config/services-data";
import { problemPages, problemI18n } from "@/config/problem-data";
import { allGenericPages } from "@/config/content-data";
import { toolsContent } from "@/config/tools-data";
import { areaPages } from "@/config/area-data";
import { getLocalizedArea } from "@/lib/location-i18n";
import { DEDICATED_TOOL_BY_SERVICE } from "@/lib/estimator/service-estimator";

type Locale = "ms" | "zh";

type ServiceSummary = {
  slug: string;
  title: string;
  startPrice: string;
  icon: string;
  tagline: string;
  subServices: { name: string }[];
  warranty: string;
  i18n?: Partial<Record<Locale, {
    title: string;
    tagline: string;
    subServices: { name: string }[];
    warranty: string;
  }>>;
};

const serviceSummaries = Object.fromEntries(
  Object.entries(servicesData).map(([slug, service]) => {
    const summary: ServiceSummary = {
      slug: service.slug,
      title: service.title,
      startPrice: service.startPrice,
      icon: service.icon,
      tagline: service.tagline,
      subServices: service.subServices.map(({ name }) => ({ name })),
      warranty: service.warranty,
    };

    const locales = Object.entries(service.i18n ?? {}).map(([locale, localized]) => [
      locale,
      {
        title: localized.title || service.title,
        tagline: localized.tagline || service.tagline,
        subServices: (localized.subServices?.length ? localized.subServices : service.subServices).map(({ name }) => ({ name })),
        warranty: localized.warranty || service.warranty,
      },
    ]);

    if (locales.length) {
      summary.i18n = Object.fromEntries(locales);
    }

    return [slug, summary];
  })
);

const fileContents = `// AUTO-GENERATED FILE — do not edit by hand.\n// Generated by scripts/generate-service-summary.ts\n\nexport type ServiceSummary = {\n  slug: string;\n  title: string;\n  startPrice: string;\n  icon: string;\n  tagline: string;\n  subServices: { name: string }[];\n  warranty: string;\n  i18n?: Partial<Record<"ms" | "zh", {\n    title: string;\n    tagline: string;\n    subServices: { name: string }[];\n    warranty: string;\n  }>>;\n};\n\nexport const serviceSummaryBySlug: Record<string, ServiceSummary> = ${JSON.stringify(serviceSummaries, null, 2)};\n\nexport const serviceSummaryList = Object.values(serviceSummaryBySlug);\n`;

const serviceNavigation = Object.fromEntries(
  Object.values(serviceSummaries).map((service) => [service.slug, {
    slug: service.slug,
    title: service.title,
    startPrice: service.startPrice,
    i18n: {
      ms: { title: service.i18n?.ms?.title ?? service.title },
      zh: { title: service.i18n?.zh?.title ?? service.title }
    }
  }])
);
const navContents = `// AUTO-GENERATED FILE — do not edit by hand.\n// Compact client-safe service navigation and quote-picker data.\n\nexport type ServiceNavItem = { slug: string; title: string; startPrice: string; i18n: Record<"ms" | "zh", { title: string }> };\nexport const serviceNavBySlug: Record<string, ServiceNavItem> = ${JSON.stringify(serviceNavigation, null, 2)};\nexport const serviceNavList = Object.values(serviceNavBySlug);\n// Number of services in the registry — the ONLY source for "N+ services" copy\n// (homepage FAQ, smart finder, /services hub). Regenerated on every prebuild,\n// so a new service can never re-create the 28+/29 drift (P3-07).\nexport const SERVICE_COUNT = ${Object.keys(servicesData).length};\nexport function getLocalizedServiceNav(item: ServiceNavItem, locale: "en" | "ms" | "zh") {\n  return locale === "en" ? item : { ...item, title: item.i18n[locale].title };\n}\n`;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(__dirname, "../config/service-summary.generated.ts");
const navPath = path.resolve(__dirname, "../config/service-nav.generated.ts");

// ── Quote catalog ─────────────────────────────────────────────────────────
// The multi-step booking form and the MS/ZH pricing page need each service's
// sub-service *price* and *description*, which the lean service summary above
// deliberately omits. Without this file both components imported the full
// `config/services-data.ts` registry (~470 KB source / ~429 KB emitted chunk)
// into the browser just to render a picker — see the performance notes in
// lib/smart-finder-loader.ts. This carries only the fields those two screens
// actually render.
type QuoteCatalogSubService = { name: string; price: string; desc: string };
type QuoteCatalogEntry = {
  slug: string;
  title: string;
  startPrice: string;
  tagline: string;
  warranty: string;
  subServices: QuoteCatalogSubService[];
  i18n?: Partial<Record<Locale, {
    title: string;
    tagline: string;
    warranty: string;
    subServices: QuoteCatalogSubService[];
  }>>;
};

const quoteCatalog = Object.fromEntries(
  Object.entries(servicesData).map(([slug, service]) => {
    const pickSubs = (subs: typeof service.subServices): QuoteCatalogSubService[] =>
      subs.map(({ name, price, desc }) => ({ name, price, desc }));

    const entry: QuoteCatalogEntry = {
      slug: service.slug,
      title: service.title,
      startPrice: service.startPrice,
      tagline: service.tagline,
      warranty: service.warranty,
      subServices: pickSubs(service.subServices),
    };

    const locales = Object.entries(service.i18n ?? {}).map(([locale, localized]) => [
      locale,
      {
        title: localized.title || service.title,
        tagline: localized.tagline || service.tagline,
        warranty: localized.warranty || service.warranty,
        subServices: pickSubs(
          localized.subServices?.length ? localized.subServices : service.subServices
        ),
      },
    ]);

    if (locales.length) {
      entry.i18n = Object.fromEntries(locales);
    }

    return [slug, entry];
  })
);

const quoteCatalogContents = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe quote/pricing catalog: the sub-service name, price and blurb that
// the booking form and the localised pricing page render, and nothing else.
// Importing \`config/services-data.ts\` from a client component ships the entire
// content registry to the browser; import this instead.

export type QuoteCatalogSubService = { name: string; price: string; desc: string };
export type QuoteCatalogEntry = {
  slug: string;
  title: string;
  startPrice: string;
  tagline: string;
  warranty: string;
  subServices: QuoteCatalogSubService[];
  i18n?: Partial<Record<"ms" | "zh", {
    title: string;
    tagline: string;
    warranty: string;
    subServices: QuoteCatalogSubService[];
  }>>;
};

export const quoteCatalogBySlug: Record<string, QuoteCatalogEntry> = ${JSON.stringify(quoteCatalog, null, 2)};

export const quoteCatalogList = Object.values(quoteCatalogBySlug);

export function getLocalizedQuoteEntry(entry: QuoteCatalogEntry, locale: "en" | "ms" | "zh"): QuoteCatalogEntry {
  if (locale === "en") return entry;
  const override = entry.i18n?.[locale];
  if (!override) return entry;
  return {
    ...entry,
    title: override.title || entry.title,
    tagline: override.tagline || entry.tagline,
    warranty: override.warranty || entry.warranty,
    subServices: override.subServices?.length ? override.subServices : entry.subServices,
  };
}
`;

// ── Problem navigation cards ──────────────────────────────────────────────
// `RelatedProblems` renders four cards (title + symptom) on every service and
// sub-service page. It previously imported `config/problem-data.ts` (~224 KB
// emitted chunk) for two strings per problem.
type ProblemNavItem = {
  slug: string;
  serviceSlug: string;
  title: string;
  symptom: string;
  costRange: string;
  i18n?: Partial<Record<Locale, { title: string; symptom: string; costRange: string }>>;
};

const problemNav: ProblemNavItem[] = problemPages.map((problem) => {
  const item: ProblemNavItem = {
    slug: problem.slug,
    serviceSlug: problem.serviceSlug,
    title: problem.title,
    symptom: problem.symptom,
    costRange: problem.costRange,
  };

  const locales = (["ms", "zh"] as const)
    .map((locale) => {
      const override = problemI18n[problem.slug]?.[locale];
      if (!override) return null;
      return [
        locale,
        {
          title: override.title || problem.title,
          symptom: override.symptom || problem.symptom,
          costRange: override.costRange || problem.costRange,
        },
      ] as const;
    })
    .filter((pair): pair is NonNullable<typeof pair> => pair !== null);

  if (locales.length) {
    item.i18n = Object.fromEntries(locales);
  }

  return item;
});

const problemNavContents = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe problem link cards (title + symptom, trilingual). Import this
// from client components instead of \`config/problem-data.ts\`, which carries
// every cause, solution and FAQ for all problems.

export type ProblemNavItem = {
  slug: string;
  serviceSlug: string;
  title: string;
  symptom: string;
  costRange: string;
  i18n?: Partial<Record<"ms" | "zh", { title: string; symptom: string; costRange: string }>>;
};

export const problemNavList: ProblemNavItem[] = ${JSON.stringify(problemNav, null, 2)};

export function getLocalizedProblemNav(item: ProblemNavItem, locale: "en" | "ms" | "zh"): ProblemNavItem {
  if (locale === "en") return item;
  const override = item.i18n?.[locale];
  if (!override) return item;
  return {
    ...item,
    title: override.title || item.title,
    symptom: override.symptom || item.symptom,
    costRange: override.costRange || item.costRange,
  };
}
`;

// ── Generic content page navigation ──────────────────────────────────────
// `GenericContentPageView` renders a "related reading" grid of same-category
// siblings. It only needs slug/title/category/relatedServiceSlug, but importing
// `config/content-data.ts` for them dragged in `config/services-data.ts` (which
// content-data derives its pages from) on every /answers, /brands, /commercial,
// /compare, /guides, /process, /residential, /seasonal and /top page.
const contentNav = allGenericPages.map((page) => ({
  slug: page.slug,
  title: page.title,
  category: page.category,
  // Only the first 120 characters are ever rendered (as the sibling card blurb).
  intro: page.intro.slice(0, 120),
  ...(page.relatedServiceSlug ? { relatedServiceSlug: page.relatedServiceSlug } : {}),
}));

// The three "related service" links each content page renders. Precomputed
// here so the client never needs `services-data` for a title, a tagline and two
// sub-service blurbs.
const contentRelatedServiceLinks = Object.fromEntries(
  Object.values(servicesData).map((service) => [
    service.slug,
    {
      slug: service.slug,
      title: service.title,
      tagline: service.tagline,
      subServices: service.subServices.slice(0, 2).map(({ name, desc }) => ({ name, desc })),
    },
  ])
);

const contentNavContents = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe sibling index for the generic content pages. Import this from
// client components instead of \`config/content-data.ts\`.

export type ContentNavItem = {
  slug: string;
  title: string;
  category: string;
  /** First 120 characters of the page intro — the only part rendered on cards. */
  intro: string;
  relatedServiceSlug?: string;
};

export const contentNavList: ContentNavItem[] = ${JSON.stringify(contentNav, null, 2)};

export type ContentRelatedServiceLink = {
  slug: string;
  title: string;
  tagline: string;
  subServices: { name: string; desc: string }[];
};

export const contentRelatedServiceBySlug: Record<string, ContentRelatedServiceLink> = ${JSON.stringify(contentRelatedServiceLinks, null, 2)};
`;

const quoteCatalogPath = path.resolve(__dirname, "../config/quote-catalog.generated.ts");
const problemNavPath = path.resolve(__dirname, "../config/problem-nav.generated.ts");
// ── Dedicated-tool cards ──────────────────────────────────────────────────
// `ServiceEstimatorBlock` links six services to their hand-built calculator and
// renders that tool's name plus three headline stats. Reading them from
// `config/tools-data.ts` shipped ~150 KB of every calculator's full copy deck to
// the browser on all 28 service pages and all 112 sub-service pages.
const dedicatedToolCards = Object.fromEntries(
  [...new Set(Object.values(DEDICATED_TOOL_BY_SERVICE))].map((toolSlug) => {
    const tool = toolsContent[toolSlug];
    if (!tool) throw new Error(`DEDICATED_TOOL_BY_SERVICE references unknown tool "${toolSlug}"`);
    return [toolSlug, { slug: tool.slug, name: tool.name, stats: tool.stats.map(({ label, value }) => ({ label, value })) }];
  })
);

const dedicatedToolContents = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe cards for the six hand-built calculators linked from service
// pages. Import this instead of \`config/tools-data.ts\` in client components.

export type DedicatedToolCard = { slug: string; name: string; stats: { label: string; value: string }[] };

export const dedicatedToolCardBySlug: Record<string, DedicatedToolCard> = ${JSON.stringify(dedicatedToolCards, null, 2)};
`;

// ── Area navigation ───────────────────────────────────────────────────────
// The footer (every page) and the homepage service-area grid render an area's
// slug, name and state. Reading them from `config/area-data.ts` plus
// `lib/location-i18n.ts` shipped ~66 KB of area records and ~64 KB of area
// translations — descriptions, meta tags and FAQs — into every single page.
const areaNav = areaPages.map((area) => ({
  slug: area.slug,
  name: area.name,
  state: area.state,
  i18n: {
    ms: { name: getLocalizedArea(area, "ms").name },
    zh: { name: getLocalizedArea(area, "zh").name },
  },
}));

const areaNavContents = `// AUTO-GENERATED FILE — do not edit by hand.
// Generated by scripts/generate-service-summary.ts
//
// Client-safe area navigation: slug, state and trilingual name. Import this
// from client components instead of \`config/area-data.ts\` / \`lib/location-i18n\`.

export type AreaNavItem = { slug: string; name: string; state: string; i18n: Record<"ms" | "zh", { name: string }> };

export const areaNavList: AreaNavItem[] = ${JSON.stringify(areaNav, null, 2)};

export const areaNavBySlug: Record<string, AreaNavItem> = Object.fromEntries(
  areaNavList.map((area) => [area.slug, area])
);

export function getLocalizedAreaName(area: AreaNavItem, locale: "en" | "ms" | "zh"): string {
  return locale === "en" ? area.name : area.i18n[locale].name || area.name;
}
`;

const contentNavPath = path.resolve(__dirname, "../config/content-nav.generated.ts");
const dedicatedToolPath = path.resolve(__dirname, "../config/dedicated-tool-cards.generated.ts");
const areaNavPath = path.resolve(__dirname, "../config/area-nav.generated.ts");

await Promise.all([
  writeFile(outPath, fileContents),
  writeFile(navPath, navContents),
  writeFile(quoteCatalogPath, quoteCatalogContents),
  writeFile(problemNavPath, problemNavContents),
  writeFile(contentNavPath, contentNavContents),
  writeFile(dedicatedToolPath, dedicatedToolContents),
  writeFile(areaNavPath, areaNavContents),
]);

console.log(`✓ Service summary generated → ${path.relative(process.cwd(), outPath)}`);
console.log(`✓ Compact service navigation generated → ${path.relative(process.cwd(), navPath)}`);
console.log(`✓ Client quote catalog generated → ${path.relative(process.cwd(), quoteCatalogPath)}`);
console.log(`✓ Client problem navigation generated → ${path.relative(process.cwd(), problemNavPath)}`);
console.log(`✓ Client content navigation generated → ${path.relative(process.cwd(), contentNavPath)}`);
console.log(`✓ Client dedicated-tool cards generated → ${path.relative(process.cwd(), dedicatedToolPath)}`);
console.log(`✓ Client area navigation generated → ${path.relative(process.cwd(), areaNavPath)}`);

