import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { servicesData } from "@/config/services-data";

type Locale = "ms" | "zh";

type ServiceSummary = {
  slug: string;
  title: string;
  startPrice: string;
  icon: string;
  tagline: string;
  subServices: { name: string }[];
  warranty: string;
  i18n?: Partial<Record<Locale, {
    title: string;
    tagline: string;
    subServices: { name: string }[];
    warranty: string;
  }>>;
};

const serviceSummaries = Object.fromEntries(
  Object.entries(servicesData).map(([slug, service]) => {
    const summary: ServiceSummary = {
      slug: service.slug,
      title: service.title,
      startPrice: service.startPrice,
      icon: service.icon,
      tagline: service.tagline,
      subServices: service.subServices.map(({ name }) => ({ name })),
      warranty: service.warranty,
    };

    const locales = Object.entries(service.i18n ?? {}).map(([locale, localized]) => [
      locale,
      {
        title: localized.title || service.title,
        tagline: localized.tagline || service.tagline,
        subServices: (localized.subServices?.length ? localized.subServices : service.subServices).map(({ name }) => ({ name })),
        warranty: localized.warranty || service.warranty,
      },
    ]);

    if (locales.length) {
      summary.i18n = Object.fromEntries(locales);
    }

    return [slug, summary];
  })
);

const fileContents = `// AUTO-GENERATED FILE — do not edit by hand.\n// Generated by scripts/generate-service-summary.ts\n\nexport type ServiceSummary = {\n  slug: string;\n  title: string;\n  startPrice: string;\n  icon: string;\n  tagline: string;\n  subServices: { name: string }[];\n  warranty: string;\n  i18n?: Partial<Record<"ms" | "zh", {\n    title: string;\n    tagline: string;\n    subServices: { name: string }[];\n    warranty: string;\n  }>>;\n};\n\nexport const serviceSummaryBySlug: Record<string, ServiceSummary> = ${JSON.stringify(serviceSummaries, null, 2)};\n\nexport const serviceSummaryList = Object.values(serviceSummaryBySlug);\n`;

const serviceNavigation = Object.fromEntries(
  Object.values(serviceSummaries).map((service) => [service.slug, {
    slug: service.slug,
    title: service.title,
    startPrice: service.startPrice,
    i18n: {
      ms: { title: service.i18n?.ms?.title ?? service.title },
      zh: { title: service.i18n?.zh?.title ?? service.title }
    }
  }])
);
const navContents = `// AUTO-GENERATED FILE — do not edit by hand.\n// Compact client-safe service navigation and quote-picker data.\n\nexport type ServiceNavItem = { slug: string; title: string; startPrice: string; i18n: Record<"ms" | "zh", { title: string }> };\nexport const serviceNavBySlug: Record<string, ServiceNavItem> = ${JSON.stringify(serviceNavigation, null, 2)};\nexport const serviceNavList = Object.values(serviceNavBySlug);\nexport function getLocalizedServiceNav(item: ServiceNavItem, locale: "en" | "ms" | "zh") {\n  return locale === "en" ? item : { ...item, title: item.i18n[locale].title };\n}\n`;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(__dirname, "../config/service-summary.generated.ts");
const navPath = path.resolve(__dirname, "../config/service-nav.generated.ts");
await Promise.all([writeFile(outPath, fileContents), writeFile(navPath, navContents)]);

console.log(`✓ Service summary generated → ${path.relative(process.cwd(), outPath)}`);
console.log(`✓ Compact service navigation generated → ${path.relative(process.cwd(), navPath)}`);
